// Reflow Config service — the app-config surface.
//
// Config owns the *logical* config that shapes what runs on the
// cluster: handler deployments, event-source bindings, inbound
// webhook bindings, and the named-secret table consumers reference.
// It is the developer-facing counterpart to
// reflow.clusterctl.v1.ClusterCtl (which owns cluster topology, DR,
// and routing). Naming mirrors Restate's split between
// `cluster-ctrl` (cluster admin) and `admin` (app config), with the
// terminology flipped to avoid the overloaded word "admin".
//
// Every reflowd process hosts a Config Connect RPC server on the
// admin listener (same port as ClusterCtl in step 1; a follow-on may
// move Config onto its own port if/when we want different network
// exposure). The server is mTLS-protected; today's starter policy
// gates /reflow.config.v1.Config/* to operator/* principals — same as
// ClusterCtl. The separation of services is the seam for later
// delegating Config to a narrower credential (tenant admin, CI
// service account) without loosening cluster-control authority.
//
// All mutating RPCs propose Command_* commands to shard 0 with a
// table-revision CAS guard (if_table_revision_eq=0 disables CAS); the
// FSM signals a CAS mismatch via Result.Value =
// ResultValueFailedPrecondition, which the server surfaces as
// connect.CodeFailedPrecondition. Read RPCs route to a local shard-0
// replica via SyncRead.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: configv1/config.proto

package configv1

import (
	enginev1 "github.com/twinfer/reflow/proto/enginev1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterDeploymentRequest names a handler endpoint reachable over
// HTTP/2. URL scheme must be http:// or https://; the engine dials
// the handler via Connect RPC.
type RegisterDeploymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional per-invocation cap on journal entries for this
	// deployment. 0 = engine default (10_000). The engine clamps to a
	// hard ceiling (100_000).
	MaxJournalEntries uint32 `protobuf:"varint,2,opt,name=max_journal_entries,json=maxJournalEntries,proto3" json:"max_journal_entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterDeploymentRequest) Reset() {
	*x = RegisterDeploymentRequest{}
	mi := &file_configv1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeploymentRequest) ProtoMessage() {}

func (x *RegisterDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeploymentRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDeploymentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterDeploymentRequest) GetMaxJournalEntries() uint32 {
	if x != nil {
		return x.MaxJournalEntries
	}
	return 0
}

type RegisterDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeploymentResponse) Reset() {
	*x = RegisterDeploymentResponse{}
	mi := &file_configv1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeploymentResponse) ProtoMessage() {}

func (x *RegisterDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeploymentResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeploymentResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsRequest) Reset() {
	*x = ListDeploymentsRequest{}
	mi := &file_configv1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsRequest) ProtoMessage() {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{2}
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Deployments   []*enginev1.DeploymentRecord `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	TableRevision uint64                       `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_configv1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeploymentsResponse) GetDeployments() []*enginev1.DeploymentRecord {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *ListDeploymentsResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DescribeDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeDeploymentRequest) Reset() {
	*x = DescribeDeploymentRequest{}
	mi := &file_configv1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeDeploymentRequest) ProtoMessage() {}

func (x *DescribeDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DescribeDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DescribeDeploymentResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Deployment    *enginev1.DeploymentRecord `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeDeploymentResponse) Reset() {
	*x = DescribeDeploymentResponse{}
	mi := &file_configv1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeDeploymentResponse) ProtoMessage() {}

func (x *DescribeDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeDeploymentResponse.ProtoReflect.Descriptor instead.
func (*DescribeDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeDeploymentResponse) GetDeployment() *enginev1.DeploymentRecord {
	if x != nil {
		return x.Deployment
	}
	return nil
}

// DeleteDeploymentRequest names one deployment by id. force must be
// true to confirm the operator accepts that in-flight invocations
// referencing this deployment may break. if_table_revision_eq=0
// disables CAS; non-zero requires the deployment table revision to
// match (CodeFailedPrecondition on mismatch).
type DeleteDeploymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId      string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Force             bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,3,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteDeploymentRequest) Reset() {
	*x = DeleteDeploymentRequest{}
	mi := &file_configv1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentRequest) ProtoMessage() {}

func (x *DeleteDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeleteDeploymentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DeleteDeploymentRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type DeleteDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeploymentResponse) Reset() {
	*x = DeleteDeploymentResponse{}
	mi := &file_configv1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentResponse) ProtoMessage() {}

func (x *DeleteDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDeploymentResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// UpsertEventSourceRequest carries one EventSourceRecord plus an
// optional CAS guard. if_table_revision_eq=0 disables CAS.
type UpsertEventSourceRequest struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Record            *enginev1.EventSourceRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	IfTableRevisionEq uint64                      `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertEventSourceRequest) Reset() {
	*x = UpsertEventSourceRequest{}
	mi := &file_configv1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEventSourceRequest) ProtoMessage() {}

func (x *UpsertEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEventSourceRequest.ProtoReflect.Descriptor instead.
func (*UpsertEventSourceRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertEventSourceRequest) GetRecord() *enginev1.EventSourceRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpsertEventSourceRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type UpsertEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEventSourceResponse) Reset() {
	*x = UpsertEventSourceResponse{}
	mi := &file_configv1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEventSourceResponse) ProtoMessage() {}

func (x *UpsertEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEventSourceResponse.ProtoReflect.Descriptor instead.
func (*UpsertEventSourceResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertEventSourceResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DeleteEventSourceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteEventSourceRequest) Reset() {
	*x = DeleteEventSourceRequest{}
	mi := &file_configv1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventSourceRequest) ProtoMessage() {}

func (x *DeleteEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventSourceRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteEventSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteEventSourceRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type DeleteEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventSourceResponse) Reset() {
	*x = DeleteEventSourceResponse{}
	mi := &file_configv1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventSourceResponse) ProtoMessage() {}

func (x *DeleteEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventSourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventSourceResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEventSourceResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type ListEventSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesRequest) Reset() {
	*x = ListEventSourcesRequest{}
	mi := &file_configv1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesRequest) ProtoMessage() {}

func (x *ListEventSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListEventSourcesRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{12}
}

type ListEventSourcesResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Sources       []*enginev1.EventSourceRecord `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	TableRevision uint64                        `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesResponse) Reset() {
	*x = ListEventSourcesResponse{}
	mi := &file_configv1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesResponse) ProtoMessage() {}

func (x *ListEventSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListEventSourcesResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{13}
}

func (x *ListEventSourcesResponse) GetSources() []*enginev1.EventSourceRecord {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListEventSourcesResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// UpsertWebhookSourceRequest carries one WebhookSourceRecord plus an
// optional CAS guard. if_table_revision_eq=0 disables CAS.
type UpsertWebhookSourceRequest struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	Record            *enginev1.WebhookSourceRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	IfTableRevisionEq uint64                        `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertWebhookSourceRequest) Reset() {
	*x = UpsertWebhookSourceRequest{}
	mi := &file_configv1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWebhookSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWebhookSourceRequest) ProtoMessage() {}

func (x *UpsertWebhookSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWebhookSourceRequest.ProtoReflect.Descriptor instead.
func (*UpsertWebhookSourceRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{14}
}

func (x *UpsertWebhookSourceRequest) GetRecord() *enginev1.WebhookSourceRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpsertWebhookSourceRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type UpsertWebhookSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWebhookSourceResponse) Reset() {
	*x = UpsertWebhookSourceResponse{}
	mi := &file_configv1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWebhookSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWebhookSourceResponse) ProtoMessage() {}

func (x *UpsertWebhookSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWebhookSourceResponse.ProtoReflect.Descriptor instead.
func (*UpsertWebhookSourceResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{15}
}

func (x *UpsertWebhookSourceResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DeleteWebhookSourceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteWebhookSourceRequest) Reset() {
	*x = DeleteWebhookSourceRequest{}
	mi := &file_configv1_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookSourceRequest) ProtoMessage() {}

func (x *DeleteWebhookSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookSourceRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteWebhookSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteWebhookSourceRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type DeleteWebhookSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookSourceResponse) Reset() {
	*x = DeleteWebhookSourceResponse{}
	mi := &file_configv1_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookSourceResponse) ProtoMessage() {}

func (x *DeleteWebhookSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookSourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookSourceResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteWebhookSourceResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type ListWebhookSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookSourcesRequest) Reset() {
	*x = ListWebhookSourcesRequest{}
	mi := &file_configv1_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookSourcesRequest) ProtoMessage() {}

func (x *ListWebhookSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListWebhookSourcesRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{18}
}

type ListWebhookSourcesResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Sources       []*enginev1.WebhookSourceRecord `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	TableRevision uint64                          `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookSourcesResponse) Reset() {
	*x = ListWebhookSourcesResponse{}
	mi := &file_configv1_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookSourcesResponse) ProtoMessage() {}

func (x *ListWebhookSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListWebhookSourcesResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{19}
}

func (x *ListWebhookSourcesResponse) GetSources() []*enginev1.WebhookSourceRecord {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListWebhookSourcesResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// UpsertSecretRequest carries one SecretRecord plus an optional CAS
// guard. if_table_revision_eq=0 disables CAS.
type UpsertSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Record            *enginev1.SecretRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertSecretRequest) Reset() {
	*x = UpsertSecretRequest{}
	mi := &file_configv1_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSecretRequest) ProtoMessage() {}

func (x *UpsertSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSecretRequest.ProtoReflect.Descriptor instead.
func (*UpsertSecretRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{20}
}

func (x *UpsertSecretRequest) GetRecord() *enginev1.SecretRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpsertSecretRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type UpsertSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSecretResponse) Reset() {
	*x = UpsertSecretResponse{}
	mi := &file_configv1_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSecretResponse) ProtoMessage() {}

func (x *UpsertSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSecretResponse.ProtoReflect.Descriptor instead.
func (*UpsertSecretResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{21}
}

func (x *UpsertSecretResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DeleteSecretRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_configv1_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSecretRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_configv1_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSecretResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_configv1_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{24}
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Records       []*enginev1.SecretRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	TableRevision uint64                   `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_configv1_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{25}
}

func (x *ListSecretsResponse) GetRecords() []*enginev1.SecretRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListSecretsResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// LeaderHint is attached as a connect.Error detail on
// connect.CodeUnavailable returned by mutating Config RPCs when the
// receiving node is not the metadata leader. Clients extract it, dial
// admin_endpoint, retry. Same shape as clusterctlv1.LeaderHint;
// duplicated here so configv1 is self-contained.
type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AdminEndpoint string                 `protobuf:"bytes,2,opt,name=admin_endpoint,json=adminEndpoint,proto3" json:"admin_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_configv1_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_configv1_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_configv1_config_proto_rawDescGZIP(), []int{26}
}

func (x *LeaderHint) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LeaderHint) GetAdminEndpoint() string {
	if x != nil {
		return x.AdminEndpoint
	}
	return ""
}

var File_configv1_config_proto protoreflect.FileDescriptor

const file_configv1_config_proto_rawDesc = "" +
	"\n" +
	"\x15configv1/config.proto\x12\x10reflow.config.v1\x1a\x15enginev1/engine.proto\"]\n" +
	"\x19RegisterDeploymentRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12.\n" +
	"\x13max_journal_entries\x18\x02 \x01(\rR\x11maxJournalEntries\"A\n" +
	"\x1aRegisterDeploymentResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"\x18\n" +
	"\x16ListDeploymentsRequest\"\x86\x01\n" +
	"\x17ListDeploymentsResponse\x12D\n" +
	"\vdeployments\x18\x01 \x03(\v2\".reflow.engine.v1.DeploymentRecordR\vdeployments\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"@\n" +
	"\x19DescribeDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"`\n" +
	"\x1aDescribeDeploymentResponse\x12B\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\".reflow.engine.v1.DeploymentRecordR\n" +
	"deployment\"\x85\x01\n" +
	"\x17DeleteDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12/\n" +
	"\x14if_table_revision_eq\x18\x03 \x01(\x04R\x11ifTableRevisionEq\"A\n" +
	"\x18DeleteDeploymentResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"\x88\x01\n" +
	"\x18UpsertEventSourceRequest\x12;\n" +
	"\x06record\x18\x01 \x01(\v2#.reflow.engine.v1.EventSourceRecordR\x06record\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"B\n" +
	"\x19UpsertEventSourceResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"_\n" +
	"\x18DeleteEventSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"B\n" +
	"\x19DeleteEventSourceResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"\x19\n" +
	"\x17ListEventSourcesRequest\"\x80\x01\n" +
	"\x18ListEventSourcesResponse\x12=\n" +
	"\asources\x18\x01 \x03(\v2#.reflow.engine.v1.EventSourceRecordR\asources\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"\x8c\x01\n" +
	"\x1aUpsertWebhookSourceRequest\x12=\n" +
	"\x06record\x18\x01 \x01(\v2%.reflow.engine.v1.WebhookSourceRecordR\x06record\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"D\n" +
	"\x1bUpsertWebhookSourceResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"a\n" +
	"\x1aDeleteWebhookSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"D\n" +
	"\x1bDeleteWebhookSourceResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"\x1b\n" +
	"\x19ListWebhookSourcesRequest\"\x84\x01\n" +
	"\x1aListWebhookSourcesResponse\x12?\n" +
	"\asources\x18\x01 \x03(\v2%.reflow.engine.v1.WebhookSourceRecordR\asources\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"~\n" +
	"\x13UpsertSecretRequest\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.reflow.engine.v1.SecretRecordR\x06record\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"=\n" +
	"\x14UpsertSecretResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"Z\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"=\n" +
	"\x14DeleteSecretResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"\x14\n" +
	"\x12ListSecretsRequest\"v\n" +
	"\x13ListSecretsResponse\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.reflow.engine.v1.SecretRecordR\arecords\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"L\n" +
	"\n" +
	"LeaderHint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12%\n" +
	"\x0eadmin_endpoint\x18\x02 \x01(\tR\radminEndpoint2\xf7\n" +
	"\n" +
	"\x06Config\x12o\n" +
	"\x12RegisterDeployment\x12+.reflow.config.v1.RegisterDeploymentRequest\x1a,.reflow.config.v1.RegisterDeploymentResponse\x12f\n" +
	"\x0fListDeployments\x12(.reflow.config.v1.ListDeploymentsRequest\x1a).reflow.config.v1.ListDeploymentsResponse\x12o\n" +
	"\x12DescribeDeployment\x12+.reflow.config.v1.DescribeDeploymentRequest\x1a,.reflow.config.v1.DescribeDeploymentResponse\x12i\n" +
	"\x10DeleteDeployment\x12).reflow.config.v1.DeleteDeploymentRequest\x1a*.reflow.config.v1.DeleteDeploymentResponse\x12l\n" +
	"\x11UpsertEventSource\x12*.reflow.config.v1.UpsertEventSourceRequest\x1a+.reflow.config.v1.UpsertEventSourceResponse\x12l\n" +
	"\x11DeleteEventSource\x12*.reflow.config.v1.DeleteEventSourceRequest\x1a+.reflow.config.v1.DeleteEventSourceResponse\x12i\n" +
	"\x10ListEventSources\x12).reflow.config.v1.ListEventSourcesRequest\x1a*.reflow.config.v1.ListEventSourcesResponse\x12r\n" +
	"\x13UpsertWebhookSource\x12,.reflow.config.v1.UpsertWebhookSourceRequest\x1a-.reflow.config.v1.UpsertWebhookSourceResponse\x12r\n" +
	"\x13DeleteWebhookSource\x12,.reflow.config.v1.DeleteWebhookSourceRequest\x1a-.reflow.config.v1.DeleteWebhookSourceResponse\x12o\n" +
	"\x12ListWebhookSources\x12+.reflow.config.v1.ListWebhookSourcesRequest\x1a,.reflow.config.v1.ListWebhookSourcesResponse\x12]\n" +
	"\fUpsertSecret\x12%.reflow.config.v1.UpsertSecretRequest\x1a&.reflow.config.v1.UpsertSecretResponse\x12]\n" +
	"\fDeleteSecret\x12%.reflow.config.v1.DeleteSecretRequest\x1a&.reflow.config.v1.DeleteSecretResponse\x12Z\n" +
	"\vListSecrets\x12$.reflow.config.v1.ListSecretsRequest\x1a%.reflow.config.v1.ListSecretsResponseB3Z1github.com/twinfer/reflow/proto/configv1;configv1b\x06proto3"

var (
	file_configv1_config_proto_rawDescOnce sync.Once
	file_configv1_config_proto_rawDescData []byte
)

func file_configv1_config_proto_rawDescGZIP() []byte {
	file_configv1_config_proto_rawDescOnce.Do(func() {
		file_configv1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configv1_config_proto_rawDesc), len(file_configv1_config_proto_rawDesc)))
	})
	return file_configv1_config_proto_rawDescData
}

var file_configv1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_configv1_config_proto_goTypes = []any{
	(*RegisterDeploymentRequest)(nil),    // 0: reflow.config.v1.RegisterDeploymentRequest
	(*RegisterDeploymentResponse)(nil),   // 1: reflow.config.v1.RegisterDeploymentResponse
	(*ListDeploymentsRequest)(nil),       // 2: reflow.config.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),      // 3: reflow.config.v1.ListDeploymentsResponse
	(*DescribeDeploymentRequest)(nil),    // 4: reflow.config.v1.DescribeDeploymentRequest
	(*DescribeDeploymentResponse)(nil),   // 5: reflow.config.v1.DescribeDeploymentResponse
	(*DeleteDeploymentRequest)(nil),      // 6: reflow.config.v1.DeleteDeploymentRequest
	(*DeleteDeploymentResponse)(nil),     // 7: reflow.config.v1.DeleteDeploymentResponse
	(*UpsertEventSourceRequest)(nil),     // 8: reflow.config.v1.UpsertEventSourceRequest
	(*UpsertEventSourceResponse)(nil),    // 9: reflow.config.v1.UpsertEventSourceResponse
	(*DeleteEventSourceRequest)(nil),     // 10: reflow.config.v1.DeleteEventSourceRequest
	(*DeleteEventSourceResponse)(nil),    // 11: reflow.config.v1.DeleteEventSourceResponse
	(*ListEventSourcesRequest)(nil),      // 12: reflow.config.v1.ListEventSourcesRequest
	(*ListEventSourcesResponse)(nil),     // 13: reflow.config.v1.ListEventSourcesResponse
	(*UpsertWebhookSourceRequest)(nil),   // 14: reflow.config.v1.UpsertWebhookSourceRequest
	(*UpsertWebhookSourceResponse)(nil),  // 15: reflow.config.v1.UpsertWebhookSourceResponse
	(*DeleteWebhookSourceRequest)(nil),   // 16: reflow.config.v1.DeleteWebhookSourceRequest
	(*DeleteWebhookSourceResponse)(nil),  // 17: reflow.config.v1.DeleteWebhookSourceResponse
	(*ListWebhookSourcesRequest)(nil),    // 18: reflow.config.v1.ListWebhookSourcesRequest
	(*ListWebhookSourcesResponse)(nil),   // 19: reflow.config.v1.ListWebhookSourcesResponse
	(*UpsertSecretRequest)(nil),          // 20: reflow.config.v1.UpsertSecretRequest
	(*UpsertSecretResponse)(nil),         // 21: reflow.config.v1.UpsertSecretResponse
	(*DeleteSecretRequest)(nil),          // 22: reflow.config.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),         // 23: reflow.config.v1.DeleteSecretResponse
	(*ListSecretsRequest)(nil),           // 24: reflow.config.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),          // 25: reflow.config.v1.ListSecretsResponse
	(*LeaderHint)(nil),                   // 26: reflow.config.v1.LeaderHint
	(*enginev1.DeploymentRecord)(nil),    // 27: reflow.engine.v1.DeploymentRecord
	(*enginev1.EventSourceRecord)(nil),   // 28: reflow.engine.v1.EventSourceRecord
	(*enginev1.WebhookSourceRecord)(nil), // 29: reflow.engine.v1.WebhookSourceRecord
	(*enginev1.SecretRecord)(nil),        // 30: reflow.engine.v1.SecretRecord
}
var file_configv1_config_proto_depIdxs = []int32{
	27, // 0: reflow.config.v1.ListDeploymentsResponse.deployments:type_name -> reflow.engine.v1.DeploymentRecord
	27, // 1: reflow.config.v1.DescribeDeploymentResponse.deployment:type_name -> reflow.engine.v1.DeploymentRecord
	28, // 2: reflow.config.v1.UpsertEventSourceRequest.record:type_name -> reflow.engine.v1.EventSourceRecord
	28, // 3: reflow.config.v1.ListEventSourcesResponse.sources:type_name -> reflow.engine.v1.EventSourceRecord
	29, // 4: reflow.config.v1.UpsertWebhookSourceRequest.record:type_name -> reflow.engine.v1.WebhookSourceRecord
	29, // 5: reflow.config.v1.ListWebhookSourcesResponse.sources:type_name -> reflow.engine.v1.WebhookSourceRecord
	30, // 6: reflow.config.v1.UpsertSecretRequest.record:type_name -> reflow.engine.v1.SecretRecord
	30, // 7: reflow.config.v1.ListSecretsResponse.records:type_name -> reflow.engine.v1.SecretRecord
	0,  // 8: reflow.config.v1.Config.RegisterDeployment:input_type -> reflow.config.v1.RegisterDeploymentRequest
	2,  // 9: reflow.config.v1.Config.ListDeployments:input_type -> reflow.config.v1.ListDeploymentsRequest
	4,  // 10: reflow.config.v1.Config.DescribeDeployment:input_type -> reflow.config.v1.DescribeDeploymentRequest
	6,  // 11: reflow.config.v1.Config.DeleteDeployment:input_type -> reflow.config.v1.DeleteDeploymentRequest
	8,  // 12: reflow.config.v1.Config.UpsertEventSource:input_type -> reflow.config.v1.UpsertEventSourceRequest
	10, // 13: reflow.config.v1.Config.DeleteEventSource:input_type -> reflow.config.v1.DeleteEventSourceRequest
	12, // 14: reflow.config.v1.Config.ListEventSources:input_type -> reflow.config.v1.ListEventSourcesRequest
	14, // 15: reflow.config.v1.Config.UpsertWebhookSource:input_type -> reflow.config.v1.UpsertWebhookSourceRequest
	16, // 16: reflow.config.v1.Config.DeleteWebhookSource:input_type -> reflow.config.v1.DeleteWebhookSourceRequest
	18, // 17: reflow.config.v1.Config.ListWebhookSources:input_type -> reflow.config.v1.ListWebhookSourcesRequest
	20, // 18: reflow.config.v1.Config.UpsertSecret:input_type -> reflow.config.v1.UpsertSecretRequest
	22, // 19: reflow.config.v1.Config.DeleteSecret:input_type -> reflow.config.v1.DeleteSecretRequest
	24, // 20: reflow.config.v1.Config.ListSecrets:input_type -> reflow.config.v1.ListSecretsRequest
	1,  // 21: reflow.config.v1.Config.RegisterDeployment:output_type -> reflow.config.v1.RegisterDeploymentResponse
	3,  // 22: reflow.config.v1.Config.ListDeployments:output_type -> reflow.config.v1.ListDeploymentsResponse
	5,  // 23: reflow.config.v1.Config.DescribeDeployment:output_type -> reflow.config.v1.DescribeDeploymentResponse
	7,  // 24: reflow.config.v1.Config.DeleteDeployment:output_type -> reflow.config.v1.DeleteDeploymentResponse
	9,  // 25: reflow.config.v1.Config.UpsertEventSource:output_type -> reflow.config.v1.UpsertEventSourceResponse
	11, // 26: reflow.config.v1.Config.DeleteEventSource:output_type -> reflow.config.v1.DeleteEventSourceResponse
	13, // 27: reflow.config.v1.Config.ListEventSources:output_type -> reflow.config.v1.ListEventSourcesResponse
	15, // 28: reflow.config.v1.Config.UpsertWebhookSource:output_type -> reflow.config.v1.UpsertWebhookSourceResponse
	17, // 29: reflow.config.v1.Config.DeleteWebhookSource:output_type -> reflow.config.v1.DeleteWebhookSourceResponse
	19, // 30: reflow.config.v1.Config.ListWebhookSources:output_type -> reflow.config.v1.ListWebhookSourcesResponse
	21, // 31: reflow.config.v1.Config.UpsertSecret:output_type -> reflow.config.v1.UpsertSecretResponse
	23, // 32: reflow.config.v1.Config.DeleteSecret:output_type -> reflow.config.v1.DeleteSecretResponse
	25, // 33: reflow.config.v1.Config.ListSecrets:output_type -> reflow.config.v1.ListSecretsResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_configv1_config_proto_init() }
func file_configv1_config_proto_init() {
	if File_configv1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configv1_config_proto_rawDesc), len(file_configv1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configv1_config_proto_goTypes,
		DependencyIndexes: file_configv1_config_proto_depIdxs,
		MessageInfos:      file_configv1_config_proto_msgTypes,
	}.Build()
	File_configv1_config_proto = out.File
	file_configv1_config_proto_goTypes = nil
	file_configv1_config_proto_depIdxs = nil
}
