// Reflow Bootstrap service — kubeadm-style joiner credential exchange.
//
// The bootstrap surface is a single RPC: SignCSR. A joiner that has been
// issued a one-time `reflowd config create-join-token` plaintext sends a
// CertificateSigningRequest plus the token to a cluster member; the
// member verifies the token against shard 0's JoinTokenTable, proposes
// ConsumeJoinToken to atomically mark the row spent, then signs the CSR
// against the cluster CA (the same path the per-node ClusterIssuer uses
// for leaf renewal). The joiner persists the returned leaf to its
// data-dir/certmagic store and proceeds with normal SelfJoin (for node
// kind) or returns the leaf to the operator client (for operator kind).
//
// The bootstrap listener is intentionally segregated from the admin /
// clusterctl listeners. Admin uses RequireAndVerifyClientCert (you need
// a mesh-issued leaf to talk to it); bootstrap accepts unauthenticated
// TLS so a freshly-installed joiner with no leaf yet can reach the
// service. Authentication is *intrinsic to the request* — the join
// token is what authorizes the cert issuance, not a TLS peer cert.
//
// The endpoint is opt-in. Operators set cfg.Bootstrap.Addr to enable
// it; production fleets typically enable it only on a couple of nodes
// (the same nodes that will run `reflowd config create-join-token` for
// their region) and behind a firewall rule that allows freshly-imaged
// hosts to reach the port.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bootstrapv1/bootstrap.proto

package bootstrapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignCSRRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER-encoded x509.CertificateRequest. Subject.CommonName MUST be
	// either `<kind>/<requested_name>` for a fixed name, or `<kind>/auto`
	// for a node token whose record carries requested_name="auto". For
	// an operator token, requested_name="auto" is rejected — the
	// operator must pick the name at create-token time.
	CsrDer []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	// Plaintext token, exactly as printed by
	// `reflowd config create-join-token`. The server hashes it (sha256)
	// and looks the row up in JoinTokenTable.
	JoinToken     string `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	mi := &file_bootstrapv1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrapv1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_bootstrapv1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *SignCSRRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *SignCSRRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

type SignCSRResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded signed leaf certificate.
	CertPem []byte `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	// PEM-encoded CA chain (typically a single self-signed root).
	// Joiners use it both to validate the returned leaf and to populate
	// their RootCAs pool for outbound mTLS dials.
	CaChainPem []byte `protobuf:"bytes,2,opt,name=ca_chain_pem,json=caChainPem,proto3" json:"ca_chain_pem,omitempty"`
	// For node tokens with requested_name="auto", carries the node_id the
	// bootstrap server allocated and stamped into the CN. Joiners use it
	// as the dragonboat replica id and on the subsequent SelfJoin RPC.
	// Zero for operator tokens.
	AssignedNodeId uint64 `protobuf:"varint,3,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	// SPKI fingerprint (sha256:<hex>) of the active CA cert at signing
	// time. Joiners record this so future trust-anchor pinning checks
	// (--root-cert-pin) can match without re-querying the table.
	CaFingerprint string `protobuf:"bytes,4,opt,name=ca_fingerprint,json=caFingerprint,proto3" json:"ca_fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	mi := &file_bootstrapv1_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrapv1_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_bootstrapv1_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *SignCSRResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *SignCSRResponse) GetCaChainPem() []byte {
	if x != nil {
		return x.CaChainPem
	}
	return nil
}

func (x *SignCSRResponse) GetAssignedNodeId() uint64 {
	if x != nil {
		return x.AssignedNodeId
	}
	return 0
}

func (x *SignCSRResponse) GetCaFingerprint() string {
	if x != nil {
		return x.CaFingerprint
	}
	return ""
}

var File_bootstrapv1_bootstrap_proto protoreflect.FileDescriptor

const file_bootstrapv1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x1bbootstrapv1/bootstrap.proto\x12\x13reflow.bootstrap.v1\"H\n" +
	"\x0eSignCSRRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\x12\x1d\n" +
	"\n" +
	"join_token\x18\x02 \x01(\tR\tjoinToken\"\x9f\x01\n" +
	"\x0fSignCSRResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12 \n" +
	"\fca_chain_pem\x18\x02 \x01(\fR\n" +
	"caChainPem\x12(\n" +
	"\x10assigned_node_id\x18\x03 \x01(\x04R\x0eassignedNodeId\x12%\n" +
	"\x0eca_fingerprint\x18\x04 \x01(\tR\rcaFingerprint2`\n" +
	"\bMeshSign\x12T\n" +
	"\aSignCSR\x12#.reflow.bootstrap.v1.SignCSRRequest\x1a$.reflow.bootstrap.v1.SignCSRResponseB9Z7github.com/twinfer/reflow/proto/bootstrapv1;bootstrapv1b\x06proto3"

var (
	file_bootstrapv1_bootstrap_proto_rawDescOnce sync.Once
	file_bootstrapv1_bootstrap_proto_rawDescData []byte
)

func file_bootstrapv1_bootstrap_proto_rawDescGZIP() []byte {
	file_bootstrapv1_bootstrap_proto_rawDescOnce.Do(func() {
		file_bootstrapv1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bootstrapv1_bootstrap_proto_rawDesc), len(file_bootstrapv1_bootstrap_proto_rawDesc)))
	})
	return file_bootstrapv1_bootstrap_proto_rawDescData
}

var file_bootstrapv1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bootstrapv1_bootstrap_proto_goTypes = []any{
	(*SignCSRRequest)(nil),  // 0: reflow.bootstrap.v1.SignCSRRequest
	(*SignCSRResponse)(nil), // 1: reflow.bootstrap.v1.SignCSRResponse
}
var file_bootstrapv1_bootstrap_proto_depIdxs = []int32{
	0, // 0: reflow.bootstrap.v1.MeshSign.SignCSR:input_type -> reflow.bootstrap.v1.SignCSRRequest
	1, // 1: reflow.bootstrap.v1.MeshSign.SignCSR:output_type -> reflow.bootstrap.v1.SignCSRResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bootstrapv1_bootstrap_proto_init() }
func file_bootstrapv1_bootstrap_proto_init() {
	if File_bootstrapv1_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bootstrapv1_bootstrap_proto_rawDesc), len(file_bootstrapv1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootstrapv1_bootstrap_proto_goTypes,
		DependencyIndexes: file_bootstrapv1_bootstrap_proto_depIdxs,
		MessageInfos:      file_bootstrapv1_bootstrap_proto_msgTypes,
	}.Build()
	File_bootstrapv1_bootstrap_proto = out.File
	file_bootstrapv1_bootstrap_proto_goTypes = nil
	file_bootstrapv1_bootstrap_proto_depIdxs = nil
}
