// Reflw ClusterCtl service — the cluster-operator surface.
//
// ClusterCtl owns the *physical* cluster operations: node membership,
// partition topology, DR snapshots, and LP routing transfers. It is
// the cluster-admin counterpart to reflw.config.v1.Config (which owns
// app config — handler deployments, CA roots, join tokens, secrets).
// The naming mirrors Restate, where `cluster-ctrl` is the
// cluster-administrator surface and `admin` is the app-config surface.
//
// Every reflwd process hosts a ClusterCtl Connect RPC server on a
// dedicated port (typically :8082). The server is mTLS-protected; the
// caller's leaf CN encodes its principal Raw form (e.g.
// `operator/<name>` for operators). The `reflwd cluster ...` CLI is
// the canonical client. SelfJoin has a narrower carve-out: it accepts
// a `node/*` principal, but only when the principal's NodeID equals
// req.node_id (defense in depth behind the Cedar authz policy).
//
// Authorization is Cedar (internal/authz). The foundational policy
// restricts /reflw.clusterctl.v1.ClusterCtl/* to principals matching
// "operator/*", with the SelfJoin carve-out described above.
//
// Mutating RPCs (AddNode, RemoveNode, TransferLP, CreateSnapshot,
// DeleteSnapshot) translate to shard-0 Raft proposals; the apply arms
// in the metadata FSM and the metadata-leader rebalancer drive the
// rest. Read RPCs (ListNodes, ListPartitions, ListSnapshots,
// ListLPTransfers) issue a SyncRead against shard 0 or the local
// SnapshotRepository.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: clusterctlv1/clusterctl.proto

package clusterctlv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	clusterctlv1 "github.com/twinfer/reflw/proto/clusterctlv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClusterCtlName is the fully-qualified name of the ClusterCtl service.
	ClusterCtlName = "reflw.clusterctl.v1.ClusterCtl"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClusterCtlAddNodeProcedure is the fully-qualified name of the ClusterCtl's AddNode RPC.
	ClusterCtlAddNodeProcedure = "/reflw.clusterctl.v1.ClusterCtl/AddNode"
	// ClusterCtlSelfJoinProcedure is the fully-qualified name of the ClusterCtl's SelfJoin RPC.
	ClusterCtlSelfJoinProcedure = "/reflw.clusterctl.v1.ClusterCtl/SelfJoin"
	// ClusterCtlRemoveNodeProcedure is the fully-qualified name of the ClusterCtl's RemoveNode RPC.
	ClusterCtlRemoveNodeProcedure = "/reflw.clusterctl.v1.ClusterCtl/RemoveNode"
	// ClusterCtlListNodesProcedure is the fully-qualified name of the ClusterCtl's ListNodes RPC.
	ClusterCtlListNodesProcedure = "/reflw.clusterctl.v1.ClusterCtl/ListNodes"
	// ClusterCtlListPartitionsProcedure is the fully-qualified name of the ClusterCtl's ListPartitions
	// RPC.
	ClusterCtlListPartitionsProcedure = "/reflw.clusterctl.v1.ClusterCtl/ListPartitions"
	// ClusterCtlNodeLeadershipProcedure is the fully-qualified name of the ClusterCtl's NodeLeadership
	// RPC.
	ClusterCtlNodeLeadershipProcedure = "/reflw.clusterctl.v1.ClusterCtl/NodeLeadership"
	// ClusterCtlCreateSnapshotProcedure is the fully-qualified name of the ClusterCtl's CreateSnapshot
	// RPC.
	ClusterCtlCreateSnapshotProcedure = "/reflw.clusterctl.v1.ClusterCtl/CreateSnapshot"
	// ClusterCtlListSnapshotsProcedure is the fully-qualified name of the ClusterCtl's ListSnapshots
	// RPC.
	ClusterCtlListSnapshotsProcedure = "/reflw.clusterctl.v1.ClusterCtl/ListSnapshots"
	// ClusterCtlDeleteSnapshotProcedure is the fully-qualified name of the ClusterCtl's DeleteSnapshot
	// RPC.
	ClusterCtlDeleteSnapshotProcedure = "/reflw.clusterctl.v1.ClusterCtl/DeleteSnapshot"
	// ClusterCtlTransferLPProcedure is the fully-qualified name of the ClusterCtl's TransferLP RPC.
	ClusterCtlTransferLPProcedure = "/reflw.clusterctl.v1.ClusterCtl/TransferLP"
	// ClusterCtlListLPTransfersProcedure is the fully-qualified name of the ClusterCtl's
	// ListLPTransfers RPC.
	ClusterCtlListLPTransfersProcedure = "/reflw.clusterctl.v1.ClusterCtl/ListLPTransfers"
	// ClusterCtlRebalanceAdviseProcedure is the fully-qualified name of the ClusterCtl's
	// RebalanceAdvise RPC.
	ClusterCtlRebalanceAdviseProcedure = "/reflw.clusterctl.v1.ClusterCtl/RebalanceAdvise"
	// ClusterCtlRebalanceDrainProcedure is the fully-qualified name of the ClusterCtl's RebalanceDrain
	// RPC.
	ClusterCtlRebalanceDrainProcedure = "/reflw.clusterctl.v1.ClusterCtl/RebalanceDrain"
)

// ClusterCtlClient is a client for the reflw.clusterctl.v1.ClusterCtl service.
type ClusterCtlClient interface {
	// AddNode registers a new peer with shard 0 and enqueues a rebalance
	// sequence to give the new node a non-voting replica of every
	// existing partition shard. The non-voting replica is promoted to a
	// voter after dragonboat reports catch-up.
	AddNode(context.Context, *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error)
	// SelfJoin is AddNode initiated by the joiner itself. Authorized when
	// the caller's leaf-CN principal is "node/<req.node_id>"; any other
	// principal is rejected. Same payload and FSM effect as AddNode —
	// the two methods exist as distinct authorization paths so the
	// authz policy can gate them by role (operator/* vs node/<id>).
	// Idempotent: the underlying RegisterNode + BeginRebalanceStep apply
	// arms upsert/dedup.
	SelfJoin(context.Context, *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error)
	// RemoveNode marks a peer as evicted in shard 0. The rebalancer
	// observes and walks the dragonboat membership-change sequence
	// (DELETE_REPLICA for every shard the node hosted).
	RemoveNode(context.Context, *connect.Request[clusterctlv1.RemoveNodeRequest]) (*connect.Response[clusterctlv1.RemoveNodeResponse], error)
	// ListNodes returns the current NodeMembership records from shard 0.
	ListNodes(context.Context, *connect.Request[clusterctlv1.ListNodesRequest]) (*connect.Response[clusterctlv1.ListNodesResponse], error)
	// ListPartitions returns the current PartitionTable from shard 0.
	ListPartitions(context.Context, *connect.Request[clusterctlv1.ListPartitionsRequest]) (*connect.Response[clusterctlv1.ListPartitionsResponse], error)
	// NodeLeadership returns the partition shards this node currently
	// hosts and their live Raft leadership state, read from the node's own
	// runtime view (Host.Partitions) — distinct from ListPartitions, which
	// returns shard 0's assignment table and cannot reflect a live election.
	// Read-only; the chaos/e2e harness uses it to locate a shard's live
	// leader.
	NodeLeadership(context.Context, *connect.Request[clusterctlv1.NodeLeadershipRequest]) (*connect.Response[clusterctlv1.NodeLeadershipResponse], error)
	// CreateSnapshot kicks off an Exported snapshot of the requested
	// partition shard and archives the result via the local
	// SnapshotRepository. Returns the snapshot index.
	CreateSnapshot(context.Context, *connect.Request[clusterctlv1.CreateSnapshotRequest]) (*connect.Response[clusterctlv1.CreateSnapshotResponse], error)
	// ListSnapshots enumerates archived snapshots for a partition shard.
	ListSnapshots(context.Context, *connect.Request[clusterctlv1.ListSnapshotsRequest]) (*connect.Response[clusterctlv1.ListSnapshotsResponse], error)
	// DeleteSnapshot removes a single archived snapshot. Idempotent —
	// returns OK when the snapshot is already absent.
	DeleteSnapshot(context.Context, *connect.Request[clusterctlv1.DeleteSnapshotRequest]) (*connect.Response[clusterctlv1.DeleteSnapshotResponse], error)
	// TransferLP initiates a cross-shard transfer of one logical
	// partition. Validates inputs, mints a UUIDv4 transfer_id, and
	// proposes Command_InitiateLPTransfer to shard 0. The lpMover on the
	// metadata leader then drives the saga (freeze → ship → stage →
	// flip → cleanup). Returns immediately with the transfer_id; the
	// caller polls ListLPTransfers to observe progress. Leader-only.
	TransferLP(context.Context, *connect.Request[clusterctlv1.TransferLPRequest]) (*connect.Response[clusterctlv1.TransferLPResponse], error)
	// ListLPTransfers returns the current LPTransferTable rows plus the
	// table revision. Reads via SyncRead against shard 0.
	ListLPTransfers(context.Context, *connect.Request[clusterctlv1.ListLPTransfersRequest]) (*connect.Response[clusterctlv1.ListLPTransfersResponse], error)
	// RebalanceAdvise returns the autonomous rebalancer's view of the
	// cluster as of the call: current skew, drained shards, per-shard LP
	// counts, and (in `would_transfer`) the moves the rebalancer would
	// propose right now under hysteresis-free evaluation. Read-only —
	// any peer can answer; SyncReads route to the local shard-0 replica.
	RebalanceAdvise(context.Context, *connect.Request[clusterctlv1.RebalanceAdviseRequest]) (*connect.Response[clusterctlv1.RebalanceAdviseResponse], error)
	// RebalanceDrain adds or removes a partition shard from the
	// RebalanceDrainTable. drain=true marks the shard drained (its LPs
	// get re-planned off); drain=false un-drains. Idempotent. CAS via
	// if_table_revision_eq; mismatch returns FailedPrecondition.
	// Leader-only.
	RebalanceDrain(context.Context, *connect.Request[clusterctlv1.RebalanceDrainRequest]) (*connect.Response[clusterctlv1.RebalanceDrainResponse], error)
}

// NewClusterCtlClient constructs a client for the reflw.clusterctl.v1.ClusterCtl service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClusterCtlClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClusterCtlClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clusterCtlMethods := clusterctlv1.File_clusterctlv1_clusterctl_proto.Services().ByName("ClusterCtl").Methods()
	return &clusterCtlClient{
		addNode: connect.NewClient[clusterctlv1.AddNodeRequest, clusterctlv1.AddNodeResponse](
			httpClient,
			baseURL+ClusterCtlAddNodeProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("AddNode")),
			connect.WithClientOptions(opts...),
		),
		selfJoin: connect.NewClient[clusterctlv1.AddNodeRequest, clusterctlv1.AddNodeResponse](
			httpClient,
			baseURL+ClusterCtlSelfJoinProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("SelfJoin")),
			connect.WithClientOptions(opts...),
		),
		removeNode: connect.NewClient[clusterctlv1.RemoveNodeRequest, clusterctlv1.RemoveNodeResponse](
			httpClient,
			baseURL+ClusterCtlRemoveNodeProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("RemoveNode")),
			connect.WithClientOptions(opts...),
		),
		listNodes: connect.NewClient[clusterctlv1.ListNodesRequest, clusterctlv1.ListNodesResponse](
			httpClient,
			baseURL+ClusterCtlListNodesProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
		listPartitions: connect.NewClient[clusterctlv1.ListPartitionsRequest, clusterctlv1.ListPartitionsResponse](
			httpClient,
			baseURL+ClusterCtlListPartitionsProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("ListPartitions")),
			connect.WithClientOptions(opts...),
		),
		nodeLeadership: connect.NewClient[clusterctlv1.NodeLeadershipRequest, clusterctlv1.NodeLeadershipResponse](
			httpClient,
			baseURL+ClusterCtlNodeLeadershipProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("NodeLeadership")),
			connect.WithClientOptions(opts...),
		),
		createSnapshot: connect.NewClient[clusterctlv1.CreateSnapshotRequest, clusterctlv1.CreateSnapshotResponse](
			httpClient,
			baseURL+ClusterCtlCreateSnapshotProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("CreateSnapshot")),
			connect.WithClientOptions(opts...),
		),
		listSnapshots: connect.NewClient[clusterctlv1.ListSnapshotsRequest, clusterctlv1.ListSnapshotsResponse](
			httpClient,
			baseURL+ClusterCtlListSnapshotsProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("ListSnapshots")),
			connect.WithClientOptions(opts...),
		),
		deleteSnapshot: connect.NewClient[clusterctlv1.DeleteSnapshotRequest, clusterctlv1.DeleteSnapshotResponse](
			httpClient,
			baseURL+ClusterCtlDeleteSnapshotProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("DeleteSnapshot")),
			connect.WithClientOptions(opts...),
		),
		transferLP: connect.NewClient[clusterctlv1.TransferLPRequest, clusterctlv1.TransferLPResponse](
			httpClient,
			baseURL+ClusterCtlTransferLPProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("TransferLP")),
			connect.WithClientOptions(opts...),
		),
		listLPTransfers: connect.NewClient[clusterctlv1.ListLPTransfersRequest, clusterctlv1.ListLPTransfersResponse](
			httpClient,
			baseURL+ClusterCtlListLPTransfersProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("ListLPTransfers")),
			connect.WithClientOptions(opts...),
		),
		rebalanceAdvise: connect.NewClient[clusterctlv1.RebalanceAdviseRequest, clusterctlv1.RebalanceAdviseResponse](
			httpClient,
			baseURL+ClusterCtlRebalanceAdviseProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("RebalanceAdvise")),
			connect.WithClientOptions(opts...),
		),
		rebalanceDrain: connect.NewClient[clusterctlv1.RebalanceDrainRequest, clusterctlv1.RebalanceDrainResponse](
			httpClient,
			baseURL+ClusterCtlRebalanceDrainProcedure,
			connect.WithSchema(clusterCtlMethods.ByName("RebalanceDrain")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clusterCtlClient implements ClusterCtlClient.
type clusterCtlClient struct {
	addNode         *connect.Client[clusterctlv1.AddNodeRequest, clusterctlv1.AddNodeResponse]
	selfJoin        *connect.Client[clusterctlv1.AddNodeRequest, clusterctlv1.AddNodeResponse]
	removeNode      *connect.Client[clusterctlv1.RemoveNodeRequest, clusterctlv1.RemoveNodeResponse]
	listNodes       *connect.Client[clusterctlv1.ListNodesRequest, clusterctlv1.ListNodesResponse]
	listPartitions  *connect.Client[clusterctlv1.ListPartitionsRequest, clusterctlv1.ListPartitionsResponse]
	nodeLeadership  *connect.Client[clusterctlv1.NodeLeadershipRequest, clusterctlv1.NodeLeadershipResponse]
	createSnapshot  *connect.Client[clusterctlv1.CreateSnapshotRequest, clusterctlv1.CreateSnapshotResponse]
	listSnapshots   *connect.Client[clusterctlv1.ListSnapshotsRequest, clusterctlv1.ListSnapshotsResponse]
	deleteSnapshot  *connect.Client[clusterctlv1.DeleteSnapshotRequest, clusterctlv1.DeleteSnapshotResponse]
	transferLP      *connect.Client[clusterctlv1.TransferLPRequest, clusterctlv1.TransferLPResponse]
	listLPTransfers *connect.Client[clusterctlv1.ListLPTransfersRequest, clusterctlv1.ListLPTransfersResponse]
	rebalanceAdvise *connect.Client[clusterctlv1.RebalanceAdviseRequest, clusterctlv1.RebalanceAdviseResponse]
	rebalanceDrain  *connect.Client[clusterctlv1.RebalanceDrainRequest, clusterctlv1.RebalanceDrainResponse]
}

// AddNode calls reflw.clusterctl.v1.ClusterCtl.AddNode.
func (c *clusterCtlClient) AddNode(ctx context.Context, req *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error) {
	return c.addNode.CallUnary(ctx, req)
}

// SelfJoin calls reflw.clusterctl.v1.ClusterCtl.SelfJoin.
func (c *clusterCtlClient) SelfJoin(ctx context.Context, req *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error) {
	return c.selfJoin.CallUnary(ctx, req)
}

// RemoveNode calls reflw.clusterctl.v1.ClusterCtl.RemoveNode.
func (c *clusterCtlClient) RemoveNode(ctx context.Context, req *connect.Request[clusterctlv1.RemoveNodeRequest]) (*connect.Response[clusterctlv1.RemoveNodeResponse], error) {
	return c.removeNode.CallUnary(ctx, req)
}

// ListNodes calls reflw.clusterctl.v1.ClusterCtl.ListNodes.
func (c *clusterCtlClient) ListNodes(ctx context.Context, req *connect.Request[clusterctlv1.ListNodesRequest]) (*connect.Response[clusterctlv1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// ListPartitions calls reflw.clusterctl.v1.ClusterCtl.ListPartitions.
func (c *clusterCtlClient) ListPartitions(ctx context.Context, req *connect.Request[clusterctlv1.ListPartitionsRequest]) (*connect.Response[clusterctlv1.ListPartitionsResponse], error) {
	return c.listPartitions.CallUnary(ctx, req)
}

// NodeLeadership calls reflw.clusterctl.v1.ClusterCtl.NodeLeadership.
func (c *clusterCtlClient) NodeLeadership(ctx context.Context, req *connect.Request[clusterctlv1.NodeLeadershipRequest]) (*connect.Response[clusterctlv1.NodeLeadershipResponse], error) {
	return c.nodeLeadership.CallUnary(ctx, req)
}

// CreateSnapshot calls reflw.clusterctl.v1.ClusterCtl.CreateSnapshot.
func (c *clusterCtlClient) CreateSnapshot(ctx context.Context, req *connect.Request[clusterctlv1.CreateSnapshotRequest]) (*connect.Response[clusterctlv1.CreateSnapshotResponse], error) {
	return c.createSnapshot.CallUnary(ctx, req)
}

// ListSnapshots calls reflw.clusterctl.v1.ClusterCtl.ListSnapshots.
func (c *clusterCtlClient) ListSnapshots(ctx context.Context, req *connect.Request[clusterctlv1.ListSnapshotsRequest]) (*connect.Response[clusterctlv1.ListSnapshotsResponse], error) {
	return c.listSnapshots.CallUnary(ctx, req)
}

// DeleteSnapshot calls reflw.clusterctl.v1.ClusterCtl.DeleteSnapshot.
func (c *clusterCtlClient) DeleteSnapshot(ctx context.Context, req *connect.Request[clusterctlv1.DeleteSnapshotRequest]) (*connect.Response[clusterctlv1.DeleteSnapshotResponse], error) {
	return c.deleteSnapshot.CallUnary(ctx, req)
}

// TransferLP calls reflw.clusterctl.v1.ClusterCtl.TransferLP.
func (c *clusterCtlClient) TransferLP(ctx context.Context, req *connect.Request[clusterctlv1.TransferLPRequest]) (*connect.Response[clusterctlv1.TransferLPResponse], error) {
	return c.transferLP.CallUnary(ctx, req)
}

// ListLPTransfers calls reflw.clusterctl.v1.ClusterCtl.ListLPTransfers.
func (c *clusterCtlClient) ListLPTransfers(ctx context.Context, req *connect.Request[clusterctlv1.ListLPTransfersRequest]) (*connect.Response[clusterctlv1.ListLPTransfersResponse], error) {
	return c.listLPTransfers.CallUnary(ctx, req)
}

// RebalanceAdvise calls reflw.clusterctl.v1.ClusterCtl.RebalanceAdvise.
func (c *clusterCtlClient) RebalanceAdvise(ctx context.Context, req *connect.Request[clusterctlv1.RebalanceAdviseRequest]) (*connect.Response[clusterctlv1.RebalanceAdviseResponse], error) {
	return c.rebalanceAdvise.CallUnary(ctx, req)
}

// RebalanceDrain calls reflw.clusterctl.v1.ClusterCtl.RebalanceDrain.
func (c *clusterCtlClient) RebalanceDrain(ctx context.Context, req *connect.Request[clusterctlv1.RebalanceDrainRequest]) (*connect.Response[clusterctlv1.RebalanceDrainResponse], error) {
	return c.rebalanceDrain.CallUnary(ctx, req)
}

// ClusterCtlHandler is an implementation of the reflw.clusterctl.v1.ClusterCtl service.
type ClusterCtlHandler interface {
	// AddNode registers a new peer with shard 0 and enqueues a rebalance
	// sequence to give the new node a non-voting replica of every
	// existing partition shard. The non-voting replica is promoted to a
	// voter after dragonboat reports catch-up.
	AddNode(context.Context, *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error)
	// SelfJoin is AddNode initiated by the joiner itself. Authorized when
	// the caller's leaf-CN principal is "node/<req.node_id>"; any other
	// principal is rejected. Same payload and FSM effect as AddNode —
	// the two methods exist as distinct authorization paths so the
	// authz policy can gate them by role (operator/* vs node/<id>).
	// Idempotent: the underlying RegisterNode + BeginRebalanceStep apply
	// arms upsert/dedup.
	SelfJoin(context.Context, *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error)
	// RemoveNode marks a peer as evicted in shard 0. The rebalancer
	// observes and walks the dragonboat membership-change sequence
	// (DELETE_REPLICA for every shard the node hosted).
	RemoveNode(context.Context, *connect.Request[clusterctlv1.RemoveNodeRequest]) (*connect.Response[clusterctlv1.RemoveNodeResponse], error)
	// ListNodes returns the current NodeMembership records from shard 0.
	ListNodes(context.Context, *connect.Request[clusterctlv1.ListNodesRequest]) (*connect.Response[clusterctlv1.ListNodesResponse], error)
	// ListPartitions returns the current PartitionTable from shard 0.
	ListPartitions(context.Context, *connect.Request[clusterctlv1.ListPartitionsRequest]) (*connect.Response[clusterctlv1.ListPartitionsResponse], error)
	// NodeLeadership returns the partition shards this node currently
	// hosts and their live Raft leadership state, read from the node's own
	// runtime view (Host.Partitions) — distinct from ListPartitions, which
	// returns shard 0's assignment table and cannot reflect a live election.
	// Read-only; the chaos/e2e harness uses it to locate a shard's live
	// leader.
	NodeLeadership(context.Context, *connect.Request[clusterctlv1.NodeLeadershipRequest]) (*connect.Response[clusterctlv1.NodeLeadershipResponse], error)
	// CreateSnapshot kicks off an Exported snapshot of the requested
	// partition shard and archives the result via the local
	// SnapshotRepository. Returns the snapshot index.
	CreateSnapshot(context.Context, *connect.Request[clusterctlv1.CreateSnapshotRequest]) (*connect.Response[clusterctlv1.CreateSnapshotResponse], error)
	// ListSnapshots enumerates archived snapshots for a partition shard.
	ListSnapshots(context.Context, *connect.Request[clusterctlv1.ListSnapshotsRequest]) (*connect.Response[clusterctlv1.ListSnapshotsResponse], error)
	// DeleteSnapshot removes a single archived snapshot. Idempotent —
	// returns OK when the snapshot is already absent.
	DeleteSnapshot(context.Context, *connect.Request[clusterctlv1.DeleteSnapshotRequest]) (*connect.Response[clusterctlv1.DeleteSnapshotResponse], error)
	// TransferLP initiates a cross-shard transfer of one logical
	// partition. Validates inputs, mints a UUIDv4 transfer_id, and
	// proposes Command_InitiateLPTransfer to shard 0. The lpMover on the
	// metadata leader then drives the saga (freeze → ship → stage →
	// flip → cleanup). Returns immediately with the transfer_id; the
	// caller polls ListLPTransfers to observe progress. Leader-only.
	TransferLP(context.Context, *connect.Request[clusterctlv1.TransferLPRequest]) (*connect.Response[clusterctlv1.TransferLPResponse], error)
	// ListLPTransfers returns the current LPTransferTable rows plus the
	// table revision. Reads via SyncRead against shard 0.
	ListLPTransfers(context.Context, *connect.Request[clusterctlv1.ListLPTransfersRequest]) (*connect.Response[clusterctlv1.ListLPTransfersResponse], error)
	// RebalanceAdvise returns the autonomous rebalancer's view of the
	// cluster as of the call: current skew, drained shards, per-shard LP
	// counts, and (in `would_transfer`) the moves the rebalancer would
	// propose right now under hysteresis-free evaluation. Read-only —
	// any peer can answer; SyncReads route to the local shard-0 replica.
	RebalanceAdvise(context.Context, *connect.Request[clusterctlv1.RebalanceAdviseRequest]) (*connect.Response[clusterctlv1.RebalanceAdviseResponse], error)
	// RebalanceDrain adds or removes a partition shard from the
	// RebalanceDrainTable. drain=true marks the shard drained (its LPs
	// get re-planned off); drain=false un-drains. Idempotent. CAS via
	// if_table_revision_eq; mismatch returns FailedPrecondition.
	// Leader-only.
	RebalanceDrain(context.Context, *connect.Request[clusterctlv1.RebalanceDrainRequest]) (*connect.Response[clusterctlv1.RebalanceDrainResponse], error)
}

// NewClusterCtlHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClusterCtlHandler(svc ClusterCtlHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clusterCtlMethods := clusterctlv1.File_clusterctlv1_clusterctl_proto.Services().ByName("ClusterCtl").Methods()
	clusterCtlAddNodeHandler := connect.NewUnaryHandler(
		ClusterCtlAddNodeProcedure,
		svc.AddNode,
		connect.WithSchema(clusterCtlMethods.ByName("AddNode")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlSelfJoinHandler := connect.NewUnaryHandler(
		ClusterCtlSelfJoinProcedure,
		svc.SelfJoin,
		connect.WithSchema(clusterCtlMethods.ByName("SelfJoin")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlRemoveNodeHandler := connect.NewUnaryHandler(
		ClusterCtlRemoveNodeProcedure,
		svc.RemoveNode,
		connect.WithSchema(clusterCtlMethods.ByName("RemoveNode")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlListNodesHandler := connect.NewUnaryHandler(
		ClusterCtlListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(clusterCtlMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlListPartitionsHandler := connect.NewUnaryHandler(
		ClusterCtlListPartitionsProcedure,
		svc.ListPartitions,
		connect.WithSchema(clusterCtlMethods.ByName("ListPartitions")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlNodeLeadershipHandler := connect.NewUnaryHandler(
		ClusterCtlNodeLeadershipProcedure,
		svc.NodeLeadership,
		connect.WithSchema(clusterCtlMethods.ByName("NodeLeadership")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlCreateSnapshotHandler := connect.NewUnaryHandler(
		ClusterCtlCreateSnapshotProcedure,
		svc.CreateSnapshot,
		connect.WithSchema(clusterCtlMethods.ByName("CreateSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlListSnapshotsHandler := connect.NewUnaryHandler(
		ClusterCtlListSnapshotsProcedure,
		svc.ListSnapshots,
		connect.WithSchema(clusterCtlMethods.ByName("ListSnapshots")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlDeleteSnapshotHandler := connect.NewUnaryHandler(
		ClusterCtlDeleteSnapshotProcedure,
		svc.DeleteSnapshot,
		connect.WithSchema(clusterCtlMethods.ByName("DeleteSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlTransferLPHandler := connect.NewUnaryHandler(
		ClusterCtlTransferLPProcedure,
		svc.TransferLP,
		connect.WithSchema(clusterCtlMethods.ByName("TransferLP")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlListLPTransfersHandler := connect.NewUnaryHandler(
		ClusterCtlListLPTransfersProcedure,
		svc.ListLPTransfers,
		connect.WithSchema(clusterCtlMethods.ByName("ListLPTransfers")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlRebalanceAdviseHandler := connect.NewUnaryHandler(
		ClusterCtlRebalanceAdviseProcedure,
		svc.RebalanceAdvise,
		connect.WithSchema(clusterCtlMethods.ByName("RebalanceAdvise")),
		connect.WithHandlerOptions(opts...),
	)
	clusterCtlRebalanceDrainHandler := connect.NewUnaryHandler(
		ClusterCtlRebalanceDrainProcedure,
		svc.RebalanceDrain,
		connect.WithSchema(clusterCtlMethods.ByName("RebalanceDrain")),
		connect.WithHandlerOptions(opts...),
	)
	return "/reflw.clusterctl.v1.ClusterCtl/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClusterCtlAddNodeProcedure:
			clusterCtlAddNodeHandler.ServeHTTP(w, r)
		case ClusterCtlSelfJoinProcedure:
			clusterCtlSelfJoinHandler.ServeHTTP(w, r)
		case ClusterCtlRemoveNodeProcedure:
			clusterCtlRemoveNodeHandler.ServeHTTP(w, r)
		case ClusterCtlListNodesProcedure:
			clusterCtlListNodesHandler.ServeHTTP(w, r)
		case ClusterCtlListPartitionsProcedure:
			clusterCtlListPartitionsHandler.ServeHTTP(w, r)
		case ClusterCtlNodeLeadershipProcedure:
			clusterCtlNodeLeadershipHandler.ServeHTTP(w, r)
		case ClusterCtlCreateSnapshotProcedure:
			clusterCtlCreateSnapshotHandler.ServeHTTP(w, r)
		case ClusterCtlListSnapshotsProcedure:
			clusterCtlListSnapshotsHandler.ServeHTTP(w, r)
		case ClusterCtlDeleteSnapshotProcedure:
			clusterCtlDeleteSnapshotHandler.ServeHTTP(w, r)
		case ClusterCtlTransferLPProcedure:
			clusterCtlTransferLPHandler.ServeHTTP(w, r)
		case ClusterCtlListLPTransfersProcedure:
			clusterCtlListLPTransfersHandler.ServeHTTP(w, r)
		case ClusterCtlRebalanceAdviseProcedure:
			clusterCtlRebalanceAdviseHandler.ServeHTTP(w, r)
		case ClusterCtlRebalanceDrainProcedure:
			clusterCtlRebalanceDrainHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClusterCtlHandler returns CodeUnimplemented from all methods.
type UnimplementedClusterCtlHandler struct{}

func (UnimplementedClusterCtlHandler) AddNode(context.Context, *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.AddNode is not implemented"))
}

func (UnimplementedClusterCtlHandler) SelfJoin(context.Context, *connect.Request[clusterctlv1.AddNodeRequest]) (*connect.Response[clusterctlv1.AddNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.SelfJoin is not implemented"))
}

func (UnimplementedClusterCtlHandler) RemoveNode(context.Context, *connect.Request[clusterctlv1.RemoveNodeRequest]) (*connect.Response[clusterctlv1.RemoveNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.RemoveNode is not implemented"))
}

func (UnimplementedClusterCtlHandler) ListNodes(context.Context, *connect.Request[clusterctlv1.ListNodesRequest]) (*connect.Response[clusterctlv1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.ListNodes is not implemented"))
}

func (UnimplementedClusterCtlHandler) ListPartitions(context.Context, *connect.Request[clusterctlv1.ListPartitionsRequest]) (*connect.Response[clusterctlv1.ListPartitionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.ListPartitions is not implemented"))
}

func (UnimplementedClusterCtlHandler) NodeLeadership(context.Context, *connect.Request[clusterctlv1.NodeLeadershipRequest]) (*connect.Response[clusterctlv1.NodeLeadershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.NodeLeadership is not implemented"))
}

func (UnimplementedClusterCtlHandler) CreateSnapshot(context.Context, *connect.Request[clusterctlv1.CreateSnapshotRequest]) (*connect.Response[clusterctlv1.CreateSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.CreateSnapshot is not implemented"))
}

func (UnimplementedClusterCtlHandler) ListSnapshots(context.Context, *connect.Request[clusterctlv1.ListSnapshotsRequest]) (*connect.Response[clusterctlv1.ListSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.ListSnapshots is not implemented"))
}

func (UnimplementedClusterCtlHandler) DeleteSnapshot(context.Context, *connect.Request[clusterctlv1.DeleteSnapshotRequest]) (*connect.Response[clusterctlv1.DeleteSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.DeleteSnapshot is not implemented"))
}

func (UnimplementedClusterCtlHandler) TransferLP(context.Context, *connect.Request[clusterctlv1.TransferLPRequest]) (*connect.Response[clusterctlv1.TransferLPResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.TransferLP is not implemented"))
}

func (UnimplementedClusterCtlHandler) ListLPTransfers(context.Context, *connect.Request[clusterctlv1.ListLPTransfersRequest]) (*connect.Response[clusterctlv1.ListLPTransfersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.ListLPTransfers is not implemented"))
}

func (UnimplementedClusterCtlHandler) RebalanceAdvise(context.Context, *connect.Request[clusterctlv1.RebalanceAdviseRequest]) (*connect.Response[clusterctlv1.RebalanceAdviseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.RebalanceAdvise is not implemented"))
}

func (UnimplementedClusterCtlHandler) RebalanceDrain(context.Context, *connect.Request[clusterctlv1.RebalanceDrainRequest]) (*connect.Response[clusterctlv1.RebalanceDrainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.clusterctl.v1.ClusterCtl.RebalanceDrain is not implemented"))
}
