// Reflow ClusterCtl service — the cluster-operator surface.
//
// ClusterCtl owns the *physical* cluster operations: node membership,
// partition topology, DR snapshots, and LP routing transfers. It is
// the cluster-admin counterpart to reflow.config.v1.Config (which owns
// app config — handler deployments, event sources, webhooks, secrets).
// The naming mirrors Restate, where `cluster-ctrl` is the
// cluster-administrator surface and `admin` is the app-config surface.
//
// Every reflowd process hosts a ClusterCtl Connect RPC server on a
// dedicated port (typically :8082). The server is mTLS-protected; the
// caller's leaf CN encodes its principal Raw form (e.g.
// `operator/<name>` for operators). The `reflowd cluster ...` CLI is
// the canonical client. SelfJoin has a narrower carve-out: it accepts
// a `node/*` principal, but only when the principal's NodeID equals
// req.node_id (defense in depth behind the path-based authz rule).
//
// Authorization lives in internal/auth (the shared starter authz policy
// consumed by both the gRPC delivery interceptor and the Connect HTTP
// middleware). The starter policy restricts
// /reflow.clusterctl.v1.ClusterCtl/* to principals matching
// "operator/*", with the SelfJoin carve-out described above.
//
// Mutating RPCs (AddNode, RemoveNode, TransferLP, CreateSnapshot,
// DeleteSnapshot) translate to shard-0 Raft proposals; the apply arms
// in the metadata FSM and the metadata-leader rebalancer drive the
// rest. Read RPCs (ListNodes, ListPartitions, ListSnapshots,
// ListLPTransfers) issue a SyncRead against shard 0 or the local
// SnapshotRepository.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clusterctlv1/clusterctl.proto

package clusterctlv1

import (
	enginev1 "github.com/twinfer/reflow/proto/enginev1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	GossipAddr    string                 `protobuf:"bytes,3,opt,name=gossip_addr,json=gossipAddr,proto3" json:"gossip_addr,omitempty"`
	GrpcEndpoint  string                 `protobuf:"bytes,4,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	NodeHostId    string                 `protobuf:"bytes,5,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{0}
}

func (x *AddNodeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AddNodeRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *AddNodeRequest) GetGossipAddr() string {
	if x != nil {
		return x.GossipAddr
	}
	return ""
}

func (x *AddNodeRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *AddNodeRequest) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

type AddNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assignment_epoch after the new node was registered. The caller can
	// poll ListPartitions until shards converge.
	AssignmentEpoch uint64 `protobuf:"varint,1,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{1}
}

func (x *AddNodeResponse) GetAssignmentEpoch() uint64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveNodeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type RemoveNodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssignmentEpoch uint64                 `protobuf:"varint,1,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveNodeResponse) GetAssignmentEpoch() uint64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Nodes         []*enginev1.NodeMembership `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*enginev1.NodeMembership {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{6}
}

type ListPartitionsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Table         *enginev1.PartitionTable `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{7}
}

func (x *ListPartitionsResponse) GetTable() *enginev1.PartitionTable {
	if x != nil {
		return x.Table
	}
	return nil
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSnapshotRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSnapshotResponse) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *CreateSnapshotResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CreateSnapshotResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{10}
}

func (x *ListSnapshotsRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type SnapshotRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShardId         uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Index           uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,4,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRef) Reset() {
	*x = SnapshotRef{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRef) ProtoMessage() {}

func (x *SnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRef.ProtoReflect.Descriptor instead.
func (*SnapshotRef) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotRef) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SnapshotRef) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotRef) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotRef         `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{12}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotRef {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSnapshotRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *DeleteSnapshotRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{14}
}

// TransferLPRequest initiates a cross-shard transfer for one LP. lp
// must be in [0, LPCount); dest_shard must be a known partition shard
// id. The request fails (FailedPrecondition) if a non-terminal
// transfer for the same lp already exists.
type TransferLPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lp            uint32                 `protobuf:"varint,1,opt,name=lp,proto3" json:"lp,omitempty"`
	DestShard     uint64                 `protobuf:"varint,2,opt,name=dest_shard,json=destShard,proto3" json:"dest_shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLPRequest) Reset() {
	*x = TransferLPRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLPRequest) ProtoMessage() {}

func (x *TransferLPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLPRequest.ProtoReflect.Descriptor instead.
func (*TransferLPRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{15}
}

func (x *TransferLPRequest) GetLp() uint32 {
	if x != nil {
		return x.Lp
	}
	return 0
}

func (x *TransferLPRequest) GetDestShard() uint64 {
	if x != nil {
		return x.DestShard
	}
	return 0
}

type TransferLPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLPResponse) Reset() {
	*x = TransferLPResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLPResponse) ProtoMessage() {}

func (x *TransferLPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLPResponse.ProtoReflect.Descriptor instead.
func (*TransferLPResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{16}
}

func (x *TransferLPResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type ListLPTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLPTransfersRequest) Reset() {
	*x = ListLPTransfersRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLPTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLPTransfersRequest) ProtoMessage() {}

func (x *ListLPTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLPTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListLPTransfersRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{17}
}

type ListLPTransfersResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Records       []*enginev1.LPTransferRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	TableRevision uint64                       `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLPTransfersResponse) Reset() {
	*x = ListLPTransfersResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLPTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLPTransfersResponse) ProtoMessage() {}

func (x *ListLPTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLPTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListLPTransfersResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{18}
}

func (x *ListLPTransfersResponse) GetRecords() []*enginev1.LPTransferRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListLPTransfersResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// RebalanceMove describes one prospective LP→shard transfer in
// RebalanceAdviseResponse. Same shape as routing.LPMove on the engine
// side.
type RebalanceMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lp            uint32                 `protobuf:"varint,1,opt,name=lp,proto3" json:"lp,omitempty"`
	FromShard     uint64                 `protobuf:"varint,2,opt,name=from_shard,json=fromShard,proto3" json:"from_shard,omitempty"`
	ToShard       uint64                 `protobuf:"varint,3,opt,name=to_shard,json=toShard,proto3" json:"to_shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceMove) Reset() {
	*x = RebalanceMove{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceMove) ProtoMessage() {}

func (x *RebalanceMove) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceMove.ProtoReflect.Descriptor instead.
func (*RebalanceMove) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{19}
}

func (x *RebalanceMove) GetLp() uint32 {
	if x != nil {
		return x.Lp
	}
	return 0
}

func (x *RebalanceMove) GetFromShard() uint64 {
	if x != nil {
		return x.FromShard
	}
	return 0
}

func (x *RebalanceMove) GetToShard() uint64 {
	if x != nil {
		return x.ToShard
	}
	return 0
}

// RebalanceAdviseRequest carries no parameters; the rebalancer's
// configuration is server-side.
type RebalanceAdviseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceAdviseRequest) Reset() {
	*x = RebalanceAdviseRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceAdviseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceAdviseRequest) ProtoMessage() {}

func (x *RebalanceAdviseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceAdviseRequest.ProtoReflect.Descriptor instead.
func (*RebalanceAdviseRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{20}
}

type RebalanceAdviseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mode is the running mode: "off", "advisory", or "auto".
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// engaged reports whether the rebalancer would consider the cluster
	// "engaged" right now — i.e., whether skew_pct ≥ engage_pct. The
	// server-side advice path evaluates without hysteresis carry-over;
	// operators get the fresh-view answer.
	Engaged bool `protobuf:"varint,2,opt,name=engaged,proto3" json:"engaged,omitempty"`
	// skew_pct is the mis-placement percentage on a 0..100 scale.
	SkewPct float64 `protobuf:"fixed64,3,opt,name=skew_pct,json=skewPct,proto3" json:"skew_pct,omitempty"`
	// in_flight is the count of non-terminal LP transfers right now.
	InFlight uint32 `protobuf:"varint,4,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	// skipped_reason is non-empty when would_transfer is empty;
	// explains which gate fired (skew_below_engage, cooldown,
	// at_capacity, no_moves, no_live_shards, no_planner).
	SkippedReason string `protobuf:"bytes,5,opt,name=skipped_reason,json=skippedReason,proto3" json:"skipped_reason,omitempty"`
	// drained_shards lists the shard ids currently in the
	// RebalanceDrainTable.
	DrainedShards []uint64 `protobuf:"varint,6,rep,packed,name=drained_shards,json=drainedShards,proto3" json:"drained_shards,omitempty"`
	// lps_per_shard maps shard_id → owned-LP count from the
	// LPOwnersTable snapshot the advisor observed.
	LpsPerShard map[uint64]uint32 `protobuf:"bytes,7,rep,name=lps_per_shard,json=lpsPerShard,proto3" json:"lps_per_shard,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// would_transfer is the move set the rebalancer would actuate on
	// this tick (up to max_concurrent − in_flight elements). In auto
	// mode the balancer has likely already proposed these; in advisory
	// mode the list is the planner's intent.
	WouldTransfer []*RebalanceMove `protobuf:"bytes,8,rep,name=would_transfer,json=wouldTransfer,proto3" json:"would_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceAdviseResponse) Reset() {
	*x = RebalanceAdviseResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceAdviseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceAdviseResponse) ProtoMessage() {}

func (x *RebalanceAdviseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceAdviseResponse.ProtoReflect.Descriptor instead.
func (*RebalanceAdviseResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{21}
}

func (x *RebalanceAdviseResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RebalanceAdviseResponse) GetEngaged() bool {
	if x != nil {
		return x.Engaged
	}
	return false
}

func (x *RebalanceAdviseResponse) GetSkewPct() float64 {
	if x != nil {
		return x.SkewPct
	}
	return 0
}

func (x *RebalanceAdviseResponse) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *RebalanceAdviseResponse) GetSkippedReason() string {
	if x != nil {
		return x.SkippedReason
	}
	return ""
}

func (x *RebalanceAdviseResponse) GetDrainedShards() []uint64 {
	if x != nil {
		return x.DrainedShards
	}
	return nil
}

func (x *RebalanceAdviseResponse) GetLpsPerShard() map[uint64]uint32 {
	if x != nil {
		return x.LpsPerShard
	}
	return nil
}

func (x *RebalanceAdviseResponse) GetWouldTransfer() []*RebalanceMove {
	if x != nil {
		return x.WouldTransfer
	}
	return nil
}

// RebalanceDrainRequest sets or clears a drain marker for one
// partition shard.
type RebalanceDrainRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Drain   bool                   `protobuf:"varint,2,opt,name=drain,proto3" json:"drain,omitempty"`
	// if_table_revision_eq, when non-zero, gates the apply on the
	// current RebalanceDrainTable revision matching this value (CAS).
	IfTableRevisionEq uint64 `protobuf:"varint,3,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RebalanceDrainRequest) Reset() {
	*x = RebalanceDrainRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceDrainRequest) ProtoMessage() {}

func (x *RebalanceDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceDrainRequest.ProtoReflect.Descriptor instead.
func (*RebalanceDrainRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{22}
}

func (x *RebalanceDrainRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *RebalanceDrainRequest) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

func (x *RebalanceDrainRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type RebalanceDrainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table_revision is the post-apply RebalanceDrainTable revision so
	// callers can chain CAS roundtrips.
	TableRevision uint64 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceDrainResponse) Reset() {
	*x = RebalanceDrainResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceDrainResponse) ProtoMessage() {}

func (x *RebalanceDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceDrainResponse.ProtoReflect.Descriptor instead.
func (*RebalanceDrainResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{23}
}

func (x *RebalanceDrainResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// UpsertTenantRequest carries one TenantRecord plus an optional CAS
// guard. record.id may be 0 (the server allocates an id from
// max(existing.id)+1 before propose) or non-zero (update). name must
// be non-empty.
type UpsertTenantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Record            *enginev1.TenantRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertTenantRequest) Reset() {
	*x = UpsertTenantRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantRequest) ProtoMessage() {}

func (x *UpsertTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantRequest.ProtoReflect.Descriptor instead.
func (*UpsertTenantRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{24}
}

func (x *UpsertTenantRequest) GetRecord() *enginev1.TenantRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpsertTenantRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

// UpsertTenantResponse echoes the assigned tenant_id (always populated,
// even on update) and the post-apply table revision.
type UpsertTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TableRevision uint64                 `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTenantResponse) Reset() {
	*x = UpsertTenantResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantResponse) ProtoMessage() {}

func (x *UpsertTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantResponse.ProtoReflect.Descriptor instead.
func (*UpsertTenantResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{25}
}

func (x *UpsertTenantResponse) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpsertTenantResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DeleteTenantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteTenantRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DeleteTenantRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteTenantResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{28}
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tenants       []*enginev1.TenantRecord `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	TableRevision uint64                   `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{29}
}

func (x *ListTenantsResponse) GetTenants() []*enginev1.TenantRecord {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DescribeTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTenantRequest) Reset() {
	*x = DescribeTenantRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTenantRequest) ProtoMessage() {}

func (x *DescribeTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTenantRequest.ProtoReflect.Descriptor instead.
func (*DescribeTenantRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{30}
}

func (x *DescribeTenantRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type DescribeTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *enginev1.TenantRecord `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTenantResponse) Reset() {
	*x = DescribeTenantResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTenantResponse) ProtoMessage() {}

func (x *DescribeTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTenantResponse.ProtoReflect.Descriptor instead.
func (*DescribeTenantResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{31}
}

func (x *DescribeTenantResponse) GetTenant() *enginev1.TenantRecord {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// UpsertTenantDEKRequest carries one TenantDEKRecord plus an optional
// CAS guard. record.tenant_id must be non-zero (the FSM rejects 0).
// record.name is the AAD used for KEK→DEK unwrap; rotation writes a
// new record with a new name and a new ciphertext blob.
type UpsertTenantDEKRequest struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Record            *enginev1.TenantDEKRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	IfTableRevisionEq uint64                    `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertTenantDEKRequest) Reset() {
	*x = UpsertTenantDEKRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantDEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantDEKRequest) ProtoMessage() {}

func (x *UpsertTenantDEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantDEKRequest.ProtoReflect.Descriptor instead.
func (*UpsertTenantDEKRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{32}
}

func (x *UpsertTenantDEKRequest) GetRecord() *enginev1.TenantDEKRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpsertTenantDEKRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type UpsertTenantDEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTenantDEKResponse) Reset() {
	*x = UpsertTenantDEKResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantDEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantDEKResponse) ProtoMessage() {}

func (x *UpsertTenantDEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantDEKResponse.ProtoReflect.Descriptor instead.
func (*UpsertTenantDEKResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{33}
}

func (x *UpsertTenantDEKResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type DeleteTenantDEKRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IfTableRevisionEq uint64                 `protobuf:"varint,2,opt,name=if_table_revision_eq,json=ifTableRevisionEq,proto3" json:"if_table_revision_eq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteTenantDEKRequest) Reset() {
	*x = DeleteTenantDEKRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantDEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantDEKRequest) ProtoMessage() {}

func (x *DeleteTenantDEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantDEKRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantDEKRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteTenantDEKRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DeleteTenantDEKRequest) GetIfTableRevisionEq() uint64 {
	if x != nil {
		return x.IfTableRevisionEq
	}
	return 0
}

type DeleteTenantDEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableRevision uint64                 `protobuf:"varint,1,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantDEKResponse) Reset() {
	*x = DeleteTenantDEKResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantDEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantDEKResponse) ProtoMessage() {}

func (x *DeleteTenantDEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantDEKResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantDEKResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteTenantDEKResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

type ListTenantDEKsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantDEKsRequest) Reset() {
	*x = ListTenantDEKsRequest{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantDEKsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantDEKsRequest) ProtoMessage() {}

func (x *ListTenantDEKsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantDEKsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantDEKsRequest) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{36}
}

type ListTenantDEKsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	TenantDeks    []*enginev1.TenantDEKRecord `protobuf:"bytes,1,rep,name=tenant_deks,json=tenantDeks,proto3" json:"tenant_deks,omitempty"`
	TableRevision uint64                      `protobuf:"varint,2,opt,name=table_revision,json=tableRevision,proto3" json:"table_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantDEKsResponse) Reset() {
	*x = ListTenantDEKsResponse{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantDEKsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantDEKsResponse) ProtoMessage() {}

func (x *ListTenantDEKsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantDEKsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantDEKsResponse) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{37}
}

func (x *ListTenantDEKsResponse) GetTenantDeks() []*enginev1.TenantDEKRecord {
	if x != nil {
		return x.TenantDeks
	}
	return nil
}

func (x *ListTenantDEKsResponse) GetTableRevision() uint64 {
	if x != nil {
		return x.TableRevision
	}
	return 0
}

// LeaderHint is attached as a connect.Error detail on
// connect.CodeUnavailable returned by mutating ClusterCtl RPCs when
// the receiving node is not the metadata leader. Clients (joiner's
// SelfJoin caller and the `reflowd cluster ...` CLI) extract it, dial
// admin_endpoint, retry.
type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AdminEndpoint string                 `protobuf:"bytes,2,opt,name=admin_endpoint,json=adminEndpoint,proto3" json:"admin_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_clusterctlv1_clusterctl_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_clusterctlv1_clusterctl_proto_rawDescGZIP(), []int{38}
}

func (x *LeaderHint) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LeaderHint) GetAdminEndpoint() string {
	if x != nil {
		return x.AdminEndpoint
	}
	return ""
}

var File_clusterctlv1_clusterctl_proto protoreflect.FileDescriptor

const file_clusterctlv1_clusterctl_proto_rawDesc = "" +
	"\n" +
	"\x1dclusterctlv1/clusterctl.proto\x12\x14reflow.clusterctl.v1\x1a\x15enginev1/engine.proto\"\xae\x01\n" +
	"\x0eAddNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1f\n" +
	"\vgossip_addr\x18\x03 \x01(\tR\n" +
	"gossipAddr\x12#\n" +
	"\rgrpc_endpoint\x18\x04 \x01(\tR\fgrpcEndpoint\x12 \n" +
	"\fnode_host_id\x18\x05 \x01(\tR\n" +
	"nodeHostId\"<\n" +
	"\x0fAddNodeResponse\x12)\n" +
	"\x10assignment_epoch\x18\x01 \x01(\x04R\x0fassignmentEpoch\",\n" +
	"\x11RemoveNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\"?\n" +
	"\x12RemoveNodeResponse\x12)\n" +
	"\x10assignment_epoch\x18\x01 \x01(\x04R\x0fassignmentEpoch\"\x12\n" +
	"\x10ListNodesRequest\"K\n" +
	"\x11ListNodesResponse\x126\n" +
	"\x05nodes\x18\x01 \x03(\v2 .reflow.engine.v1.NodeMembershipR\x05nodes\"\x17\n" +
	"\x15ListPartitionsRequest\"P\n" +
	"\x16ListPartitionsResponse\x126\n" +
	"\x05table\x18\x01 \x01(\v2 .reflow.engine.v1.PartitionTableR\x05table\"2\n" +
	"\x15CreateSnapshotRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\"h\n" +
	"\x16CreateSnapshotResponse\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"1\n" +
	"\x14ListSnapshotsRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\"\x8a\x01\n" +
	"\vSnapshotRef\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12+\n" +
	"\x12created_at_unix_ms\x18\x04 \x01(\x03R\x0fcreatedAtUnixMs\"X\n" +
	"\x15ListSnapshotsResponse\x12?\n" +
	"\tsnapshots\x18\x01 \x03(\v2!.reflow.clusterctl.v1.SnapshotRefR\tsnapshots\"H\n" +
	"\x15DeleteSnapshotRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"\x18\n" +
	"\x16DeleteSnapshotResponse\"B\n" +
	"\x11TransferLPRequest\x12\x0e\n" +
	"\x02lp\x18\x01 \x01(\rR\x02lp\x12\x1d\n" +
	"\n" +
	"dest_shard\x18\x02 \x01(\x04R\tdestShard\"5\n" +
	"\x12TransferLPResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\x18\n" +
	"\x16ListLPTransfersRequest\"~\n" +
	"\x17ListLPTransfersResponse\x12<\n" +
	"\arecords\x18\x01 \x03(\v2\".reflow.engine.v1.LPTransferRecordR\arecords\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"Y\n" +
	"\rRebalanceMove\x12\x0e\n" +
	"\x02lp\x18\x01 \x01(\rR\x02lp\x12\x1d\n" +
	"\n" +
	"from_shard\x18\x02 \x01(\x04R\tfromShard\x12\x19\n" +
	"\bto_shard\x18\x03 \x01(\x04R\atoShard\"\x18\n" +
	"\x16RebalanceAdviseRequest\"\xbd\x03\n" +
	"\x17RebalanceAdviseResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x18\n" +
	"\aengaged\x18\x02 \x01(\bR\aengaged\x12\x19\n" +
	"\bskew_pct\x18\x03 \x01(\x01R\askewPct\x12\x1b\n" +
	"\tin_flight\x18\x04 \x01(\rR\binFlight\x12%\n" +
	"\x0eskipped_reason\x18\x05 \x01(\tR\rskippedReason\x12%\n" +
	"\x0edrained_shards\x18\x06 \x03(\x04R\rdrainedShards\x12b\n" +
	"\rlps_per_shard\x18\a \x03(\v2>.reflow.clusterctl.v1.RebalanceAdviseResponse.LpsPerShardEntryR\vlpsPerShard\x12J\n" +
	"\x0ewould_transfer\x18\b \x03(\v2#.reflow.clusterctl.v1.RebalanceMoveR\rwouldTransfer\x1a>\n" +
	"\x10LpsPerShardEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"y\n" +
	"\x15RebalanceDrainRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05drain\x18\x02 \x01(\bR\x05drain\x12/\n" +
	"\x14if_table_revision_eq\x18\x03 \x01(\x04R\x11ifTableRevisionEq\"?\n" +
	"\x16RebalanceDrainResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"~\n" +
	"\x13UpsertTenantRequest\x126\n" +
	"\x06record\x18\x01 \x01(\v2\x1e.reflow.engine.v1.TenantRecordR\x06record\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"Z\n" +
	"\x14UpsertTenantResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"c\n" +
	"\x13DeleteTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"=\n" +
	"\x14DeleteTenantResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"\x14\n" +
	"\x12ListTenantsRequest\"v\n" +
	"\x13ListTenantsResponse\x128\n" +
	"\atenants\x18\x01 \x03(\v2\x1e.reflow.engine.v1.TenantRecordR\atenants\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"4\n" +
	"\x15DescribeTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\"P\n" +
	"\x16DescribeTenantResponse\x126\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1e.reflow.engine.v1.TenantRecordR\x06tenant\"\x84\x01\n" +
	"\x16UpsertTenantDEKRequest\x129\n" +
	"\x06record\x18\x01 \x01(\v2!.reflow.engine.v1.TenantDEKRecordR\x06record\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"@\n" +
	"\x17UpsertTenantDEKResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"f\n" +
	"\x16DeleteTenantDEKRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\x12/\n" +
	"\x14if_table_revision_eq\x18\x02 \x01(\x04R\x11ifTableRevisionEq\"@\n" +
	"\x17DeleteTenantDEKResponse\x12%\n" +
	"\x0etable_revision\x18\x01 \x01(\x04R\rtableRevision\"\x17\n" +
	"\x15ListTenantDEKsRequest\"\x83\x01\n" +
	"\x16ListTenantDEKsResponse\x12B\n" +
	"\vtenant_deks\x18\x01 \x03(\v2!.reflow.engine.v1.TenantDEKRecordR\n" +
	"tenantDeks\x12%\n" +
	"\x0etable_revision\x18\x02 \x01(\x04R\rtableRevision\"L\n" +
	"\n" +
	"LeaderHint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12%\n" +
	"\x0eadmin_endpoint\x18\x02 \x01(\tR\radminEndpoint2\xc7\x0f\n" +
	"\n" +
	"ClusterCtl\x12V\n" +
	"\aAddNode\x12$.reflow.clusterctl.v1.AddNodeRequest\x1a%.reflow.clusterctl.v1.AddNodeResponse\x12W\n" +
	"\bSelfJoin\x12$.reflow.clusterctl.v1.AddNodeRequest\x1a%.reflow.clusterctl.v1.AddNodeResponse\x12_\n" +
	"\n" +
	"RemoveNode\x12'.reflow.clusterctl.v1.RemoveNodeRequest\x1a(.reflow.clusterctl.v1.RemoveNodeResponse\x12\\\n" +
	"\tListNodes\x12&.reflow.clusterctl.v1.ListNodesRequest\x1a'.reflow.clusterctl.v1.ListNodesResponse\x12k\n" +
	"\x0eListPartitions\x12+.reflow.clusterctl.v1.ListPartitionsRequest\x1a,.reflow.clusterctl.v1.ListPartitionsResponse\x12k\n" +
	"\x0eCreateSnapshot\x12+.reflow.clusterctl.v1.CreateSnapshotRequest\x1a,.reflow.clusterctl.v1.CreateSnapshotResponse\x12h\n" +
	"\rListSnapshots\x12*.reflow.clusterctl.v1.ListSnapshotsRequest\x1a+.reflow.clusterctl.v1.ListSnapshotsResponse\x12k\n" +
	"\x0eDeleteSnapshot\x12+.reflow.clusterctl.v1.DeleteSnapshotRequest\x1a,.reflow.clusterctl.v1.DeleteSnapshotResponse\x12_\n" +
	"\n" +
	"TransferLP\x12'.reflow.clusterctl.v1.TransferLPRequest\x1a(.reflow.clusterctl.v1.TransferLPResponse\x12n\n" +
	"\x0fListLPTransfers\x12,.reflow.clusterctl.v1.ListLPTransfersRequest\x1a-.reflow.clusterctl.v1.ListLPTransfersResponse\x12n\n" +
	"\x0fRebalanceAdvise\x12,.reflow.clusterctl.v1.RebalanceAdviseRequest\x1a-.reflow.clusterctl.v1.RebalanceAdviseResponse\x12k\n" +
	"\x0eRebalanceDrain\x12+.reflow.clusterctl.v1.RebalanceDrainRequest\x1a,.reflow.clusterctl.v1.RebalanceDrainResponse\x12e\n" +
	"\fUpsertTenant\x12).reflow.clusterctl.v1.UpsertTenantRequest\x1a*.reflow.clusterctl.v1.UpsertTenantResponse\x12e\n" +
	"\fDeleteTenant\x12).reflow.clusterctl.v1.DeleteTenantRequest\x1a*.reflow.clusterctl.v1.DeleteTenantResponse\x12b\n" +
	"\vListTenants\x12(.reflow.clusterctl.v1.ListTenantsRequest\x1a).reflow.clusterctl.v1.ListTenantsResponse\x12k\n" +
	"\x0eDescribeTenant\x12+.reflow.clusterctl.v1.DescribeTenantRequest\x1a,.reflow.clusterctl.v1.DescribeTenantResponse\x12n\n" +
	"\x0fUpsertTenantDEK\x12,.reflow.clusterctl.v1.UpsertTenantDEKRequest\x1a-.reflow.clusterctl.v1.UpsertTenantDEKResponse\x12n\n" +
	"\x0fDeleteTenantDEK\x12,.reflow.clusterctl.v1.DeleteTenantDEKRequest\x1a-.reflow.clusterctl.v1.DeleteTenantDEKResponse\x12k\n" +
	"\x0eListTenantDEKs\x12+.reflow.clusterctl.v1.ListTenantDEKsRequest\x1a,.reflow.clusterctl.v1.ListTenantDEKsResponseB;Z9github.com/twinfer/reflow/proto/clusterctlv1;clusterctlv1b\x06proto3"

var (
	file_clusterctlv1_clusterctl_proto_rawDescOnce sync.Once
	file_clusterctlv1_clusterctl_proto_rawDescData []byte
)

func file_clusterctlv1_clusterctl_proto_rawDescGZIP() []byte {
	file_clusterctlv1_clusterctl_proto_rawDescOnce.Do(func() {
		file_clusterctlv1_clusterctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusterctlv1_clusterctl_proto_rawDesc), len(file_clusterctlv1_clusterctl_proto_rawDesc)))
	})
	return file_clusterctlv1_clusterctl_proto_rawDescData
}

var file_clusterctlv1_clusterctl_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_clusterctlv1_clusterctl_proto_goTypes = []any{
	(*AddNodeRequest)(nil),            // 0: reflow.clusterctl.v1.AddNodeRequest
	(*AddNodeResponse)(nil),           // 1: reflow.clusterctl.v1.AddNodeResponse
	(*RemoveNodeRequest)(nil),         // 2: reflow.clusterctl.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),        // 3: reflow.clusterctl.v1.RemoveNodeResponse
	(*ListNodesRequest)(nil),          // 4: reflow.clusterctl.v1.ListNodesRequest
	(*ListNodesResponse)(nil),         // 5: reflow.clusterctl.v1.ListNodesResponse
	(*ListPartitionsRequest)(nil),     // 6: reflow.clusterctl.v1.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),    // 7: reflow.clusterctl.v1.ListPartitionsResponse
	(*CreateSnapshotRequest)(nil),     // 8: reflow.clusterctl.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),    // 9: reflow.clusterctl.v1.CreateSnapshotResponse
	(*ListSnapshotsRequest)(nil),      // 10: reflow.clusterctl.v1.ListSnapshotsRequest
	(*SnapshotRef)(nil),               // 11: reflow.clusterctl.v1.SnapshotRef
	(*ListSnapshotsResponse)(nil),     // 12: reflow.clusterctl.v1.ListSnapshotsResponse
	(*DeleteSnapshotRequest)(nil),     // 13: reflow.clusterctl.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),    // 14: reflow.clusterctl.v1.DeleteSnapshotResponse
	(*TransferLPRequest)(nil),         // 15: reflow.clusterctl.v1.TransferLPRequest
	(*TransferLPResponse)(nil),        // 16: reflow.clusterctl.v1.TransferLPResponse
	(*ListLPTransfersRequest)(nil),    // 17: reflow.clusterctl.v1.ListLPTransfersRequest
	(*ListLPTransfersResponse)(nil),   // 18: reflow.clusterctl.v1.ListLPTransfersResponse
	(*RebalanceMove)(nil),             // 19: reflow.clusterctl.v1.RebalanceMove
	(*RebalanceAdviseRequest)(nil),    // 20: reflow.clusterctl.v1.RebalanceAdviseRequest
	(*RebalanceAdviseResponse)(nil),   // 21: reflow.clusterctl.v1.RebalanceAdviseResponse
	(*RebalanceDrainRequest)(nil),     // 22: reflow.clusterctl.v1.RebalanceDrainRequest
	(*RebalanceDrainResponse)(nil),    // 23: reflow.clusterctl.v1.RebalanceDrainResponse
	(*UpsertTenantRequest)(nil),       // 24: reflow.clusterctl.v1.UpsertTenantRequest
	(*UpsertTenantResponse)(nil),      // 25: reflow.clusterctl.v1.UpsertTenantResponse
	(*DeleteTenantRequest)(nil),       // 26: reflow.clusterctl.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),      // 27: reflow.clusterctl.v1.DeleteTenantResponse
	(*ListTenantsRequest)(nil),        // 28: reflow.clusterctl.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),       // 29: reflow.clusterctl.v1.ListTenantsResponse
	(*DescribeTenantRequest)(nil),     // 30: reflow.clusterctl.v1.DescribeTenantRequest
	(*DescribeTenantResponse)(nil),    // 31: reflow.clusterctl.v1.DescribeTenantResponse
	(*UpsertTenantDEKRequest)(nil),    // 32: reflow.clusterctl.v1.UpsertTenantDEKRequest
	(*UpsertTenantDEKResponse)(nil),   // 33: reflow.clusterctl.v1.UpsertTenantDEKResponse
	(*DeleteTenantDEKRequest)(nil),    // 34: reflow.clusterctl.v1.DeleteTenantDEKRequest
	(*DeleteTenantDEKResponse)(nil),   // 35: reflow.clusterctl.v1.DeleteTenantDEKResponse
	(*ListTenantDEKsRequest)(nil),     // 36: reflow.clusterctl.v1.ListTenantDEKsRequest
	(*ListTenantDEKsResponse)(nil),    // 37: reflow.clusterctl.v1.ListTenantDEKsResponse
	(*LeaderHint)(nil),                // 38: reflow.clusterctl.v1.LeaderHint
	nil,                               // 39: reflow.clusterctl.v1.RebalanceAdviseResponse.LpsPerShardEntry
	(*enginev1.NodeMembership)(nil),   // 40: reflow.engine.v1.NodeMembership
	(*enginev1.PartitionTable)(nil),   // 41: reflow.engine.v1.PartitionTable
	(*enginev1.LPTransferRecord)(nil), // 42: reflow.engine.v1.LPTransferRecord
	(*enginev1.TenantRecord)(nil),     // 43: reflow.engine.v1.TenantRecord
	(*enginev1.TenantDEKRecord)(nil),  // 44: reflow.engine.v1.TenantDEKRecord
}
var file_clusterctlv1_clusterctl_proto_depIdxs = []int32{
	40, // 0: reflow.clusterctl.v1.ListNodesResponse.nodes:type_name -> reflow.engine.v1.NodeMembership
	41, // 1: reflow.clusterctl.v1.ListPartitionsResponse.table:type_name -> reflow.engine.v1.PartitionTable
	11, // 2: reflow.clusterctl.v1.ListSnapshotsResponse.snapshots:type_name -> reflow.clusterctl.v1.SnapshotRef
	42, // 3: reflow.clusterctl.v1.ListLPTransfersResponse.records:type_name -> reflow.engine.v1.LPTransferRecord
	39, // 4: reflow.clusterctl.v1.RebalanceAdviseResponse.lps_per_shard:type_name -> reflow.clusterctl.v1.RebalanceAdviseResponse.LpsPerShardEntry
	19, // 5: reflow.clusterctl.v1.RebalanceAdviseResponse.would_transfer:type_name -> reflow.clusterctl.v1.RebalanceMove
	43, // 6: reflow.clusterctl.v1.UpsertTenantRequest.record:type_name -> reflow.engine.v1.TenantRecord
	43, // 7: reflow.clusterctl.v1.ListTenantsResponse.tenants:type_name -> reflow.engine.v1.TenantRecord
	43, // 8: reflow.clusterctl.v1.DescribeTenantResponse.tenant:type_name -> reflow.engine.v1.TenantRecord
	44, // 9: reflow.clusterctl.v1.UpsertTenantDEKRequest.record:type_name -> reflow.engine.v1.TenantDEKRecord
	44, // 10: reflow.clusterctl.v1.ListTenantDEKsResponse.tenant_deks:type_name -> reflow.engine.v1.TenantDEKRecord
	0,  // 11: reflow.clusterctl.v1.ClusterCtl.AddNode:input_type -> reflow.clusterctl.v1.AddNodeRequest
	0,  // 12: reflow.clusterctl.v1.ClusterCtl.SelfJoin:input_type -> reflow.clusterctl.v1.AddNodeRequest
	2,  // 13: reflow.clusterctl.v1.ClusterCtl.RemoveNode:input_type -> reflow.clusterctl.v1.RemoveNodeRequest
	4,  // 14: reflow.clusterctl.v1.ClusterCtl.ListNodes:input_type -> reflow.clusterctl.v1.ListNodesRequest
	6,  // 15: reflow.clusterctl.v1.ClusterCtl.ListPartitions:input_type -> reflow.clusterctl.v1.ListPartitionsRequest
	8,  // 16: reflow.clusterctl.v1.ClusterCtl.CreateSnapshot:input_type -> reflow.clusterctl.v1.CreateSnapshotRequest
	10, // 17: reflow.clusterctl.v1.ClusterCtl.ListSnapshots:input_type -> reflow.clusterctl.v1.ListSnapshotsRequest
	13, // 18: reflow.clusterctl.v1.ClusterCtl.DeleteSnapshot:input_type -> reflow.clusterctl.v1.DeleteSnapshotRequest
	15, // 19: reflow.clusterctl.v1.ClusterCtl.TransferLP:input_type -> reflow.clusterctl.v1.TransferLPRequest
	17, // 20: reflow.clusterctl.v1.ClusterCtl.ListLPTransfers:input_type -> reflow.clusterctl.v1.ListLPTransfersRequest
	20, // 21: reflow.clusterctl.v1.ClusterCtl.RebalanceAdvise:input_type -> reflow.clusterctl.v1.RebalanceAdviseRequest
	22, // 22: reflow.clusterctl.v1.ClusterCtl.RebalanceDrain:input_type -> reflow.clusterctl.v1.RebalanceDrainRequest
	24, // 23: reflow.clusterctl.v1.ClusterCtl.UpsertTenant:input_type -> reflow.clusterctl.v1.UpsertTenantRequest
	26, // 24: reflow.clusterctl.v1.ClusterCtl.DeleteTenant:input_type -> reflow.clusterctl.v1.DeleteTenantRequest
	28, // 25: reflow.clusterctl.v1.ClusterCtl.ListTenants:input_type -> reflow.clusterctl.v1.ListTenantsRequest
	30, // 26: reflow.clusterctl.v1.ClusterCtl.DescribeTenant:input_type -> reflow.clusterctl.v1.DescribeTenantRequest
	32, // 27: reflow.clusterctl.v1.ClusterCtl.UpsertTenantDEK:input_type -> reflow.clusterctl.v1.UpsertTenantDEKRequest
	34, // 28: reflow.clusterctl.v1.ClusterCtl.DeleteTenantDEK:input_type -> reflow.clusterctl.v1.DeleteTenantDEKRequest
	36, // 29: reflow.clusterctl.v1.ClusterCtl.ListTenantDEKs:input_type -> reflow.clusterctl.v1.ListTenantDEKsRequest
	1,  // 30: reflow.clusterctl.v1.ClusterCtl.AddNode:output_type -> reflow.clusterctl.v1.AddNodeResponse
	1,  // 31: reflow.clusterctl.v1.ClusterCtl.SelfJoin:output_type -> reflow.clusterctl.v1.AddNodeResponse
	3,  // 32: reflow.clusterctl.v1.ClusterCtl.RemoveNode:output_type -> reflow.clusterctl.v1.RemoveNodeResponse
	5,  // 33: reflow.clusterctl.v1.ClusterCtl.ListNodes:output_type -> reflow.clusterctl.v1.ListNodesResponse
	7,  // 34: reflow.clusterctl.v1.ClusterCtl.ListPartitions:output_type -> reflow.clusterctl.v1.ListPartitionsResponse
	9,  // 35: reflow.clusterctl.v1.ClusterCtl.CreateSnapshot:output_type -> reflow.clusterctl.v1.CreateSnapshotResponse
	12, // 36: reflow.clusterctl.v1.ClusterCtl.ListSnapshots:output_type -> reflow.clusterctl.v1.ListSnapshotsResponse
	14, // 37: reflow.clusterctl.v1.ClusterCtl.DeleteSnapshot:output_type -> reflow.clusterctl.v1.DeleteSnapshotResponse
	16, // 38: reflow.clusterctl.v1.ClusterCtl.TransferLP:output_type -> reflow.clusterctl.v1.TransferLPResponse
	18, // 39: reflow.clusterctl.v1.ClusterCtl.ListLPTransfers:output_type -> reflow.clusterctl.v1.ListLPTransfersResponse
	21, // 40: reflow.clusterctl.v1.ClusterCtl.RebalanceAdvise:output_type -> reflow.clusterctl.v1.RebalanceAdviseResponse
	23, // 41: reflow.clusterctl.v1.ClusterCtl.RebalanceDrain:output_type -> reflow.clusterctl.v1.RebalanceDrainResponse
	25, // 42: reflow.clusterctl.v1.ClusterCtl.UpsertTenant:output_type -> reflow.clusterctl.v1.UpsertTenantResponse
	27, // 43: reflow.clusterctl.v1.ClusterCtl.DeleteTenant:output_type -> reflow.clusterctl.v1.DeleteTenantResponse
	29, // 44: reflow.clusterctl.v1.ClusterCtl.ListTenants:output_type -> reflow.clusterctl.v1.ListTenantsResponse
	31, // 45: reflow.clusterctl.v1.ClusterCtl.DescribeTenant:output_type -> reflow.clusterctl.v1.DescribeTenantResponse
	33, // 46: reflow.clusterctl.v1.ClusterCtl.UpsertTenantDEK:output_type -> reflow.clusterctl.v1.UpsertTenantDEKResponse
	35, // 47: reflow.clusterctl.v1.ClusterCtl.DeleteTenantDEK:output_type -> reflow.clusterctl.v1.DeleteTenantDEKResponse
	37, // 48: reflow.clusterctl.v1.ClusterCtl.ListTenantDEKs:output_type -> reflow.clusterctl.v1.ListTenantDEKsResponse
	30, // [30:49] is the sub-list for method output_type
	11, // [11:30] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_clusterctlv1_clusterctl_proto_init() }
func file_clusterctlv1_clusterctl_proto_init() {
	if File_clusterctlv1_clusterctl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusterctlv1_clusterctl_proto_rawDesc), len(file_clusterctlv1_clusterctl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusterctlv1_clusterctl_proto_goTypes,
		DependencyIndexes: file_clusterctlv1_clusterctl_proto_depIdxs,
		MessageInfos:      file_clusterctlv1_clusterctl_proto_msgTypes,
	}.Build()
	File_clusterctlv1_clusterctl_proto = out.File
	file_clusterctlv1_clusterctl_proto_goTypes = nil
	file_clusterctlv1_clusterctl_proto_depIdxs = nil
}
