// Reflow ingress service.
//
// Exposes the user-facing entrypoints for submitting invocations, awaiting
// their results, and resolving awakeables. Dual-served over gRPC and
// HTTP/JSON via grpc-gateway annotations. See SAD §10 for routing rules; in
// Phase 2 the deployment is single-partition (shard 1).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ingressv1/ingress.proto

package ingressv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ingress_SubmitInvocation_FullMethodName   = "/reflow.ingress.v1.Ingress/SubmitInvocation"
	Ingress_AwaitInvocation_FullMethodName    = "/reflow.ingress.v1.Ingress/AwaitInvocation"
	Ingress_ResolveAwakeable_FullMethodName   = "/reflow.ingress.v1.Ingress/ResolveAwakeable"
	Ingress_ListPartitions_FullMethodName     = "/reflow.ingress.v1.Ingress/ListPartitions"
	Ingress_DescribeInvocation_FullMethodName = "/reflow.ingress.v1.Ingress/DescribeInvocation"
)

// IngressClient is the client API for Ingress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngressClient interface {
	// SubmitInvocation enqueues a new invocation. Returns the minted invocation
	// ID; the caller polls AwaitInvocation (or relies on response routing once
	// Phase 5 SSE lands) for the result.
	SubmitInvocation(ctx context.Context, in *SubmitInvocationRequest, opts ...grpc.CallOption) (*SubmitInvocationResponse, error)
	// AwaitInvocation blocks (up to deadline) until the named invocation
	// reaches Completed and returns its output. Currently implemented via
	// server-side polling of SyncRead; SSE/streaming is Phase 5.
	AwaitInvocation(ctx context.Context, in *AwaitInvocationRequest, opts ...grpc.CallOption) (*AwaitInvocationResponse, error)
	// ResolveAwakeable completes an outstanding awakeable previously created
	// by a handler via ctx.Awakeable(). Routes to the owning partition by
	// looking up the awakeable directory.
	ResolveAwakeable(ctx context.Context, in *ResolveAwakeableRequest, opts ...grpc.CallOption) (*ResolveAwakeableResponse, error)
	// ListPartitions reports the partitions hosted on this node and their
	// leadership state. Read-only debug endpoint.
	ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error)
	// DescribeInvocation returns the current status of an invocation without
	// blocking. Read-only debug endpoint.
	DescribeInvocation(ctx context.Context, in *DescribeInvocationRequest, opts ...grpc.CallOption) (*DescribeInvocationResponse, error)
}

type ingressClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressClient(cc grpc.ClientConnInterface) IngressClient {
	return &ingressClient{cc}
}

func (c *ingressClient) SubmitInvocation(ctx context.Context, in *SubmitInvocationRequest, opts ...grpc.CallOption) (*SubmitInvocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInvocationResponse)
	err := c.cc.Invoke(ctx, Ingress_SubmitInvocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) AwaitInvocation(ctx context.Context, in *AwaitInvocationRequest, opts ...grpc.CallOption) (*AwaitInvocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwaitInvocationResponse)
	err := c.cc.Invoke(ctx, Ingress_AwaitInvocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) ResolveAwakeable(ctx context.Context, in *ResolveAwakeableRequest, opts ...grpc.CallOption) (*ResolveAwakeableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAwakeableResponse)
	err := c.cc.Invoke(ctx, Ingress_ResolveAwakeable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartitionsResponse)
	err := c.cc.Invoke(ctx, Ingress_ListPartitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) DescribeInvocation(ctx context.Context, in *DescribeInvocationRequest, opts ...grpc.CallOption) (*DescribeInvocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeInvocationResponse)
	err := c.cc.Invoke(ctx, Ingress_DescribeInvocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngressServer is the server API for Ingress service.
// All implementations must embed UnimplementedIngressServer
// for forward compatibility.
type IngressServer interface {
	// SubmitInvocation enqueues a new invocation. Returns the minted invocation
	// ID; the caller polls AwaitInvocation (or relies on response routing once
	// Phase 5 SSE lands) for the result.
	SubmitInvocation(context.Context, *SubmitInvocationRequest) (*SubmitInvocationResponse, error)
	// AwaitInvocation blocks (up to deadline) until the named invocation
	// reaches Completed and returns its output. Currently implemented via
	// server-side polling of SyncRead; SSE/streaming is Phase 5.
	AwaitInvocation(context.Context, *AwaitInvocationRequest) (*AwaitInvocationResponse, error)
	// ResolveAwakeable completes an outstanding awakeable previously created
	// by a handler via ctx.Awakeable(). Routes to the owning partition by
	// looking up the awakeable directory.
	ResolveAwakeable(context.Context, *ResolveAwakeableRequest) (*ResolveAwakeableResponse, error)
	// ListPartitions reports the partitions hosted on this node and their
	// leadership state. Read-only debug endpoint.
	ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error)
	// DescribeInvocation returns the current status of an invocation without
	// blocking. Read-only debug endpoint.
	DescribeInvocation(context.Context, *DescribeInvocationRequest) (*DescribeInvocationResponse, error)
	mustEmbedUnimplementedIngressServer()
}

// UnimplementedIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngressServer struct{}

func (UnimplementedIngressServer) SubmitInvocation(context.Context, *SubmitInvocationRequest) (*SubmitInvocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInvocation not implemented")
}
func (UnimplementedIngressServer) AwaitInvocation(context.Context, *AwaitInvocationRequest) (*AwaitInvocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AwaitInvocation not implemented")
}
func (UnimplementedIngressServer) ResolveAwakeable(context.Context, *ResolveAwakeableRequest) (*ResolveAwakeableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAwakeable not implemented")
}
func (UnimplementedIngressServer) ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPartitions not implemented")
}
func (UnimplementedIngressServer) DescribeInvocation(context.Context, *DescribeInvocationRequest) (*DescribeInvocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeInvocation not implemented")
}
func (UnimplementedIngressServer) mustEmbedUnimplementedIngressServer() {}
func (UnimplementedIngressServer) testEmbeddedByValue()                 {}

// UnsafeIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressServer will
// result in compilation errors.
type UnsafeIngressServer interface {
	mustEmbedUnimplementedIngressServer()
}

func RegisterIngressServer(s grpc.ServiceRegistrar, srv IngressServer) {
	// If the following call panics, it indicates UnimplementedIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ingress_ServiceDesc, srv)
}

func _Ingress_SubmitInvocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).SubmitInvocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_SubmitInvocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).SubmitInvocation(ctx, req.(*SubmitInvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_AwaitInvocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwaitInvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).AwaitInvocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_AwaitInvocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).AwaitInvocation(ctx, req.(*AwaitInvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_ResolveAwakeable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAwakeableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).ResolveAwakeable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_ResolveAwakeable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).ResolveAwakeable(ctx, req.(*ResolveAwakeableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_ListPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).ListPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_ListPartitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).ListPartitions(ctx, req.(*ListPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_DescribeInvocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeInvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).DescribeInvocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_DescribeInvocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).DescribeInvocation(ctx, req.(*DescribeInvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ingress_ServiceDesc is the grpc.ServiceDesc for Ingress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reflow.ingress.v1.Ingress",
	HandlerType: (*IngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitInvocation",
			Handler:    _Ingress_SubmitInvocation_Handler,
		},
		{
			MethodName: "AwaitInvocation",
			Handler:    _Ingress_AwaitInvocation_Handler,
		},
		{
			MethodName: "ResolveAwakeable",
			Handler:    _Ingress_ResolveAwakeable_Handler,
		},
		{
			MethodName: "ListPartitions",
			Handler:    _Ingress_ListPartitions_Handler,
		},
		{
			MethodName: "DescribeInvocation",
			Handler:    _Ingress_DescribeInvocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingressv1/ingress.proto",
}
