// Reflow handler discovery v1 — engine-to-handler capability probe.
//
// At RegisterDeployment time the engine calls DiscoveryService.Discover
// and persists the response into the DeploymentRecord on shard 0 so
// future invocations can route by id.
//
// This file is intentionally separated from the session wire protocol
// (proto/protocolv1) because discovery is a one-shot request/response
// shape with its own evolution axis (deployment metadata, capability
// advertisement). Kind is imported from protocolv1 — handler addressing
// vocabulary is owned by the session protocol.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: discoveryv1/discovery.proto

package discoveryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	discoveryv1 "github.com/twinfer/reflw/proto/discoveryv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DiscoveryServiceName is the fully-qualified name of the DiscoveryService service.
	DiscoveryServiceName = "reflw.discovery.v1.DiscoveryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DiscoveryServiceDiscoverProcedure is the fully-qualified name of the DiscoveryService's Discover
	// RPC.
	DiscoveryServiceDiscoverProcedure = "/reflw.discovery.v1.DiscoveryService/Discover"
)

// DiscoveryServiceClient is a client for the reflw.discovery.v1.DiscoveryService service.
type DiscoveryServiceClient interface {
	// Discover returns the (service, kind, handler_names) tuples this
	// deployment exposes. The engine calls this once at
	// RegisterDeployment time.
	Discover(context.Context, *connect.Request[discoveryv1.DiscoveryRequest]) (*connect.Response[discoveryv1.DiscoveryResponse], error)
}

// NewDiscoveryServiceClient constructs a client for the reflw.discovery.v1.DiscoveryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDiscoveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DiscoveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	discoveryServiceMethods := discoveryv1.File_discoveryv1_discovery_proto.Services().ByName("DiscoveryService").Methods()
	return &discoveryServiceClient{
		discover: connect.NewClient[discoveryv1.DiscoveryRequest, discoveryv1.DiscoveryResponse](
			httpClient,
			baseURL+DiscoveryServiceDiscoverProcedure,
			connect.WithSchema(discoveryServiceMethods.ByName("Discover")),
			connect.WithClientOptions(opts...),
		),
	}
}

// discoveryServiceClient implements DiscoveryServiceClient.
type discoveryServiceClient struct {
	discover *connect.Client[discoveryv1.DiscoveryRequest, discoveryv1.DiscoveryResponse]
}

// Discover calls reflw.discovery.v1.DiscoveryService.Discover.
func (c *discoveryServiceClient) Discover(ctx context.Context, req *connect.Request[discoveryv1.DiscoveryRequest]) (*connect.Response[discoveryv1.DiscoveryResponse], error) {
	return c.discover.CallUnary(ctx, req)
}

// DiscoveryServiceHandler is an implementation of the reflw.discovery.v1.DiscoveryService service.
type DiscoveryServiceHandler interface {
	// Discover returns the (service, kind, handler_names) tuples this
	// deployment exposes. The engine calls this once at
	// RegisterDeployment time.
	Discover(context.Context, *connect.Request[discoveryv1.DiscoveryRequest]) (*connect.Response[discoveryv1.DiscoveryResponse], error)
}

// NewDiscoveryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDiscoveryServiceHandler(svc DiscoveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	discoveryServiceMethods := discoveryv1.File_discoveryv1_discovery_proto.Services().ByName("DiscoveryService").Methods()
	discoveryServiceDiscoverHandler := connect.NewUnaryHandler(
		DiscoveryServiceDiscoverProcedure,
		svc.Discover,
		connect.WithSchema(discoveryServiceMethods.ByName("Discover")),
		connect.WithHandlerOptions(opts...),
	)
	return "/reflw.discovery.v1.DiscoveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DiscoveryServiceDiscoverProcedure:
			discoveryServiceDiscoverHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDiscoveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDiscoveryServiceHandler struct{}

func (UnimplementedDiscoveryServiceHandler) Discover(context.Context, *connect.Request[discoveryv1.DiscoveryRequest]) (*connect.Response[discoveryv1.DiscoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.discovery.v1.DiscoveryService.Discover is not implemented"))
}
