// Reflow-wide custom proto options.
//
// required_spiffe_role tags a single RPC with the SPIFFE role its
// caller must hold (e.g. "operator", "operator/admin", "node"). The
// match semantics are server-side (see internal/engine/admin/authz.go).
//
// default_required_spiffe_role does the same at the service level.
// Methods that omit the method-level annotation inherit this value.
//
// Both fields are opaque strings — reflow's role taxonomy lives in the
// SPIFFE identity layer (pkg/reflow/tls.go), not the IDL.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: optionsv1/options.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_optionsv1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "reflow.options.v1.required_spiffe_role",
		Tag:           "bytes,50001,opt,name=required_spiffe_role",
		Filename:      "optionsv1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "reflow.options.v1.default_required_spiffe_role",
		Tag:           "bytes,50002,opt,name=default_required_spiffe_role",
		Filename:      "optionsv1/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string required_spiffe_role = 50001;
	E_RequiredSpiffeRole = &file_optionsv1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string default_required_spiffe_role = 50002;
	E_DefaultRequiredSpiffeRole = &file_optionsv1_options_proto_extTypes[1]
)

var File_optionsv1_options_proto protoreflect.FileDescriptor

const file_optionsv1_options_proto_rawDesc = "" +
	"\n" +
	"\x17optionsv1/options.proto\x12\x11reflow.options.v1\x1a google/protobuf/descriptor.proto:R\n" +
	"\x14required_spiffe_role\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x12requiredSpiffeRole:b\n" +
	"\x1cdefault_required_spiffe_role\x12\x1f.google.protobuf.ServiceOptions\x18҆\x03 \x01(\tR\x19defaultRequiredSpiffeRoleB5Z3github.com/twinfer/reflow/proto/optionsv1;optionsv1b\x06proto3"

var file_optionsv1_options_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil),  // 0: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
}
var file_optionsv1_options_proto_depIdxs = []int32{
	0, // 0: reflow.options.v1.required_spiffe_role:extendee -> google.protobuf.MethodOptions
	1, // 1: reflow.options.v1.default_required_spiffe_role:extendee -> google.protobuf.ServiceOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_optionsv1_options_proto_init() }
func file_optionsv1_options_proto_init() {
	if File_optionsv1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optionsv1_options_proto_rawDesc), len(file_optionsv1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_optionsv1_options_proto_goTypes,
		DependencyIndexes: file_optionsv1_options_proto_depIdxs,
		ExtensionInfos:    file_optionsv1_options_proto_extTypes,
	}.Build()
	File_optionsv1_options_proto = out.File
	file_optionsv1_options_proto_goTypes = nil
	file_optionsv1_options_proto_depIdxs = nil
}
