// Reflw ingress service.
//
// Exposes the user-facing entrypoints for submitting invocations, awaiting
// their results, resolving awakeables, and the process plane. Served over
// Connect (HTTP/2) with content-negotiated Connect / gRPC / gRPC-Web /
// HTTP-JSON; clients pick a wire encoding by setting Content-Type.
//
// Responses speak the reflw.api.v1 view vocabulary (apiv1), never enginev1 —
// the Raft/on-disk format stays out of the public SDK and the browser bundle.
// Each RPC also carries a google.api.http annotation: one definition yields
// the Connect RPC, a REST/JSON route (transcoded by connectrpc.com/vanguard),
// and an OpenAPI operation. REST paths are rooted at a literal first segment
// (/v1/invocations, /v1/state, /v1/awakeables, /v1/promises, /v1/processes,
// /v1/messages, /v1/tasks) so the transcoder has zero ambiguous routes.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ingressv1/ingress.proto

package ingressv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	ingressv1 "github.com/twinfer/reflw/proto/ingressv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngressName is the fully-qualified name of the Ingress service.
	IngressName = "reflw.ingress.v1.Ingress"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngressSubmitInvocationProcedure is the fully-qualified name of the Ingress's SubmitInvocation
	// RPC.
	IngressSubmitInvocationProcedure = "/reflw.ingress.v1.Ingress/SubmitInvocation"
	// IngressAwaitInvocationProcedure is the fully-qualified name of the Ingress's AwaitInvocation RPC.
	IngressAwaitInvocationProcedure = "/reflw.ingress.v1.Ingress/AwaitInvocation"
	// IngressResolveAwakeableProcedure is the fully-qualified name of the Ingress's ResolveAwakeable
	// RPC.
	IngressResolveAwakeableProcedure = "/reflw.ingress.v1.Ingress/ResolveAwakeable"
	// IngressDescribeInvocationProcedure is the fully-qualified name of the Ingress's
	// DescribeInvocation RPC.
	IngressDescribeInvocationProcedure = "/reflw.ingress.v1.Ingress/DescribeInvocation"
	// IngressAttachInvocationProcedure is the fully-qualified name of the Ingress's AttachInvocation
	// RPC.
	IngressAttachInvocationProcedure = "/reflw.ingress.v1.Ingress/AttachInvocation"
	// IngressGetInvocationOutputProcedure is the fully-qualified name of the Ingress's
	// GetInvocationOutput RPC.
	IngressGetInvocationOutputProcedure = "/reflw.ingress.v1.Ingress/GetInvocationOutput"
	// IngressGetObjectStateProcedure is the fully-qualified name of the Ingress's GetObjectState RPC.
	IngressGetObjectStateProcedure = "/reflw.ingress.v1.Ingress/GetObjectState"
	// IngressCancelInvocationProcedure is the fully-qualified name of the Ingress's CancelInvocation
	// RPC.
	IngressCancelInvocationProcedure = "/reflw.ingress.v1.Ingress/CancelInvocation"
	// IngressResolveWorkflowPromiseProcedure is the fully-qualified name of the Ingress's
	// ResolveWorkflowPromise RPC.
	IngressResolveWorkflowPromiseProcedure = "/reflw.ingress.v1.Ingress/ResolveWorkflowPromise"
	// IngressPurgeInvocationProcedure is the fully-qualified name of the Ingress's PurgeInvocation RPC.
	IngressPurgeInvocationProcedure = "/reflw.ingress.v1.Ingress/PurgeInvocation"
	// IngressListInvocationsProcedure is the fully-qualified name of the Ingress's ListInvocations RPC.
	IngressListInvocationsProcedure = "/reflw.ingress.v1.Ingress/ListInvocations"
	// IngressStartProcessProcedure is the fully-qualified name of the Ingress's StartProcess RPC.
	IngressStartProcessProcedure = "/reflw.ingress.v1.Ingress/StartProcess"
	// IngressDeliverMessageProcedure is the fully-qualified name of the Ingress's DeliverMessage RPC.
	IngressDeliverMessageProcedure = "/reflw.ingress.v1.Ingress/DeliverMessage"
	// IngressDeliverProcessEventProcedure is the fully-qualified name of the Ingress's
	// DeliverProcessEvent RPC.
	IngressDeliverProcessEventProcedure = "/reflw.ingress.v1.Ingress/DeliverProcessEvent"
	// IngressGetProcessInstanceProcedure is the fully-qualified name of the Ingress's
	// GetProcessInstance RPC.
	IngressGetProcessInstanceProcedure = "/reflw.ingress.v1.Ingress/GetProcessInstance"
	// IngressListProcessInstancesProcedure is the fully-qualified name of the Ingress's
	// ListProcessInstances RPC.
	IngressListProcessInstancesProcedure = "/reflw.ingress.v1.Ingress/ListProcessInstances"
	// IngressGetProcessInstanceHistoryProcedure is the fully-qualified name of the Ingress's
	// GetProcessInstanceHistory RPC.
	IngressGetProcessInstanceHistoryProcedure = "/reflw.ingress.v1.Ingress/GetProcessInstanceHistory"
	// IngressResolveProcessIncidentProcedure is the fully-qualified name of the Ingress's
	// ResolveProcessIncident RPC.
	IngressResolveProcessIncidentProcedure = "/reflw.ingress.v1.Ingress/ResolveProcessIncident"
	// IngressGetTaskProcedure is the fully-qualified name of the Ingress's GetTask RPC.
	IngressGetTaskProcedure = "/reflw.ingress.v1.Ingress/GetTask"
	// IngressCompleteTaskProcedure is the fully-qualified name of the Ingress's CompleteTask RPC.
	IngressCompleteTaskProcedure = "/reflw.ingress.v1.Ingress/CompleteTask"
)

// IngressClient is a client for the reflw.ingress.v1.Ingress service.
type IngressClient interface {
	// SubmitInvocation mints an invocation for (service, handler[, object_key])
	// and, in AWAIT mode (the default), blocks for its result; in SEND mode it
	// returns the minted id immediately. service/handler/object_key ride the
	// body (not the path) so the transcoder has no wildcard route. Caller
	// metadata flows via the metadata map and/or Reflw-Meta-* request headers.
	SubmitInvocation(context.Context, *connect.Request[ingressv1.SubmitInvocationRequest]) (*connect.Response[ingressv1.SubmitInvocationResponse], error)
	// AwaitInvocation blocks (up to deadline) until the named invocation
	// reaches Completed and returns its output. Server-side polling of
	// SyncRead today; SSE/streaming is a future evolution.
	AwaitInvocation(context.Context, *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error)
	// ResolveAwakeable completes an outstanding awakeable previously
	// created by a handler via ctx.Awakeable(). Routes to the owning
	// partition by looking up the awakeable directory.
	ResolveAwakeable(context.Context, *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error)
	// DescribeInvocation returns the current status of an invocation
	// without blocking. Read-only debug endpoint.
	DescribeInvocation(context.Context, *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error)
	// AttachInvocation blocks (up to deadline) on an existing invocation
	// and returns its outcome once Completed. Same shape as
	// AwaitInvocation but explicit about attaching to an already-
	// submitted invocation by id.
	AttachInvocation(context.Context, *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error)
	// GetInvocationOutput is a non-blocking lookup of an invocation's
	// current outcome. Returns PENDING for still-running invocations,
	// COMPLETED_OK / COMPLETED_FAILED for terminated ones, UNKNOWN if no
	// such invocation is known to this node.
	GetInvocationOutput(context.Context, *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error)
	// GetObjectState reads a single state value for a virtual object.
	// Routes to the partition owning (service, object_key) through the
	// cluster Partitioner. present=false (not an error) when the key is absent.
	GetObjectState(context.Context, *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error)
	// CancelInvocation forces a running invocation to terminate with
	// FailureCode=9002 (cancelled). Implemented as a __cancel__ signal
	// delivered to the invocation's (service, key); the receiver shard
	// resolves the active InvocationId via KeyLeaseTable and synthesizes
	// a terminal Completed. Idempotent: cancelling an already-completed
	// invocation is a no-op.
	CancelInvocation(context.Context, *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error)
	// ResolveWorkflowPromise resolves or rejects a named workflow-scoped
	// durable promise. Routes by (service, workflow_key) via
	// Partitioner.ShardForTarget; the receiver shard writes PromiseValue
	// and wakes any in-flight Promise(name).Result() awaiter. Idempotent
	// against already-completed promises: succeeded=false signals
	// "promise already completed" without an error status.
	ResolveWorkflowPromise(context.Context, *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error)
	// PurgeInvocation deletes a Completed invocation's durable rows (inv
	// status, journal, signal inbox/awaiter) immediately, instead of
	// waiting for the retention reaper. Routes by the partition_key encoded
	// in the invocation id. Idempotent and no-op-safe: purging an absent or
	// not-yet-Completed invocation is accepted but changes nothing (the
	// apply arm requires a Completed/Free → Free transition). Does not touch
	// virtual-object state or workflow promise rows. Operator-only.
	PurgeInvocation(context.Context, *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error)
	// ListInvocations lists invocations across the namespace, fanning out across
	// all partition shards (same substrate as ListProcessInstances). Optional
	// service-name and state filters; capped by limit. Read-only — no proposal.
	ListInvocations(context.Context, *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error)
	// StartProcess launches a new reflwos BPMN/CMMN instance. kind ("bpmn" |
	// "cmmn") selects the plane; routing is by (name, instance_key). Proposes a
	// start ProcessEvent (model_ref + kind set). Idempotent per (model,
	// instance_key): a start for an already-existing instance is dropped by the
	// apply path. When instance_key is empty the server mints a random one (then
	// not idempotent).
	StartProcess(context.Context, *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error)
	// DeliverMessage correlates an inbound message/signal to parked process
	// instances. Routes to the partition owning (message_name,
	// correlation_key) and proposes DeliverProcessMessage, which fans the message
	// out to every instance subscribed on that (message_name, correlation_key).
	// An empty correlation_key addresses every instance waiting on the name (BPMN
	// signal broadcast). Messages with no current subscriber are dropped.
	DeliverMessage(context.Context, *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error)
	// DeliverProcessEvent injects an external typed engine event into a RUNNING
	// instance addressed by (name, instance_key) — the path a human or operator
	// uses to fire a CMMN user-event listener or push a variable update onto a
	// parked conditional. Point-to-point: it proposes a continuation ProcessEvent
	// (no model_ref → the apply path appends to the named instance's inbox and
	// advances one turn). An absent or terminal instance is a benign drop. To
	// complete a parked user/human task by its resume token, use CompleteTask.
	DeliverProcessEvent(context.Context, *connect.Request[ingressv1.DeliverProcessEventRequest]) (*connect.Response[ingressv1.DeliverProcessEventResponse], error)
	// GetProcessInstance is a linearizable read of one instance's current state,
	// routed by (name, instance_key) like StartProcess. present=false means the
	// instance never started OR already reached a terminal and was reaped.
	// Read-only — no proposal.
	GetProcessInstance(context.Context, *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error)
	// ListProcessInstances lists process instances across the namespace, fanning
	// out across all partition shards. Optional model-name and status filters;
	// capped by limit.
	ListProcessInstances(context.Context, *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error)
	// GetProcessInstanceHistory reads one instance's append-only activity timeline
	// (start, inbound events, task dispatch/complete, timer arm/fire, child
	// start/complete, subscribe/unsubscribe, message received, terminal), routed by
	// (name, instance_key) like GetProcessInstance. Read-only — no proposal. The
	// timeline survives a terminal only within the instance's retention window;
	// present=false means the instance never started or was reaped. Page forward
	// with after_seq.
	GetProcessInstanceHistory(context.Context, *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error)
	// ResolveProcessIncident resolves an incident-parked instance (one whose
	// status is PROCESS_STATUS_INCIDENT — an uncaught failure parked for human
	// intervention). RETRY re-drives the failed element as a new turn (optionally
	// patching variables first); TERMINATE fails the instance terminally. Routed by
	// (name, instance_key) like StartProcess. Idempotent: resolving a non-incident
	// instance is accepted but changes nothing (accepted=false).
	ResolveProcessIncident(context.Context, *connect.Request[ingressv1.ResolveProcessIncidentRequest]) (*connect.Response[ingressv1.ResolveProcessIncidentResponse], error)
	// GetTask resolves an opaque resume token (from a GetProcessInstance
	// awaiting_tasks entry) to the parked user/human task it addresses — the
	// discovery (read) half of the resume-token surface. Returned only when the
	// token is live (instance present, RUNNING, node_id still awaiting); a
	// stale/consumed/forged token is FailedPrecondition. The schema field, when
	// set, is the task's submission JSON Schema (model-derived, best-effort).
	GetTask(context.Context, *connect.Request[ingressv1.GetTaskRequest]) (*connect.Response[ingressv1.GetTaskResponse], error)
	// CompleteTask completes (or fails) a parked BPMN user task / CMMN human task
	// by its opaque resume token — the consume half of the resume-token flow. The
	// token carries (name, instance_key, node_id), so the caller names no element
	// id; it supplies only the output vars (or, when fail=true, a failure message).
	// A linearizable read gates it (the task must still be awaiting) else
	// FailedPrecondition.
	CompleteTask(context.Context, *connect.Request[ingressv1.CompleteTaskRequest]) (*connect.Response[ingressv1.CompleteTaskResponse], error)
}

// NewIngressClient constructs a client for the reflw.ingress.v1.Ingress service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngressClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngressClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ingressMethods := ingressv1.File_ingressv1_ingress_proto.Services().ByName("Ingress").Methods()
	return &ingressClient{
		submitInvocation: connect.NewClient[ingressv1.SubmitInvocationRequest, ingressv1.SubmitInvocationResponse](
			httpClient,
			baseURL+IngressSubmitInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("SubmitInvocation")),
			connect.WithClientOptions(opts...),
		),
		awaitInvocation: connect.NewClient[ingressv1.AwaitInvocationRequest, ingressv1.AwaitInvocationResponse](
			httpClient,
			baseURL+IngressAwaitInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("AwaitInvocation")),
			connect.WithClientOptions(opts...),
		),
		resolveAwakeable: connect.NewClient[ingressv1.ResolveAwakeableRequest, ingressv1.ResolveAwakeableResponse](
			httpClient,
			baseURL+IngressResolveAwakeableProcedure,
			connect.WithSchema(ingressMethods.ByName("ResolveAwakeable")),
			connect.WithClientOptions(opts...),
		),
		describeInvocation: connect.NewClient[ingressv1.DescribeInvocationRequest, ingressv1.DescribeInvocationResponse](
			httpClient,
			baseURL+IngressDescribeInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("DescribeInvocation")),
			connect.WithClientOptions(opts...),
		),
		attachInvocation: connect.NewClient[ingressv1.AttachInvocationRequest, ingressv1.AttachInvocationResponse](
			httpClient,
			baseURL+IngressAttachInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("AttachInvocation")),
			connect.WithClientOptions(opts...),
		),
		getInvocationOutput: connect.NewClient[ingressv1.GetInvocationOutputRequest, ingressv1.GetInvocationOutputResponse](
			httpClient,
			baseURL+IngressGetInvocationOutputProcedure,
			connect.WithSchema(ingressMethods.ByName("GetInvocationOutput")),
			connect.WithClientOptions(opts...),
		),
		getObjectState: connect.NewClient[ingressv1.GetObjectStateRequest, ingressv1.GetObjectStateResponse](
			httpClient,
			baseURL+IngressGetObjectStateProcedure,
			connect.WithSchema(ingressMethods.ByName("GetObjectState")),
			connect.WithClientOptions(opts...),
		),
		cancelInvocation: connect.NewClient[ingressv1.CancelInvocationRequest, ingressv1.CancelInvocationResponse](
			httpClient,
			baseURL+IngressCancelInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("CancelInvocation")),
			connect.WithClientOptions(opts...),
		),
		resolveWorkflowPromise: connect.NewClient[ingressv1.ResolveWorkflowPromiseRequest, ingressv1.ResolveWorkflowPromiseResponse](
			httpClient,
			baseURL+IngressResolveWorkflowPromiseProcedure,
			connect.WithSchema(ingressMethods.ByName("ResolveWorkflowPromise")),
			connect.WithClientOptions(opts...),
		),
		purgeInvocation: connect.NewClient[ingressv1.PurgeInvocationRequest, ingressv1.PurgeInvocationResponse](
			httpClient,
			baseURL+IngressPurgeInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("PurgeInvocation")),
			connect.WithClientOptions(opts...),
		),
		listInvocations: connect.NewClient[ingressv1.ListInvocationsRequest, ingressv1.ListInvocationsResponse](
			httpClient,
			baseURL+IngressListInvocationsProcedure,
			connect.WithSchema(ingressMethods.ByName("ListInvocations")),
			connect.WithClientOptions(opts...),
		),
		startProcess: connect.NewClient[ingressv1.StartProcessRequest, ingressv1.StartProcessResponse](
			httpClient,
			baseURL+IngressStartProcessProcedure,
			connect.WithSchema(ingressMethods.ByName("StartProcess")),
			connect.WithClientOptions(opts...),
		),
		deliverMessage: connect.NewClient[ingressv1.DeliverMessageRequest, ingressv1.DeliverMessageResponse](
			httpClient,
			baseURL+IngressDeliverMessageProcedure,
			connect.WithSchema(ingressMethods.ByName("DeliverMessage")),
			connect.WithClientOptions(opts...),
		),
		deliverProcessEvent: connect.NewClient[ingressv1.DeliverProcessEventRequest, ingressv1.DeliverProcessEventResponse](
			httpClient,
			baseURL+IngressDeliverProcessEventProcedure,
			connect.WithSchema(ingressMethods.ByName("DeliverProcessEvent")),
			connect.WithClientOptions(opts...),
		),
		getProcessInstance: connect.NewClient[ingressv1.GetProcessInstanceRequest, ingressv1.GetProcessInstanceResponse](
			httpClient,
			baseURL+IngressGetProcessInstanceProcedure,
			connect.WithSchema(ingressMethods.ByName("GetProcessInstance")),
			connect.WithClientOptions(opts...),
		),
		listProcessInstances: connect.NewClient[ingressv1.ListProcessInstancesRequest, ingressv1.ListProcessInstancesResponse](
			httpClient,
			baseURL+IngressListProcessInstancesProcedure,
			connect.WithSchema(ingressMethods.ByName("ListProcessInstances")),
			connect.WithClientOptions(opts...),
		),
		getProcessInstanceHistory: connect.NewClient[ingressv1.GetProcessInstanceHistoryRequest, ingressv1.GetProcessInstanceHistoryResponse](
			httpClient,
			baseURL+IngressGetProcessInstanceHistoryProcedure,
			connect.WithSchema(ingressMethods.ByName("GetProcessInstanceHistory")),
			connect.WithClientOptions(opts...),
		),
		resolveProcessIncident: connect.NewClient[ingressv1.ResolveProcessIncidentRequest, ingressv1.ResolveProcessIncidentResponse](
			httpClient,
			baseURL+IngressResolveProcessIncidentProcedure,
			connect.WithSchema(ingressMethods.ByName("ResolveProcessIncident")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[ingressv1.GetTaskRequest, ingressv1.GetTaskResponse](
			httpClient,
			baseURL+IngressGetTaskProcedure,
			connect.WithSchema(ingressMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		completeTask: connect.NewClient[ingressv1.CompleteTaskRequest, ingressv1.CompleteTaskResponse](
			httpClient,
			baseURL+IngressCompleteTaskProcedure,
			connect.WithSchema(ingressMethods.ByName("CompleteTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingressClient implements IngressClient.
type ingressClient struct {
	submitInvocation          *connect.Client[ingressv1.SubmitInvocationRequest, ingressv1.SubmitInvocationResponse]
	awaitInvocation           *connect.Client[ingressv1.AwaitInvocationRequest, ingressv1.AwaitInvocationResponse]
	resolveAwakeable          *connect.Client[ingressv1.ResolveAwakeableRequest, ingressv1.ResolveAwakeableResponse]
	describeInvocation        *connect.Client[ingressv1.DescribeInvocationRequest, ingressv1.DescribeInvocationResponse]
	attachInvocation          *connect.Client[ingressv1.AttachInvocationRequest, ingressv1.AttachInvocationResponse]
	getInvocationOutput       *connect.Client[ingressv1.GetInvocationOutputRequest, ingressv1.GetInvocationOutputResponse]
	getObjectState            *connect.Client[ingressv1.GetObjectStateRequest, ingressv1.GetObjectStateResponse]
	cancelInvocation          *connect.Client[ingressv1.CancelInvocationRequest, ingressv1.CancelInvocationResponse]
	resolveWorkflowPromise    *connect.Client[ingressv1.ResolveWorkflowPromiseRequest, ingressv1.ResolveWorkflowPromiseResponse]
	purgeInvocation           *connect.Client[ingressv1.PurgeInvocationRequest, ingressv1.PurgeInvocationResponse]
	listInvocations           *connect.Client[ingressv1.ListInvocationsRequest, ingressv1.ListInvocationsResponse]
	startProcess              *connect.Client[ingressv1.StartProcessRequest, ingressv1.StartProcessResponse]
	deliverMessage            *connect.Client[ingressv1.DeliverMessageRequest, ingressv1.DeliverMessageResponse]
	deliverProcessEvent       *connect.Client[ingressv1.DeliverProcessEventRequest, ingressv1.DeliverProcessEventResponse]
	getProcessInstance        *connect.Client[ingressv1.GetProcessInstanceRequest, ingressv1.GetProcessInstanceResponse]
	listProcessInstances      *connect.Client[ingressv1.ListProcessInstancesRequest, ingressv1.ListProcessInstancesResponse]
	getProcessInstanceHistory *connect.Client[ingressv1.GetProcessInstanceHistoryRequest, ingressv1.GetProcessInstanceHistoryResponse]
	resolveProcessIncident    *connect.Client[ingressv1.ResolveProcessIncidentRequest, ingressv1.ResolveProcessIncidentResponse]
	getTask                   *connect.Client[ingressv1.GetTaskRequest, ingressv1.GetTaskResponse]
	completeTask              *connect.Client[ingressv1.CompleteTaskRequest, ingressv1.CompleteTaskResponse]
}

// SubmitInvocation calls reflw.ingress.v1.Ingress.SubmitInvocation.
func (c *ingressClient) SubmitInvocation(ctx context.Context, req *connect.Request[ingressv1.SubmitInvocationRequest]) (*connect.Response[ingressv1.SubmitInvocationResponse], error) {
	return c.submitInvocation.CallUnary(ctx, req)
}

// AwaitInvocation calls reflw.ingress.v1.Ingress.AwaitInvocation.
func (c *ingressClient) AwaitInvocation(ctx context.Context, req *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error) {
	return c.awaitInvocation.CallUnary(ctx, req)
}

// ResolveAwakeable calls reflw.ingress.v1.Ingress.ResolveAwakeable.
func (c *ingressClient) ResolveAwakeable(ctx context.Context, req *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error) {
	return c.resolveAwakeable.CallUnary(ctx, req)
}

// DescribeInvocation calls reflw.ingress.v1.Ingress.DescribeInvocation.
func (c *ingressClient) DescribeInvocation(ctx context.Context, req *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error) {
	return c.describeInvocation.CallUnary(ctx, req)
}

// AttachInvocation calls reflw.ingress.v1.Ingress.AttachInvocation.
func (c *ingressClient) AttachInvocation(ctx context.Context, req *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error) {
	return c.attachInvocation.CallUnary(ctx, req)
}

// GetInvocationOutput calls reflw.ingress.v1.Ingress.GetInvocationOutput.
func (c *ingressClient) GetInvocationOutput(ctx context.Context, req *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error) {
	return c.getInvocationOutput.CallUnary(ctx, req)
}

// GetObjectState calls reflw.ingress.v1.Ingress.GetObjectState.
func (c *ingressClient) GetObjectState(ctx context.Context, req *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error) {
	return c.getObjectState.CallUnary(ctx, req)
}

// CancelInvocation calls reflw.ingress.v1.Ingress.CancelInvocation.
func (c *ingressClient) CancelInvocation(ctx context.Context, req *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error) {
	return c.cancelInvocation.CallUnary(ctx, req)
}

// ResolveWorkflowPromise calls reflw.ingress.v1.Ingress.ResolveWorkflowPromise.
func (c *ingressClient) ResolveWorkflowPromise(ctx context.Context, req *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error) {
	return c.resolveWorkflowPromise.CallUnary(ctx, req)
}

// PurgeInvocation calls reflw.ingress.v1.Ingress.PurgeInvocation.
func (c *ingressClient) PurgeInvocation(ctx context.Context, req *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error) {
	return c.purgeInvocation.CallUnary(ctx, req)
}

// ListInvocations calls reflw.ingress.v1.Ingress.ListInvocations.
func (c *ingressClient) ListInvocations(ctx context.Context, req *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error) {
	return c.listInvocations.CallUnary(ctx, req)
}

// StartProcess calls reflw.ingress.v1.Ingress.StartProcess.
func (c *ingressClient) StartProcess(ctx context.Context, req *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error) {
	return c.startProcess.CallUnary(ctx, req)
}

// DeliverMessage calls reflw.ingress.v1.Ingress.DeliverMessage.
func (c *ingressClient) DeliverMessage(ctx context.Context, req *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error) {
	return c.deliverMessage.CallUnary(ctx, req)
}

// DeliverProcessEvent calls reflw.ingress.v1.Ingress.DeliverProcessEvent.
func (c *ingressClient) DeliverProcessEvent(ctx context.Context, req *connect.Request[ingressv1.DeliverProcessEventRequest]) (*connect.Response[ingressv1.DeliverProcessEventResponse], error) {
	return c.deliverProcessEvent.CallUnary(ctx, req)
}

// GetProcessInstance calls reflw.ingress.v1.Ingress.GetProcessInstance.
func (c *ingressClient) GetProcessInstance(ctx context.Context, req *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error) {
	return c.getProcessInstance.CallUnary(ctx, req)
}

// ListProcessInstances calls reflw.ingress.v1.Ingress.ListProcessInstances.
func (c *ingressClient) ListProcessInstances(ctx context.Context, req *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error) {
	return c.listProcessInstances.CallUnary(ctx, req)
}

// GetProcessInstanceHistory calls reflw.ingress.v1.Ingress.GetProcessInstanceHistory.
func (c *ingressClient) GetProcessInstanceHistory(ctx context.Context, req *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error) {
	return c.getProcessInstanceHistory.CallUnary(ctx, req)
}

// ResolveProcessIncident calls reflw.ingress.v1.Ingress.ResolveProcessIncident.
func (c *ingressClient) ResolveProcessIncident(ctx context.Context, req *connect.Request[ingressv1.ResolveProcessIncidentRequest]) (*connect.Response[ingressv1.ResolveProcessIncidentResponse], error) {
	return c.resolveProcessIncident.CallUnary(ctx, req)
}

// GetTask calls reflw.ingress.v1.Ingress.GetTask.
func (c *ingressClient) GetTask(ctx context.Context, req *connect.Request[ingressv1.GetTaskRequest]) (*connect.Response[ingressv1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// CompleteTask calls reflw.ingress.v1.Ingress.CompleteTask.
func (c *ingressClient) CompleteTask(ctx context.Context, req *connect.Request[ingressv1.CompleteTaskRequest]) (*connect.Response[ingressv1.CompleteTaskResponse], error) {
	return c.completeTask.CallUnary(ctx, req)
}

// IngressHandler is an implementation of the reflw.ingress.v1.Ingress service.
type IngressHandler interface {
	// SubmitInvocation mints an invocation for (service, handler[, object_key])
	// and, in AWAIT mode (the default), blocks for its result; in SEND mode it
	// returns the minted id immediately. service/handler/object_key ride the
	// body (not the path) so the transcoder has no wildcard route. Caller
	// metadata flows via the metadata map and/or Reflw-Meta-* request headers.
	SubmitInvocation(context.Context, *connect.Request[ingressv1.SubmitInvocationRequest]) (*connect.Response[ingressv1.SubmitInvocationResponse], error)
	// AwaitInvocation blocks (up to deadline) until the named invocation
	// reaches Completed and returns its output. Server-side polling of
	// SyncRead today; SSE/streaming is a future evolution.
	AwaitInvocation(context.Context, *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error)
	// ResolveAwakeable completes an outstanding awakeable previously
	// created by a handler via ctx.Awakeable(). Routes to the owning
	// partition by looking up the awakeable directory.
	ResolveAwakeable(context.Context, *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error)
	// DescribeInvocation returns the current status of an invocation
	// without blocking. Read-only debug endpoint.
	DescribeInvocation(context.Context, *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error)
	// AttachInvocation blocks (up to deadline) on an existing invocation
	// and returns its outcome once Completed. Same shape as
	// AwaitInvocation but explicit about attaching to an already-
	// submitted invocation by id.
	AttachInvocation(context.Context, *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error)
	// GetInvocationOutput is a non-blocking lookup of an invocation's
	// current outcome. Returns PENDING for still-running invocations,
	// COMPLETED_OK / COMPLETED_FAILED for terminated ones, UNKNOWN if no
	// such invocation is known to this node.
	GetInvocationOutput(context.Context, *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error)
	// GetObjectState reads a single state value for a virtual object.
	// Routes to the partition owning (service, object_key) through the
	// cluster Partitioner. present=false (not an error) when the key is absent.
	GetObjectState(context.Context, *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error)
	// CancelInvocation forces a running invocation to terminate with
	// FailureCode=9002 (cancelled). Implemented as a __cancel__ signal
	// delivered to the invocation's (service, key); the receiver shard
	// resolves the active InvocationId via KeyLeaseTable and synthesizes
	// a terminal Completed. Idempotent: cancelling an already-completed
	// invocation is a no-op.
	CancelInvocation(context.Context, *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error)
	// ResolveWorkflowPromise resolves or rejects a named workflow-scoped
	// durable promise. Routes by (service, workflow_key) via
	// Partitioner.ShardForTarget; the receiver shard writes PromiseValue
	// and wakes any in-flight Promise(name).Result() awaiter. Idempotent
	// against already-completed promises: succeeded=false signals
	// "promise already completed" without an error status.
	ResolveWorkflowPromise(context.Context, *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error)
	// PurgeInvocation deletes a Completed invocation's durable rows (inv
	// status, journal, signal inbox/awaiter) immediately, instead of
	// waiting for the retention reaper. Routes by the partition_key encoded
	// in the invocation id. Idempotent and no-op-safe: purging an absent or
	// not-yet-Completed invocation is accepted but changes nothing (the
	// apply arm requires a Completed/Free → Free transition). Does not touch
	// virtual-object state or workflow promise rows. Operator-only.
	PurgeInvocation(context.Context, *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error)
	// ListInvocations lists invocations across the namespace, fanning out across
	// all partition shards (same substrate as ListProcessInstances). Optional
	// service-name and state filters; capped by limit. Read-only — no proposal.
	ListInvocations(context.Context, *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error)
	// StartProcess launches a new reflwos BPMN/CMMN instance. kind ("bpmn" |
	// "cmmn") selects the plane; routing is by (name, instance_key). Proposes a
	// start ProcessEvent (model_ref + kind set). Idempotent per (model,
	// instance_key): a start for an already-existing instance is dropped by the
	// apply path. When instance_key is empty the server mints a random one (then
	// not idempotent).
	StartProcess(context.Context, *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error)
	// DeliverMessage correlates an inbound message/signal to parked process
	// instances. Routes to the partition owning (message_name,
	// correlation_key) and proposes DeliverProcessMessage, which fans the message
	// out to every instance subscribed on that (message_name, correlation_key).
	// An empty correlation_key addresses every instance waiting on the name (BPMN
	// signal broadcast). Messages with no current subscriber are dropped.
	DeliverMessage(context.Context, *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error)
	// DeliverProcessEvent injects an external typed engine event into a RUNNING
	// instance addressed by (name, instance_key) — the path a human or operator
	// uses to fire a CMMN user-event listener or push a variable update onto a
	// parked conditional. Point-to-point: it proposes a continuation ProcessEvent
	// (no model_ref → the apply path appends to the named instance's inbox and
	// advances one turn). An absent or terminal instance is a benign drop. To
	// complete a parked user/human task by its resume token, use CompleteTask.
	DeliverProcessEvent(context.Context, *connect.Request[ingressv1.DeliverProcessEventRequest]) (*connect.Response[ingressv1.DeliverProcessEventResponse], error)
	// GetProcessInstance is a linearizable read of one instance's current state,
	// routed by (name, instance_key) like StartProcess. present=false means the
	// instance never started OR already reached a terminal and was reaped.
	// Read-only — no proposal.
	GetProcessInstance(context.Context, *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error)
	// ListProcessInstances lists process instances across the namespace, fanning
	// out across all partition shards. Optional model-name and status filters;
	// capped by limit.
	ListProcessInstances(context.Context, *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error)
	// GetProcessInstanceHistory reads one instance's append-only activity timeline
	// (start, inbound events, task dispatch/complete, timer arm/fire, child
	// start/complete, subscribe/unsubscribe, message received, terminal), routed by
	// (name, instance_key) like GetProcessInstance. Read-only — no proposal. The
	// timeline survives a terminal only within the instance's retention window;
	// present=false means the instance never started or was reaped. Page forward
	// with after_seq.
	GetProcessInstanceHistory(context.Context, *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error)
	// ResolveProcessIncident resolves an incident-parked instance (one whose
	// status is PROCESS_STATUS_INCIDENT — an uncaught failure parked for human
	// intervention). RETRY re-drives the failed element as a new turn (optionally
	// patching variables first); TERMINATE fails the instance terminally. Routed by
	// (name, instance_key) like StartProcess. Idempotent: resolving a non-incident
	// instance is accepted but changes nothing (accepted=false).
	ResolveProcessIncident(context.Context, *connect.Request[ingressv1.ResolveProcessIncidentRequest]) (*connect.Response[ingressv1.ResolveProcessIncidentResponse], error)
	// GetTask resolves an opaque resume token (from a GetProcessInstance
	// awaiting_tasks entry) to the parked user/human task it addresses — the
	// discovery (read) half of the resume-token surface. Returned only when the
	// token is live (instance present, RUNNING, node_id still awaiting); a
	// stale/consumed/forged token is FailedPrecondition. The schema field, when
	// set, is the task's submission JSON Schema (model-derived, best-effort).
	GetTask(context.Context, *connect.Request[ingressv1.GetTaskRequest]) (*connect.Response[ingressv1.GetTaskResponse], error)
	// CompleteTask completes (or fails) a parked BPMN user task / CMMN human task
	// by its opaque resume token — the consume half of the resume-token flow. The
	// token carries (name, instance_key, node_id), so the caller names no element
	// id; it supplies only the output vars (or, when fail=true, a failure message).
	// A linearizable read gates it (the task must still be awaiting) else
	// FailedPrecondition.
	CompleteTask(context.Context, *connect.Request[ingressv1.CompleteTaskRequest]) (*connect.Response[ingressv1.CompleteTaskResponse], error)
}

// NewIngressHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngressHandler(svc IngressHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingressMethods := ingressv1.File_ingressv1_ingress_proto.Services().ByName("Ingress").Methods()
	ingressSubmitInvocationHandler := connect.NewUnaryHandler(
		IngressSubmitInvocationProcedure,
		svc.SubmitInvocation,
		connect.WithSchema(ingressMethods.ByName("SubmitInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressAwaitInvocationHandler := connect.NewUnaryHandler(
		IngressAwaitInvocationProcedure,
		svc.AwaitInvocation,
		connect.WithSchema(ingressMethods.ByName("AwaitInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressResolveAwakeableHandler := connect.NewUnaryHandler(
		IngressResolveAwakeableProcedure,
		svc.ResolveAwakeable,
		connect.WithSchema(ingressMethods.ByName("ResolveAwakeable")),
		connect.WithHandlerOptions(opts...),
	)
	ingressDescribeInvocationHandler := connect.NewUnaryHandler(
		IngressDescribeInvocationProcedure,
		svc.DescribeInvocation,
		connect.WithSchema(ingressMethods.ByName("DescribeInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressAttachInvocationHandler := connect.NewUnaryHandler(
		IngressAttachInvocationProcedure,
		svc.AttachInvocation,
		connect.WithSchema(ingressMethods.ByName("AttachInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetInvocationOutputHandler := connect.NewUnaryHandler(
		IngressGetInvocationOutputProcedure,
		svc.GetInvocationOutput,
		connect.WithSchema(ingressMethods.ByName("GetInvocationOutput")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetObjectStateHandler := connect.NewUnaryHandler(
		IngressGetObjectStateProcedure,
		svc.GetObjectState,
		connect.WithSchema(ingressMethods.ByName("GetObjectState")),
		connect.WithHandlerOptions(opts...),
	)
	ingressCancelInvocationHandler := connect.NewUnaryHandler(
		IngressCancelInvocationProcedure,
		svc.CancelInvocation,
		connect.WithSchema(ingressMethods.ByName("CancelInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressResolveWorkflowPromiseHandler := connect.NewUnaryHandler(
		IngressResolveWorkflowPromiseProcedure,
		svc.ResolveWorkflowPromise,
		connect.WithSchema(ingressMethods.ByName("ResolveWorkflowPromise")),
		connect.WithHandlerOptions(opts...),
	)
	ingressPurgeInvocationHandler := connect.NewUnaryHandler(
		IngressPurgeInvocationProcedure,
		svc.PurgeInvocation,
		connect.WithSchema(ingressMethods.ByName("PurgeInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressListInvocationsHandler := connect.NewUnaryHandler(
		IngressListInvocationsProcedure,
		svc.ListInvocations,
		connect.WithSchema(ingressMethods.ByName("ListInvocations")),
		connect.WithHandlerOptions(opts...),
	)
	ingressStartProcessHandler := connect.NewUnaryHandler(
		IngressStartProcessProcedure,
		svc.StartProcess,
		connect.WithSchema(ingressMethods.ByName("StartProcess")),
		connect.WithHandlerOptions(opts...),
	)
	ingressDeliverMessageHandler := connect.NewUnaryHandler(
		IngressDeliverMessageProcedure,
		svc.DeliverMessage,
		connect.WithSchema(ingressMethods.ByName("DeliverMessage")),
		connect.WithHandlerOptions(opts...),
	)
	ingressDeliverProcessEventHandler := connect.NewUnaryHandler(
		IngressDeliverProcessEventProcedure,
		svc.DeliverProcessEvent,
		connect.WithSchema(ingressMethods.ByName("DeliverProcessEvent")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetProcessInstanceHandler := connect.NewUnaryHandler(
		IngressGetProcessInstanceProcedure,
		svc.GetProcessInstance,
		connect.WithSchema(ingressMethods.ByName("GetProcessInstance")),
		connect.WithHandlerOptions(opts...),
	)
	ingressListProcessInstancesHandler := connect.NewUnaryHandler(
		IngressListProcessInstancesProcedure,
		svc.ListProcessInstances,
		connect.WithSchema(ingressMethods.ByName("ListProcessInstances")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetProcessInstanceHistoryHandler := connect.NewUnaryHandler(
		IngressGetProcessInstanceHistoryProcedure,
		svc.GetProcessInstanceHistory,
		connect.WithSchema(ingressMethods.ByName("GetProcessInstanceHistory")),
		connect.WithHandlerOptions(opts...),
	)
	ingressResolveProcessIncidentHandler := connect.NewUnaryHandler(
		IngressResolveProcessIncidentProcedure,
		svc.ResolveProcessIncident,
		connect.WithSchema(ingressMethods.ByName("ResolveProcessIncident")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetTaskHandler := connect.NewUnaryHandler(
		IngressGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(ingressMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	ingressCompleteTaskHandler := connect.NewUnaryHandler(
		IngressCompleteTaskProcedure,
		svc.CompleteTask,
		connect.WithSchema(ingressMethods.ByName("CompleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/reflw.ingress.v1.Ingress/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngressSubmitInvocationProcedure:
			ingressSubmitInvocationHandler.ServeHTTP(w, r)
		case IngressAwaitInvocationProcedure:
			ingressAwaitInvocationHandler.ServeHTTP(w, r)
		case IngressResolveAwakeableProcedure:
			ingressResolveAwakeableHandler.ServeHTTP(w, r)
		case IngressDescribeInvocationProcedure:
			ingressDescribeInvocationHandler.ServeHTTP(w, r)
		case IngressAttachInvocationProcedure:
			ingressAttachInvocationHandler.ServeHTTP(w, r)
		case IngressGetInvocationOutputProcedure:
			ingressGetInvocationOutputHandler.ServeHTTP(w, r)
		case IngressGetObjectStateProcedure:
			ingressGetObjectStateHandler.ServeHTTP(w, r)
		case IngressCancelInvocationProcedure:
			ingressCancelInvocationHandler.ServeHTTP(w, r)
		case IngressResolveWorkflowPromiseProcedure:
			ingressResolveWorkflowPromiseHandler.ServeHTTP(w, r)
		case IngressPurgeInvocationProcedure:
			ingressPurgeInvocationHandler.ServeHTTP(w, r)
		case IngressListInvocationsProcedure:
			ingressListInvocationsHandler.ServeHTTP(w, r)
		case IngressStartProcessProcedure:
			ingressStartProcessHandler.ServeHTTP(w, r)
		case IngressDeliverMessageProcedure:
			ingressDeliverMessageHandler.ServeHTTP(w, r)
		case IngressDeliverProcessEventProcedure:
			ingressDeliverProcessEventHandler.ServeHTTP(w, r)
		case IngressGetProcessInstanceProcedure:
			ingressGetProcessInstanceHandler.ServeHTTP(w, r)
		case IngressListProcessInstancesProcedure:
			ingressListProcessInstancesHandler.ServeHTTP(w, r)
		case IngressGetProcessInstanceHistoryProcedure:
			ingressGetProcessInstanceHistoryHandler.ServeHTTP(w, r)
		case IngressResolveProcessIncidentProcedure:
			ingressResolveProcessIncidentHandler.ServeHTTP(w, r)
		case IngressGetTaskProcedure:
			ingressGetTaskHandler.ServeHTTP(w, r)
		case IngressCompleteTaskProcedure:
			ingressCompleteTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngressHandler returns CodeUnimplemented from all methods.
type UnimplementedIngressHandler struct{}

func (UnimplementedIngressHandler) SubmitInvocation(context.Context, *connect.Request[ingressv1.SubmitInvocationRequest]) (*connect.Response[ingressv1.SubmitInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.SubmitInvocation is not implemented"))
}

func (UnimplementedIngressHandler) AwaitInvocation(context.Context, *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.AwaitInvocation is not implemented"))
}

func (UnimplementedIngressHandler) ResolveAwakeable(context.Context, *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ResolveAwakeable is not implemented"))
}

func (UnimplementedIngressHandler) DescribeInvocation(context.Context, *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.DescribeInvocation is not implemented"))
}

func (UnimplementedIngressHandler) AttachInvocation(context.Context, *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.AttachInvocation is not implemented"))
}

func (UnimplementedIngressHandler) GetInvocationOutput(context.Context, *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetInvocationOutput is not implemented"))
}

func (UnimplementedIngressHandler) GetObjectState(context.Context, *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetObjectState is not implemented"))
}

func (UnimplementedIngressHandler) CancelInvocation(context.Context, *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.CancelInvocation is not implemented"))
}

func (UnimplementedIngressHandler) ResolveWorkflowPromise(context.Context, *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ResolveWorkflowPromise is not implemented"))
}

func (UnimplementedIngressHandler) PurgeInvocation(context.Context, *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.PurgeInvocation is not implemented"))
}

func (UnimplementedIngressHandler) ListInvocations(context.Context, *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ListInvocations is not implemented"))
}

func (UnimplementedIngressHandler) StartProcess(context.Context, *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.StartProcess is not implemented"))
}

func (UnimplementedIngressHandler) DeliverMessage(context.Context, *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.DeliverMessage is not implemented"))
}

func (UnimplementedIngressHandler) DeliverProcessEvent(context.Context, *connect.Request[ingressv1.DeliverProcessEventRequest]) (*connect.Response[ingressv1.DeliverProcessEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.DeliverProcessEvent is not implemented"))
}

func (UnimplementedIngressHandler) GetProcessInstance(context.Context, *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetProcessInstance is not implemented"))
}

func (UnimplementedIngressHandler) ListProcessInstances(context.Context, *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ListProcessInstances is not implemented"))
}

func (UnimplementedIngressHandler) GetProcessInstanceHistory(context.Context, *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetProcessInstanceHistory is not implemented"))
}

func (UnimplementedIngressHandler) ResolveProcessIncident(context.Context, *connect.Request[ingressv1.ResolveProcessIncidentRequest]) (*connect.Response[ingressv1.ResolveProcessIncidentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ResolveProcessIncident is not implemented"))
}

func (UnimplementedIngressHandler) GetTask(context.Context, *connect.Request[ingressv1.GetTaskRequest]) (*connect.Response[ingressv1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetTask is not implemented"))
}

func (UnimplementedIngressHandler) CompleteTask(context.Context, *connect.Request[ingressv1.CompleteTaskRequest]) (*connect.Response[ingressv1.CompleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.CompleteTask is not implemented"))
}
