// Reflow ingress service.
//
// Exposes the user-facing entrypoints for submitting invocations, awaiting
// their results, and resolving awakeables. Served over Connect (HTTP/2)
// with content-negotiated Connect / gRPC / gRPC-Web / HTTP-JSON; clients
// pick a wire encoding by setting Content-Type. The default reflwd
// config is single-partition (shard 1) but ingress is partition-agnostic
// and routes via Host.Partitioner.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ingressv1/ingress.proto

package ingressv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	ingressv1 "github.com/twinfer/reflw/proto/ingressv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngressName is the fully-qualified name of the Ingress service.
	IngressName = "reflw.ingress.v1.Ingress"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngressAwaitInvocationProcedure is the fully-qualified name of the Ingress's AwaitInvocation RPC.
	IngressAwaitInvocationProcedure = "/reflw.ingress.v1.Ingress/AwaitInvocation"
	// IngressResolveAwakeableProcedure is the fully-qualified name of the Ingress's ResolveAwakeable
	// RPC.
	IngressResolveAwakeableProcedure = "/reflw.ingress.v1.Ingress/ResolveAwakeable"
	// IngressDescribeInvocationProcedure is the fully-qualified name of the Ingress's
	// DescribeInvocation RPC.
	IngressDescribeInvocationProcedure = "/reflw.ingress.v1.Ingress/DescribeInvocation"
	// IngressAttachInvocationProcedure is the fully-qualified name of the Ingress's AttachInvocation
	// RPC.
	IngressAttachInvocationProcedure = "/reflw.ingress.v1.Ingress/AttachInvocation"
	// IngressGetInvocationOutputProcedure is the fully-qualified name of the Ingress's
	// GetInvocationOutput RPC.
	IngressGetInvocationOutputProcedure = "/reflw.ingress.v1.Ingress/GetInvocationOutput"
	// IngressGetObjectStateProcedure is the fully-qualified name of the Ingress's GetObjectState RPC.
	IngressGetObjectStateProcedure = "/reflw.ingress.v1.Ingress/GetObjectState"
	// IngressCancelInvocationProcedure is the fully-qualified name of the Ingress's CancelInvocation
	// RPC.
	IngressCancelInvocationProcedure = "/reflw.ingress.v1.Ingress/CancelInvocation"
	// IngressResolveWorkflowPromiseProcedure is the fully-qualified name of the Ingress's
	// ResolveWorkflowPromise RPC.
	IngressResolveWorkflowPromiseProcedure = "/reflw.ingress.v1.Ingress/ResolveWorkflowPromise"
	// IngressPurgeInvocationProcedure is the fully-qualified name of the Ingress's PurgeInvocation RPC.
	IngressPurgeInvocationProcedure = "/reflw.ingress.v1.Ingress/PurgeInvocation"
	// IngressListInvocationsProcedure is the fully-qualified name of the Ingress's ListInvocations RPC.
	IngressListInvocationsProcedure = "/reflw.ingress.v1.Ingress/ListInvocations"
	// IngressStartProcessProcedure is the fully-qualified name of the Ingress's StartProcess RPC.
	IngressStartProcessProcedure = "/reflw.ingress.v1.Ingress/StartProcess"
	// IngressDeliverMessageProcedure is the fully-qualified name of the Ingress's DeliverMessage RPC.
	IngressDeliverMessageProcedure = "/reflw.ingress.v1.Ingress/DeliverMessage"
	// IngressGetProcessInstanceProcedure is the fully-qualified name of the Ingress's
	// GetProcessInstance RPC.
	IngressGetProcessInstanceProcedure = "/reflw.ingress.v1.Ingress/GetProcessInstance"
	// IngressListProcessInstancesProcedure is the fully-qualified name of the Ingress's
	// ListProcessInstances RPC.
	IngressListProcessInstancesProcedure = "/reflw.ingress.v1.Ingress/ListProcessInstances"
	// IngressGetProcessInstanceHistoryProcedure is the fully-qualified name of the Ingress's
	// GetProcessInstanceHistory RPC.
	IngressGetProcessInstanceHistoryProcedure = "/reflw.ingress.v1.Ingress/GetProcessInstanceHistory"
)

// IngressClient is a client for the reflw.ingress.v1.Ingress service.
type IngressClient interface {
	// AwaitInvocation blocks (up to deadline) until the named invocation
	// reaches Completed and returns its output. Server-side polling of
	// SyncRead today; SSE/streaming is a future evolution.
	AwaitInvocation(context.Context, *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error)
	// ResolveAwakeable completes an outstanding awakeable previously
	// created by a handler via ctx.Awakeable(). Routes to the owning
	// partition by looking up the awakeable directory.
	ResolveAwakeable(context.Context, *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error)
	// DescribeInvocation returns the current status of an invocation
	// without blocking. Read-only debug endpoint.
	DescribeInvocation(context.Context, *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error)
	// AttachInvocation blocks (up to deadline) on an existing invocation
	// and returns its outcome once Completed. Same shape as
	// AwaitInvocation but explicit about attaching to an already-
	// submitted invocation by id.
	AttachInvocation(context.Context, *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error)
	// GetInvocationOutput is a non-blocking lookup of an invocation's
	// current outcome. Returns PENDING for still-running invocations,
	// COMPLETED_OK / COMPLETED_FAILED for terminated ones, UNKNOWN if no
	// such invocation is known to this node.
	GetInvocationOutput(context.Context, *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error)
	// GetObjectState reads a single state value for a virtual object.
	// Routes to the partition owning the object by hashing (service,
	// object_key) through the cluster Partitioner. present=false (not an
	// error) when the key is absent.
	GetObjectState(context.Context, *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error)
	// CancelInvocation forces a running invocation to terminate with
	// FailureCode=9002 (cancelled). Implemented as a __cancel__ signal
	// delivered to the invocation's (service, key); the receiver shard
	// resolves the active InvocationId via KeyLeaseTable and synthesizes
	// a terminal Completed. Idempotent: cancelling an already-completed
	// invocation is a no-op.
	CancelInvocation(context.Context, *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error)
	// ResolveWorkflowPromise resolves or rejects a named workflow-scoped
	// durable promise. Routes by (service, workflow_key) via
	// Partitioner.ShardForTarget; the receiver shard writes PromiseValue
	// and wakes any in-flight Promise(name).Result() awaiter. Idempotent
	// against already-completed promises: succeeded=false signals
	// "promise already completed" without an error status.
	ResolveWorkflowPromise(context.Context, *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error)
	// PurgeInvocation deletes a Completed invocation's durable rows (inv
	// status, journal, signal inbox/awaiter) immediately, instead of
	// waiting for the retention reaper. Routes by the partition_key encoded
	// in the invocation id. Idempotent and no-op-safe: purging an absent or
	// not-yet-Completed invocation is accepted but changes nothing (the
	// apply arm requires a Completed/Free → Free transition). Does not touch
	// virtual-object state or workflow promise rows.
	PurgeInvocation(context.Context, *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error)
	// ListInvocations lists the caller tenant band's invocations, fanning out
	// across the shards owning the band's LPs (same substrate as
	// ListProcessInstances). Optional service-name and state filters; capped by
	// limit. Read-only — no proposal.
	ListInvocations(context.Context, *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error)
	// StartProcess launches a new reflwos BPMN/CMMN instance. Routes to the
	// partition owning (tenant, model name, instance_key) and proposes a start
	// ProcessEvent (model_ref + kind set). Idempotent per (model, instance_key):
	// a start for an already-existing instance is dropped by the apply path. When
	// instance_key is empty the server mints a random one (then not idempotent).
	StartProcess(context.Context, *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error)
	// DeliverMessage correlates an inbound message/signal to parked process
	// instances. Routes to the partition owning (tenant, message_name,
	// correlation_key) and proposes DeliverProcessMessage, which fans the message
	// out to every instance subscribed on that (message_name, correlation_key).
	// An empty correlation_key addresses every instance waiting on the name (BPMN
	// signal broadcast). Messages with no current subscriber are dropped.
	DeliverMessage(context.Context, *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error)
	// GetProcessInstance is a linearizable read of one instance's current state,
	// routed by (tenant, model name, instance_key) like StartProcess. It exists
	// so a caller without an await RPC can observe lifecycle: present=false means
	// the instance never started OR already reached a terminal and was reaped
	// (completion is immediate-reap, so a COMPLETED record never lingers);
	// present=true with active_seq>0 means a turn is in flight; present=true with
	// active_seq==0 means idle/parked on an external wait (a timer that will fire,
	// or a message/signal subscription). Read-only — no proposal.
	GetProcessInstance(context.Context, *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error)
	// ListProcessInstances lists the caller tenant band's process instances,
	// fanning out across the shards owning the band's LPs. Optional model-name and
	// status filters; capped by limit.
	ListProcessInstances(context.Context, *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error)
	// GetProcessInstanceHistory reads one instance's append-only activity timeline
	// (start, inbound events, task dispatch/complete, timer arm/fire, child
	// start/complete, subscribe/unsubscribe, message received, terminal), routed by
	// (tenant, model name, instance_key) like GetProcessInstance. Read-only — no
	// proposal. The timeline is bounded live (keep-last-N) and survives a terminal
	// only within the instance's retention window (historyTimeToLive); present=false
	// means the instance never started or was reaped. Page forward with after_seq.
	GetProcessInstanceHistory(context.Context, *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error)
}

// NewIngressClient constructs a client for the reflw.ingress.v1.Ingress service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngressClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngressClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ingressMethods := ingressv1.File_ingressv1_ingress_proto.Services().ByName("Ingress").Methods()
	return &ingressClient{
		awaitInvocation: connect.NewClient[ingressv1.AwaitInvocationRequest, ingressv1.AwaitInvocationResponse](
			httpClient,
			baseURL+IngressAwaitInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("AwaitInvocation")),
			connect.WithClientOptions(opts...),
		),
		resolveAwakeable: connect.NewClient[ingressv1.ResolveAwakeableRequest, ingressv1.ResolveAwakeableResponse](
			httpClient,
			baseURL+IngressResolveAwakeableProcedure,
			connect.WithSchema(ingressMethods.ByName("ResolveAwakeable")),
			connect.WithClientOptions(opts...),
		),
		describeInvocation: connect.NewClient[ingressv1.DescribeInvocationRequest, ingressv1.DescribeInvocationResponse](
			httpClient,
			baseURL+IngressDescribeInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("DescribeInvocation")),
			connect.WithClientOptions(opts...),
		),
		attachInvocation: connect.NewClient[ingressv1.AttachInvocationRequest, ingressv1.AttachInvocationResponse](
			httpClient,
			baseURL+IngressAttachInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("AttachInvocation")),
			connect.WithClientOptions(opts...),
		),
		getInvocationOutput: connect.NewClient[ingressv1.GetInvocationOutputRequest, ingressv1.GetInvocationOutputResponse](
			httpClient,
			baseURL+IngressGetInvocationOutputProcedure,
			connect.WithSchema(ingressMethods.ByName("GetInvocationOutput")),
			connect.WithClientOptions(opts...),
		),
		getObjectState: connect.NewClient[ingressv1.GetObjectStateRequest, ingressv1.GetObjectStateResponse](
			httpClient,
			baseURL+IngressGetObjectStateProcedure,
			connect.WithSchema(ingressMethods.ByName("GetObjectState")),
			connect.WithClientOptions(opts...),
		),
		cancelInvocation: connect.NewClient[ingressv1.CancelInvocationRequest, ingressv1.CancelInvocationResponse](
			httpClient,
			baseURL+IngressCancelInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("CancelInvocation")),
			connect.WithClientOptions(opts...),
		),
		resolveWorkflowPromise: connect.NewClient[ingressv1.ResolveWorkflowPromiseRequest, ingressv1.ResolveWorkflowPromiseResponse](
			httpClient,
			baseURL+IngressResolveWorkflowPromiseProcedure,
			connect.WithSchema(ingressMethods.ByName("ResolveWorkflowPromise")),
			connect.WithClientOptions(opts...),
		),
		purgeInvocation: connect.NewClient[ingressv1.PurgeInvocationRequest, ingressv1.PurgeInvocationResponse](
			httpClient,
			baseURL+IngressPurgeInvocationProcedure,
			connect.WithSchema(ingressMethods.ByName("PurgeInvocation")),
			connect.WithClientOptions(opts...),
		),
		listInvocations: connect.NewClient[ingressv1.ListInvocationsRequest, ingressv1.ListInvocationsResponse](
			httpClient,
			baseURL+IngressListInvocationsProcedure,
			connect.WithSchema(ingressMethods.ByName("ListInvocations")),
			connect.WithClientOptions(opts...),
		),
		startProcess: connect.NewClient[ingressv1.StartProcessRequest, ingressv1.StartProcessResponse](
			httpClient,
			baseURL+IngressStartProcessProcedure,
			connect.WithSchema(ingressMethods.ByName("StartProcess")),
			connect.WithClientOptions(opts...),
		),
		deliverMessage: connect.NewClient[ingressv1.DeliverMessageRequest, ingressv1.DeliverMessageResponse](
			httpClient,
			baseURL+IngressDeliverMessageProcedure,
			connect.WithSchema(ingressMethods.ByName("DeliverMessage")),
			connect.WithClientOptions(opts...),
		),
		getProcessInstance: connect.NewClient[ingressv1.GetProcessInstanceRequest, ingressv1.GetProcessInstanceResponse](
			httpClient,
			baseURL+IngressGetProcessInstanceProcedure,
			connect.WithSchema(ingressMethods.ByName("GetProcessInstance")),
			connect.WithClientOptions(opts...),
		),
		listProcessInstances: connect.NewClient[ingressv1.ListProcessInstancesRequest, ingressv1.ListProcessInstancesResponse](
			httpClient,
			baseURL+IngressListProcessInstancesProcedure,
			connect.WithSchema(ingressMethods.ByName("ListProcessInstances")),
			connect.WithClientOptions(opts...),
		),
		getProcessInstanceHistory: connect.NewClient[ingressv1.GetProcessInstanceHistoryRequest, ingressv1.GetProcessInstanceHistoryResponse](
			httpClient,
			baseURL+IngressGetProcessInstanceHistoryProcedure,
			connect.WithSchema(ingressMethods.ByName("GetProcessInstanceHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingressClient implements IngressClient.
type ingressClient struct {
	awaitInvocation           *connect.Client[ingressv1.AwaitInvocationRequest, ingressv1.AwaitInvocationResponse]
	resolveAwakeable          *connect.Client[ingressv1.ResolveAwakeableRequest, ingressv1.ResolveAwakeableResponse]
	describeInvocation        *connect.Client[ingressv1.DescribeInvocationRequest, ingressv1.DescribeInvocationResponse]
	attachInvocation          *connect.Client[ingressv1.AttachInvocationRequest, ingressv1.AttachInvocationResponse]
	getInvocationOutput       *connect.Client[ingressv1.GetInvocationOutputRequest, ingressv1.GetInvocationOutputResponse]
	getObjectState            *connect.Client[ingressv1.GetObjectStateRequest, ingressv1.GetObjectStateResponse]
	cancelInvocation          *connect.Client[ingressv1.CancelInvocationRequest, ingressv1.CancelInvocationResponse]
	resolveWorkflowPromise    *connect.Client[ingressv1.ResolveWorkflowPromiseRequest, ingressv1.ResolveWorkflowPromiseResponse]
	purgeInvocation           *connect.Client[ingressv1.PurgeInvocationRequest, ingressv1.PurgeInvocationResponse]
	listInvocations           *connect.Client[ingressv1.ListInvocationsRequest, ingressv1.ListInvocationsResponse]
	startProcess              *connect.Client[ingressv1.StartProcessRequest, ingressv1.StartProcessResponse]
	deliverMessage            *connect.Client[ingressv1.DeliverMessageRequest, ingressv1.DeliverMessageResponse]
	getProcessInstance        *connect.Client[ingressv1.GetProcessInstanceRequest, ingressv1.GetProcessInstanceResponse]
	listProcessInstances      *connect.Client[ingressv1.ListProcessInstancesRequest, ingressv1.ListProcessInstancesResponse]
	getProcessInstanceHistory *connect.Client[ingressv1.GetProcessInstanceHistoryRequest, ingressv1.GetProcessInstanceHistoryResponse]
}

// AwaitInvocation calls reflw.ingress.v1.Ingress.AwaitInvocation.
func (c *ingressClient) AwaitInvocation(ctx context.Context, req *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error) {
	return c.awaitInvocation.CallUnary(ctx, req)
}

// ResolveAwakeable calls reflw.ingress.v1.Ingress.ResolveAwakeable.
func (c *ingressClient) ResolveAwakeable(ctx context.Context, req *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error) {
	return c.resolveAwakeable.CallUnary(ctx, req)
}

// DescribeInvocation calls reflw.ingress.v1.Ingress.DescribeInvocation.
func (c *ingressClient) DescribeInvocation(ctx context.Context, req *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error) {
	return c.describeInvocation.CallUnary(ctx, req)
}

// AttachInvocation calls reflw.ingress.v1.Ingress.AttachInvocation.
func (c *ingressClient) AttachInvocation(ctx context.Context, req *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error) {
	return c.attachInvocation.CallUnary(ctx, req)
}

// GetInvocationOutput calls reflw.ingress.v1.Ingress.GetInvocationOutput.
func (c *ingressClient) GetInvocationOutput(ctx context.Context, req *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error) {
	return c.getInvocationOutput.CallUnary(ctx, req)
}

// GetObjectState calls reflw.ingress.v1.Ingress.GetObjectState.
func (c *ingressClient) GetObjectState(ctx context.Context, req *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error) {
	return c.getObjectState.CallUnary(ctx, req)
}

// CancelInvocation calls reflw.ingress.v1.Ingress.CancelInvocation.
func (c *ingressClient) CancelInvocation(ctx context.Context, req *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error) {
	return c.cancelInvocation.CallUnary(ctx, req)
}

// ResolveWorkflowPromise calls reflw.ingress.v1.Ingress.ResolveWorkflowPromise.
func (c *ingressClient) ResolveWorkflowPromise(ctx context.Context, req *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error) {
	return c.resolveWorkflowPromise.CallUnary(ctx, req)
}

// PurgeInvocation calls reflw.ingress.v1.Ingress.PurgeInvocation.
func (c *ingressClient) PurgeInvocation(ctx context.Context, req *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error) {
	return c.purgeInvocation.CallUnary(ctx, req)
}

// ListInvocations calls reflw.ingress.v1.Ingress.ListInvocations.
func (c *ingressClient) ListInvocations(ctx context.Context, req *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error) {
	return c.listInvocations.CallUnary(ctx, req)
}

// StartProcess calls reflw.ingress.v1.Ingress.StartProcess.
func (c *ingressClient) StartProcess(ctx context.Context, req *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error) {
	return c.startProcess.CallUnary(ctx, req)
}

// DeliverMessage calls reflw.ingress.v1.Ingress.DeliverMessage.
func (c *ingressClient) DeliverMessage(ctx context.Context, req *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error) {
	return c.deliverMessage.CallUnary(ctx, req)
}

// GetProcessInstance calls reflw.ingress.v1.Ingress.GetProcessInstance.
func (c *ingressClient) GetProcessInstance(ctx context.Context, req *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error) {
	return c.getProcessInstance.CallUnary(ctx, req)
}

// ListProcessInstances calls reflw.ingress.v1.Ingress.ListProcessInstances.
func (c *ingressClient) ListProcessInstances(ctx context.Context, req *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error) {
	return c.listProcessInstances.CallUnary(ctx, req)
}

// GetProcessInstanceHistory calls reflw.ingress.v1.Ingress.GetProcessInstanceHistory.
func (c *ingressClient) GetProcessInstanceHistory(ctx context.Context, req *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error) {
	return c.getProcessInstanceHistory.CallUnary(ctx, req)
}

// IngressHandler is an implementation of the reflw.ingress.v1.Ingress service.
type IngressHandler interface {
	// AwaitInvocation blocks (up to deadline) until the named invocation
	// reaches Completed and returns its output. Server-side polling of
	// SyncRead today; SSE/streaming is a future evolution.
	AwaitInvocation(context.Context, *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error)
	// ResolveAwakeable completes an outstanding awakeable previously
	// created by a handler via ctx.Awakeable(). Routes to the owning
	// partition by looking up the awakeable directory.
	ResolveAwakeable(context.Context, *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error)
	// DescribeInvocation returns the current status of an invocation
	// without blocking. Read-only debug endpoint.
	DescribeInvocation(context.Context, *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error)
	// AttachInvocation blocks (up to deadline) on an existing invocation
	// and returns its outcome once Completed. Same shape as
	// AwaitInvocation but explicit about attaching to an already-
	// submitted invocation by id.
	AttachInvocation(context.Context, *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error)
	// GetInvocationOutput is a non-blocking lookup of an invocation's
	// current outcome. Returns PENDING for still-running invocations,
	// COMPLETED_OK / COMPLETED_FAILED for terminated ones, UNKNOWN if no
	// such invocation is known to this node.
	GetInvocationOutput(context.Context, *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error)
	// GetObjectState reads a single state value for a virtual object.
	// Routes to the partition owning the object by hashing (service,
	// object_key) through the cluster Partitioner. present=false (not an
	// error) when the key is absent.
	GetObjectState(context.Context, *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error)
	// CancelInvocation forces a running invocation to terminate with
	// FailureCode=9002 (cancelled). Implemented as a __cancel__ signal
	// delivered to the invocation's (service, key); the receiver shard
	// resolves the active InvocationId via KeyLeaseTable and synthesizes
	// a terminal Completed. Idempotent: cancelling an already-completed
	// invocation is a no-op.
	CancelInvocation(context.Context, *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error)
	// ResolveWorkflowPromise resolves or rejects a named workflow-scoped
	// durable promise. Routes by (service, workflow_key) via
	// Partitioner.ShardForTarget; the receiver shard writes PromiseValue
	// and wakes any in-flight Promise(name).Result() awaiter. Idempotent
	// against already-completed promises: succeeded=false signals
	// "promise already completed" without an error status.
	ResolveWorkflowPromise(context.Context, *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error)
	// PurgeInvocation deletes a Completed invocation's durable rows (inv
	// status, journal, signal inbox/awaiter) immediately, instead of
	// waiting for the retention reaper. Routes by the partition_key encoded
	// in the invocation id. Idempotent and no-op-safe: purging an absent or
	// not-yet-Completed invocation is accepted but changes nothing (the
	// apply arm requires a Completed/Free → Free transition). Does not touch
	// virtual-object state or workflow promise rows.
	PurgeInvocation(context.Context, *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error)
	// ListInvocations lists the caller tenant band's invocations, fanning out
	// across the shards owning the band's LPs (same substrate as
	// ListProcessInstances). Optional service-name and state filters; capped by
	// limit. Read-only — no proposal.
	ListInvocations(context.Context, *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error)
	// StartProcess launches a new reflwos BPMN/CMMN instance. Routes to the
	// partition owning (tenant, model name, instance_key) and proposes a start
	// ProcessEvent (model_ref + kind set). Idempotent per (model, instance_key):
	// a start for an already-existing instance is dropped by the apply path. When
	// instance_key is empty the server mints a random one (then not idempotent).
	StartProcess(context.Context, *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error)
	// DeliverMessage correlates an inbound message/signal to parked process
	// instances. Routes to the partition owning (tenant, message_name,
	// correlation_key) and proposes DeliverProcessMessage, which fans the message
	// out to every instance subscribed on that (message_name, correlation_key).
	// An empty correlation_key addresses every instance waiting on the name (BPMN
	// signal broadcast). Messages with no current subscriber are dropped.
	DeliverMessage(context.Context, *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error)
	// GetProcessInstance is a linearizable read of one instance's current state,
	// routed by (tenant, model name, instance_key) like StartProcess. It exists
	// so a caller without an await RPC can observe lifecycle: present=false means
	// the instance never started OR already reached a terminal and was reaped
	// (completion is immediate-reap, so a COMPLETED record never lingers);
	// present=true with active_seq>0 means a turn is in flight; present=true with
	// active_seq==0 means idle/parked on an external wait (a timer that will fire,
	// or a message/signal subscription). Read-only — no proposal.
	GetProcessInstance(context.Context, *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error)
	// ListProcessInstances lists the caller tenant band's process instances,
	// fanning out across the shards owning the band's LPs. Optional model-name and
	// status filters; capped by limit.
	ListProcessInstances(context.Context, *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error)
	// GetProcessInstanceHistory reads one instance's append-only activity timeline
	// (start, inbound events, task dispatch/complete, timer arm/fire, child
	// start/complete, subscribe/unsubscribe, message received, terminal), routed by
	// (tenant, model name, instance_key) like GetProcessInstance. Read-only — no
	// proposal. The timeline is bounded live (keep-last-N) and survives a terminal
	// only within the instance's retention window (historyTimeToLive); present=false
	// means the instance never started or was reaped. Page forward with after_seq.
	GetProcessInstanceHistory(context.Context, *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error)
}

// NewIngressHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngressHandler(svc IngressHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingressMethods := ingressv1.File_ingressv1_ingress_proto.Services().ByName("Ingress").Methods()
	ingressAwaitInvocationHandler := connect.NewUnaryHandler(
		IngressAwaitInvocationProcedure,
		svc.AwaitInvocation,
		connect.WithSchema(ingressMethods.ByName("AwaitInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressResolveAwakeableHandler := connect.NewUnaryHandler(
		IngressResolveAwakeableProcedure,
		svc.ResolveAwakeable,
		connect.WithSchema(ingressMethods.ByName("ResolveAwakeable")),
		connect.WithHandlerOptions(opts...),
	)
	ingressDescribeInvocationHandler := connect.NewUnaryHandler(
		IngressDescribeInvocationProcedure,
		svc.DescribeInvocation,
		connect.WithSchema(ingressMethods.ByName("DescribeInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressAttachInvocationHandler := connect.NewUnaryHandler(
		IngressAttachInvocationProcedure,
		svc.AttachInvocation,
		connect.WithSchema(ingressMethods.ByName("AttachInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetInvocationOutputHandler := connect.NewUnaryHandler(
		IngressGetInvocationOutputProcedure,
		svc.GetInvocationOutput,
		connect.WithSchema(ingressMethods.ByName("GetInvocationOutput")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetObjectStateHandler := connect.NewUnaryHandler(
		IngressGetObjectStateProcedure,
		svc.GetObjectState,
		connect.WithSchema(ingressMethods.ByName("GetObjectState")),
		connect.WithHandlerOptions(opts...),
	)
	ingressCancelInvocationHandler := connect.NewUnaryHandler(
		IngressCancelInvocationProcedure,
		svc.CancelInvocation,
		connect.WithSchema(ingressMethods.ByName("CancelInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressResolveWorkflowPromiseHandler := connect.NewUnaryHandler(
		IngressResolveWorkflowPromiseProcedure,
		svc.ResolveWorkflowPromise,
		connect.WithSchema(ingressMethods.ByName("ResolveWorkflowPromise")),
		connect.WithHandlerOptions(opts...),
	)
	ingressPurgeInvocationHandler := connect.NewUnaryHandler(
		IngressPurgeInvocationProcedure,
		svc.PurgeInvocation,
		connect.WithSchema(ingressMethods.ByName("PurgeInvocation")),
		connect.WithHandlerOptions(opts...),
	)
	ingressListInvocationsHandler := connect.NewUnaryHandler(
		IngressListInvocationsProcedure,
		svc.ListInvocations,
		connect.WithSchema(ingressMethods.ByName("ListInvocations")),
		connect.WithHandlerOptions(opts...),
	)
	ingressStartProcessHandler := connect.NewUnaryHandler(
		IngressStartProcessProcedure,
		svc.StartProcess,
		connect.WithSchema(ingressMethods.ByName("StartProcess")),
		connect.WithHandlerOptions(opts...),
	)
	ingressDeliverMessageHandler := connect.NewUnaryHandler(
		IngressDeliverMessageProcedure,
		svc.DeliverMessage,
		connect.WithSchema(ingressMethods.ByName("DeliverMessage")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetProcessInstanceHandler := connect.NewUnaryHandler(
		IngressGetProcessInstanceProcedure,
		svc.GetProcessInstance,
		connect.WithSchema(ingressMethods.ByName("GetProcessInstance")),
		connect.WithHandlerOptions(opts...),
	)
	ingressListProcessInstancesHandler := connect.NewUnaryHandler(
		IngressListProcessInstancesProcedure,
		svc.ListProcessInstances,
		connect.WithSchema(ingressMethods.ByName("ListProcessInstances")),
		connect.WithHandlerOptions(opts...),
	)
	ingressGetProcessInstanceHistoryHandler := connect.NewUnaryHandler(
		IngressGetProcessInstanceHistoryProcedure,
		svc.GetProcessInstanceHistory,
		connect.WithSchema(ingressMethods.ByName("GetProcessInstanceHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/reflw.ingress.v1.Ingress/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngressAwaitInvocationProcedure:
			ingressAwaitInvocationHandler.ServeHTTP(w, r)
		case IngressResolveAwakeableProcedure:
			ingressResolveAwakeableHandler.ServeHTTP(w, r)
		case IngressDescribeInvocationProcedure:
			ingressDescribeInvocationHandler.ServeHTTP(w, r)
		case IngressAttachInvocationProcedure:
			ingressAttachInvocationHandler.ServeHTTP(w, r)
		case IngressGetInvocationOutputProcedure:
			ingressGetInvocationOutputHandler.ServeHTTP(w, r)
		case IngressGetObjectStateProcedure:
			ingressGetObjectStateHandler.ServeHTTP(w, r)
		case IngressCancelInvocationProcedure:
			ingressCancelInvocationHandler.ServeHTTP(w, r)
		case IngressResolveWorkflowPromiseProcedure:
			ingressResolveWorkflowPromiseHandler.ServeHTTP(w, r)
		case IngressPurgeInvocationProcedure:
			ingressPurgeInvocationHandler.ServeHTTP(w, r)
		case IngressListInvocationsProcedure:
			ingressListInvocationsHandler.ServeHTTP(w, r)
		case IngressStartProcessProcedure:
			ingressStartProcessHandler.ServeHTTP(w, r)
		case IngressDeliverMessageProcedure:
			ingressDeliverMessageHandler.ServeHTTP(w, r)
		case IngressGetProcessInstanceProcedure:
			ingressGetProcessInstanceHandler.ServeHTTP(w, r)
		case IngressListProcessInstancesProcedure:
			ingressListProcessInstancesHandler.ServeHTTP(w, r)
		case IngressGetProcessInstanceHistoryProcedure:
			ingressGetProcessInstanceHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngressHandler returns CodeUnimplemented from all methods.
type UnimplementedIngressHandler struct{}

func (UnimplementedIngressHandler) AwaitInvocation(context.Context, *connect.Request[ingressv1.AwaitInvocationRequest]) (*connect.Response[ingressv1.AwaitInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.AwaitInvocation is not implemented"))
}

func (UnimplementedIngressHandler) ResolveAwakeable(context.Context, *connect.Request[ingressv1.ResolveAwakeableRequest]) (*connect.Response[ingressv1.ResolveAwakeableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ResolveAwakeable is not implemented"))
}

func (UnimplementedIngressHandler) DescribeInvocation(context.Context, *connect.Request[ingressv1.DescribeInvocationRequest]) (*connect.Response[ingressv1.DescribeInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.DescribeInvocation is not implemented"))
}

func (UnimplementedIngressHandler) AttachInvocation(context.Context, *connect.Request[ingressv1.AttachInvocationRequest]) (*connect.Response[ingressv1.AttachInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.AttachInvocation is not implemented"))
}

func (UnimplementedIngressHandler) GetInvocationOutput(context.Context, *connect.Request[ingressv1.GetInvocationOutputRequest]) (*connect.Response[ingressv1.GetInvocationOutputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetInvocationOutput is not implemented"))
}

func (UnimplementedIngressHandler) GetObjectState(context.Context, *connect.Request[ingressv1.GetObjectStateRequest]) (*connect.Response[ingressv1.GetObjectStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetObjectState is not implemented"))
}

func (UnimplementedIngressHandler) CancelInvocation(context.Context, *connect.Request[ingressv1.CancelInvocationRequest]) (*connect.Response[ingressv1.CancelInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.CancelInvocation is not implemented"))
}

func (UnimplementedIngressHandler) ResolveWorkflowPromise(context.Context, *connect.Request[ingressv1.ResolveWorkflowPromiseRequest]) (*connect.Response[ingressv1.ResolveWorkflowPromiseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ResolveWorkflowPromise is not implemented"))
}

func (UnimplementedIngressHandler) PurgeInvocation(context.Context, *connect.Request[ingressv1.PurgeInvocationRequest]) (*connect.Response[ingressv1.PurgeInvocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.PurgeInvocation is not implemented"))
}

func (UnimplementedIngressHandler) ListInvocations(context.Context, *connect.Request[ingressv1.ListInvocationsRequest]) (*connect.Response[ingressv1.ListInvocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ListInvocations is not implemented"))
}

func (UnimplementedIngressHandler) StartProcess(context.Context, *connect.Request[ingressv1.StartProcessRequest]) (*connect.Response[ingressv1.StartProcessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.StartProcess is not implemented"))
}

func (UnimplementedIngressHandler) DeliverMessage(context.Context, *connect.Request[ingressv1.DeliverMessageRequest]) (*connect.Response[ingressv1.DeliverMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.DeliverMessage is not implemented"))
}

func (UnimplementedIngressHandler) GetProcessInstance(context.Context, *connect.Request[ingressv1.GetProcessInstanceRequest]) (*connect.Response[ingressv1.GetProcessInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetProcessInstance is not implemented"))
}

func (UnimplementedIngressHandler) ListProcessInstances(context.Context, *connect.Request[ingressv1.ListProcessInstancesRequest]) (*connect.Response[ingressv1.ListProcessInstancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.ListProcessInstances is not implemented"))
}

func (UnimplementedIngressHandler) GetProcessInstanceHistory(context.Context, *connect.Request[ingressv1.GetProcessInstanceHistoryRequest]) (*connect.Response[ingressv1.GetProcessInstanceHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reflw.ingress.v1.Ingress.GetProcessInstanceHistory is not implemented"))
}
