// Reflow inter-node Delivery service.
//
// Every reflwd process hosts a Delivery gRPC server. When a shard's
// leader-side OutboxService sees an OutboxEnvelope whose
// destination_shard_id does not match the local shard, it dials the
// destination shard's current leader via this service and streams the
// envelope as a Command. The receiver's Delivery server calls the local
// RaftProposer.ProposeIngress on the destination shard if and only if
// this node holds that shard's leadership.
//
// A successful Ack means "I have durably accepted responsibility for
// proposing this command via Raft" — durable apply on the receiver
// triggers a reciprocal OutboxAck envelope that pops the sender's
// outbox row. NotLeader carries the receiver's leader hint so the
// sender can re-resolve via the dragonboat gossip ShardView and retry.
//
// Authorization: every RPC on this service requires a "node" principal.
// The starter grpc-go authz policy in internal/auth/starter_policy.json
// restricts /reflw.delivery.v1.Delivery/* to principals matching
// "node/*"; operators may override via Config.Auth.PolicyFile.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deliveryv1/delivery.proto

package deliveryv1

import (
	enginev1 "github.com/twinfer/reflw/proto/enginev1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliverRequest carries an outbox envelope that the sender wants
// proposed on shard_id. producer_id and seq must match the values
// stamped on the envelope's ArbitraryDedup header so the receiver's
// dedup absorbs replayed sends on crash recovery.
type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Command       *enginev1.Command      `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *DeliverRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *DeliverRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DeliverRequest) GetCommand() *enginev1.Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// DeliverResponse is the single reply for a DeliverRequest. The seq
// field is echoed from the request for correlation on the bidi stream.
type DeliverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DeliverResponse_Ack
	//	*DeliverResponse_NotLeader
	//	*DeliverResponse_Err
	Kind          isDeliverResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DeliverResponse) GetKind() isDeliverResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DeliverResponse) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*DeliverResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *DeliverResponse) GetNotLeader() *NotLeader {
	if x != nil {
		if x, ok := x.Kind.(*DeliverResponse_NotLeader); ok {
			return x.NotLeader
		}
	}
	return nil
}

func (x *DeliverResponse) GetErr() *Err {
	if x != nil {
		if x, ok := x.Kind.(*DeliverResponse_Err); ok {
			return x.Err
		}
	}
	return nil
}

type isDeliverResponse_Kind interface {
	isDeliverResponse_Kind()
}

type DeliverResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type DeliverResponse_NotLeader struct {
	NotLeader *NotLeader `protobuf:"bytes,3,opt,name=not_leader,json=notLeader,proto3,oneof"`
}

type DeliverResponse_Err struct {
	Err *Err `protobuf:"bytes,4,opt,name=err,proto3,oneof"`
}

func (*DeliverResponse_Ack) isDeliverResponse_Kind() {}

func (*DeliverResponse_NotLeader) isDeliverResponse_Kind() {}

func (*DeliverResponse_Err) isDeliverResponse_Kind() {}

// Ack confirms the destination shard's leader on this node has called
// SyncPropose and the command is durably accepted.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{2}
}

// NotLeader indicates this node is not the leader of the requested
// shard. leader_node_id is a hint from the local ShardView; sender
// should re-resolve via gossip and retry.
type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderNodeId  uint64                 `protobuf:"varint,1,opt,name=leader_node_id,json=leaderNodeId,proto3" json:"leader_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *NotLeader) GetLeaderNodeId() uint64 {
	if x != nil {
		return x.LeaderNodeId
	}
	return 0
}

// Err is a transient error (e.g. shard not started, dragonboat
// timeout). Sender should back off and retry.
type Err struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err) Reset() {
	*x = Err{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err) ProtoMessage() {}

func (x *Err) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err.ProtoReflect.Descriptor instead.
func (*Err) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *Err) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UploadLPTransferSSTRequest is one frame of the SST upload stream.
// First frame MUST be a header; subsequent frames MUST be chunks.
type UploadLPTransferSSTRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*UploadLPTransferSSTRequest_Header
	//	*UploadLPTransferSSTRequest_Chunk
	Kind          isUploadLPTransferSSTRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLPTransferSSTRequest) Reset() {
	*x = UploadLPTransferSSTRequest{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLPTransferSSTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLPTransferSSTRequest) ProtoMessage() {}

func (x *UploadLPTransferSSTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLPTransferSSTRequest.ProtoReflect.Descriptor instead.
func (*UploadLPTransferSSTRequest) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *UploadLPTransferSSTRequest) GetKind() isUploadLPTransferSSTRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UploadLPTransferSSTRequest) GetHeader() *UploadLPTransferSSTHeader {
	if x != nil {
		if x, ok := x.Kind.(*UploadLPTransferSSTRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *UploadLPTransferSSTRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Kind.(*UploadLPTransferSSTRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadLPTransferSSTRequest_Kind interface {
	isUploadLPTransferSSTRequest_Kind()
}

type UploadLPTransferSSTRequest_Header struct {
	Header *UploadLPTransferSSTHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type UploadLPTransferSSTRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadLPTransferSSTRequest_Header) isUploadLPTransferSSTRequest_Kind() {}

func (*UploadLPTransferSSTRequest_Chunk) isUploadLPTransferSSTRequest_Kind() {}

// UploadLPTransferSSTHeader is the first stream frame. The server uses
// dest_shard to confirm leadership locally and rejects with NotLeader
// when this node does not host the dest shard's leader. namespace is a
// short tag (e.g. "inv", "journal", "timer_primary") that determines
// the on-disk filename `<namespace>.sst` under
// `<dataDir>.lpstage_in/<transfer_id>/`. size_bytes and sha256_hex
// belt the body against truncation / mid-stream corruption.
type UploadLPTransferSSTHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestShard     uint64                 `protobuf:"varint,1,opt,name=dest_shard,json=destShard,proto3" json:"dest_shard,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256Hex     string                 `protobuf:"bytes,5,opt,name=sha256_hex,json=sha256Hex,proto3" json:"sha256_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLPTransferSSTHeader) Reset() {
	*x = UploadLPTransferSSTHeader{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLPTransferSSTHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLPTransferSSTHeader) ProtoMessage() {}

func (x *UploadLPTransferSSTHeader) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLPTransferSSTHeader.ProtoReflect.Descriptor instead.
func (*UploadLPTransferSSTHeader) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *UploadLPTransferSSTHeader) GetDestShard() uint64 {
	if x != nil {
		return x.DestShard
	}
	return 0
}

func (x *UploadLPTransferSSTHeader) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *UploadLPTransferSSTHeader) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UploadLPTransferSSTHeader) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadLPTransferSSTHeader) GetSha256Hex() string {
	if x != nil {
		return x.Sha256Hex
	}
	return ""
}

// UploadLPTransferSSTResponse is the single reply for one upload.
type UploadLPTransferSSTResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*UploadLPTransferSSTResponse_Ack
	//	*UploadLPTransferSSTResponse_NotLeader
	//	*UploadLPTransferSSTResponse_Err
	Kind          isUploadLPTransferSSTResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLPTransferSSTResponse) Reset() {
	*x = UploadLPTransferSSTResponse{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLPTransferSSTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLPTransferSSTResponse) ProtoMessage() {}

func (x *UploadLPTransferSSTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLPTransferSSTResponse.ProtoReflect.Descriptor instead.
func (*UploadLPTransferSSTResponse) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *UploadLPTransferSSTResponse) GetKind() isUploadLPTransferSSTResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UploadLPTransferSSTResponse) GetAck() *UploadLPTransferSSTAck {
	if x != nil {
		if x, ok := x.Kind.(*UploadLPTransferSSTResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *UploadLPTransferSSTResponse) GetNotLeader() *NotLeader {
	if x != nil {
		if x, ok := x.Kind.(*UploadLPTransferSSTResponse_NotLeader); ok {
			return x.NotLeader
		}
	}
	return nil
}

func (x *UploadLPTransferSSTResponse) GetErr() *Err {
	if x != nil {
		if x, ok := x.Kind.(*UploadLPTransferSSTResponse_Err); ok {
			return x.Err
		}
	}
	return nil
}

type isUploadLPTransferSSTResponse_Kind interface {
	isUploadLPTransferSSTResponse_Kind()
}

type UploadLPTransferSSTResponse_Ack struct {
	Ack *UploadLPTransferSSTAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type UploadLPTransferSSTResponse_NotLeader struct {
	NotLeader *NotLeader `protobuf:"bytes,2,opt,name=not_leader,json=notLeader,proto3,oneof"`
}

type UploadLPTransferSSTResponse_Err struct {
	Err *Err `protobuf:"bytes,3,opt,name=err,proto3,oneof"`
}

func (*UploadLPTransferSSTResponse_Ack) isUploadLPTransferSSTResponse_Kind() {}

func (*UploadLPTransferSSTResponse_NotLeader) isUploadLPTransferSSTResponse_Kind() {}

func (*UploadLPTransferSSTResponse_Err) isUploadLPTransferSSTResponse_Kind() {}

// UploadLPTransferSSTAck confirms the file was written, fsynced, and
// renamed into place. relative_path is rooted at the dest's
// `<dataDir>.lpstage_in/<transfer_id>/` directory and is what the
// source must echo back in TransferSSTRef.relative_path.
type UploadLPTransferSSTAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelativePath  string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLPTransferSSTAck) Reset() {
	*x = UploadLPTransferSSTAck{}
	mi := &file_deliveryv1_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLPTransferSSTAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLPTransferSSTAck) ProtoMessage() {}

func (x *UploadLPTransferSSTAck) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryv1_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLPTransferSSTAck.ProtoReflect.Descriptor instead.
func (*UploadLPTransferSSTAck) Descriptor() ([]byte, []int) {
	return file_deliveryv1_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *UploadLPTransferSSTAck) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

var File_deliveryv1_delivery_proto protoreflect.FileDescriptor

const file_deliveryv1_delivery_proto_rawDesc = "" +
	"\n" +
	"\x19deliveryv1/delivery.proto\x12\x11reflw.delivery.v1\x1a\x15enginev1/engine.proto\"\x92\x01\n" +
	"\x0eDeliverRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x122\n" +
	"\acommand\x18\x04 \x01(\v2\x18.reflw.engine.v1.CommandR\acommand\"\xc2\x01\n" +
	"\x0fDeliverResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12*\n" +
	"\x03ack\x18\x02 \x01(\v2\x16.reflw.delivery.v1.AckH\x00R\x03ack\x12=\n" +
	"\n" +
	"not_leader\x18\x03 \x01(\v2\x1c.reflw.delivery.v1.NotLeaderH\x00R\tnotLeader\x12*\n" +
	"\x03err\x18\x04 \x01(\v2\x16.reflw.delivery.v1.ErrH\x00R\x03errB\x06\n" +
	"\x04kind\"\x05\n" +
	"\x03Ack\"1\n" +
	"\tNotLeader\x12$\n" +
	"\x0eleader_node_id\x18\x01 \x01(\x04R\fleaderNodeId\"\x1f\n" +
	"\x03Err\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x84\x01\n" +
	"\x1aUploadLPTransferSSTRequest\x12F\n" +
	"\x06header\x18\x01 \x01(\v2,.reflw.delivery.v1.UploadLPTransferSSTHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04kind\"\xb7\x01\n" +
	"\x19UploadLPTransferSSTHeader\x12\x1d\n" +
	"\n" +
	"dest_shard\x18\x01 \x01(\x04R\tdestShard\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"sha256_hex\x18\x05 \x01(\tR\tsha256Hex\"\xcf\x01\n" +
	"\x1bUploadLPTransferSSTResponse\x12=\n" +
	"\x03ack\x18\x01 \x01(\v2).reflw.delivery.v1.UploadLPTransferSSTAckH\x00R\x03ack\x12=\n" +
	"\n" +
	"not_leader\x18\x02 \x01(\v2\x1c.reflw.delivery.v1.NotLeaderH\x00R\tnotLeader\x12*\n" +
	"\x03err\x18\x03 \x01(\v2\x16.reflw.delivery.v1.ErrH\x00R\x03errB\x06\n" +
	"\x04kind\"=\n" +
	"\x16UploadLPTransferSSTAck\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath2\xd8\x01\n" +
	"\bDelivery\x12T\n" +
	"\aDeliver\x12!.reflw.delivery.v1.DeliverRequest\x1a\".reflw.delivery.v1.DeliverResponse(\x010\x01\x12v\n" +
	"\x13UploadLPTransferSST\x12-.reflw.delivery.v1.UploadLPTransferSSTRequest\x1a..reflw.delivery.v1.UploadLPTransferSSTResponse(\x01B6Z4github.com/twinfer/reflw/proto/deliveryv1;deliveryv1b\x06proto3"

var (
	file_deliveryv1_delivery_proto_rawDescOnce sync.Once
	file_deliveryv1_delivery_proto_rawDescData []byte
)

func file_deliveryv1_delivery_proto_rawDescGZIP() []byte {
	file_deliveryv1_delivery_proto_rawDescOnce.Do(func() {
		file_deliveryv1_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deliveryv1_delivery_proto_rawDesc), len(file_deliveryv1_delivery_proto_rawDesc)))
	})
	return file_deliveryv1_delivery_proto_rawDescData
}

var file_deliveryv1_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_deliveryv1_delivery_proto_goTypes = []any{
	(*DeliverRequest)(nil),              // 0: reflw.delivery.v1.DeliverRequest
	(*DeliverResponse)(nil),             // 1: reflw.delivery.v1.DeliverResponse
	(*Ack)(nil),                         // 2: reflw.delivery.v1.Ack
	(*NotLeader)(nil),                   // 3: reflw.delivery.v1.NotLeader
	(*Err)(nil),                         // 4: reflw.delivery.v1.Err
	(*UploadLPTransferSSTRequest)(nil),  // 5: reflw.delivery.v1.UploadLPTransferSSTRequest
	(*UploadLPTransferSSTHeader)(nil),   // 6: reflw.delivery.v1.UploadLPTransferSSTHeader
	(*UploadLPTransferSSTResponse)(nil), // 7: reflw.delivery.v1.UploadLPTransferSSTResponse
	(*UploadLPTransferSSTAck)(nil),      // 8: reflw.delivery.v1.UploadLPTransferSSTAck
	(*enginev1.Command)(nil),            // 9: reflw.engine.v1.Command
}
var file_deliveryv1_delivery_proto_depIdxs = []int32{
	9,  // 0: reflw.delivery.v1.DeliverRequest.command:type_name -> reflw.engine.v1.Command
	2,  // 1: reflw.delivery.v1.DeliverResponse.ack:type_name -> reflw.delivery.v1.Ack
	3,  // 2: reflw.delivery.v1.DeliverResponse.not_leader:type_name -> reflw.delivery.v1.NotLeader
	4,  // 3: reflw.delivery.v1.DeliverResponse.err:type_name -> reflw.delivery.v1.Err
	6,  // 4: reflw.delivery.v1.UploadLPTransferSSTRequest.header:type_name -> reflw.delivery.v1.UploadLPTransferSSTHeader
	8,  // 5: reflw.delivery.v1.UploadLPTransferSSTResponse.ack:type_name -> reflw.delivery.v1.UploadLPTransferSSTAck
	3,  // 6: reflw.delivery.v1.UploadLPTransferSSTResponse.not_leader:type_name -> reflw.delivery.v1.NotLeader
	4,  // 7: reflw.delivery.v1.UploadLPTransferSSTResponse.err:type_name -> reflw.delivery.v1.Err
	0,  // 8: reflw.delivery.v1.Delivery.Deliver:input_type -> reflw.delivery.v1.DeliverRequest
	5,  // 9: reflw.delivery.v1.Delivery.UploadLPTransferSST:input_type -> reflw.delivery.v1.UploadLPTransferSSTRequest
	1,  // 10: reflw.delivery.v1.Delivery.Deliver:output_type -> reflw.delivery.v1.DeliverResponse
	7,  // 11: reflw.delivery.v1.Delivery.UploadLPTransferSST:output_type -> reflw.delivery.v1.UploadLPTransferSSTResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_deliveryv1_delivery_proto_init() }
func file_deliveryv1_delivery_proto_init() {
	if File_deliveryv1_delivery_proto != nil {
		return
	}
	file_deliveryv1_delivery_proto_msgTypes[1].OneofWrappers = []any{
		(*DeliverResponse_Ack)(nil),
		(*DeliverResponse_NotLeader)(nil),
		(*DeliverResponse_Err)(nil),
	}
	file_deliveryv1_delivery_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadLPTransferSSTRequest_Header)(nil),
		(*UploadLPTransferSSTRequest_Chunk)(nil),
	}
	file_deliveryv1_delivery_proto_msgTypes[7].OneofWrappers = []any{
		(*UploadLPTransferSSTResponse_Ack)(nil),
		(*UploadLPTransferSSTResponse_NotLeader)(nil),
		(*UploadLPTransferSSTResponse_Err)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deliveryv1_delivery_proto_rawDesc), len(file_deliveryv1_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deliveryv1_delivery_proto_goTypes,
		DependencyIndexes: file_deliveryv1_delivery_proto_depIdxs,
		MessageInfos:      file_deliveryv1_delivery_proto_msgTypes,
	}.Build()
	File_deliveryv1_delivery_proto = out.File
	file_deliveryv1_delivery_proto_goTypes = nil
	file_deliveryv1_delivery_proto_depIdxs = nil
}
