// Reflow cluster Admin service.
//
// Every reflowd process hosts an Admin Connect RPC server on a
// dedicated port (typically :8082). The server is mTLS-protected
// against the cluster CA; the caller's SPIFFE URI SAN identifies its
// role (`spiffe://<trust-domain>/operator/<name>` for operators). The
// `reflowd cluster ...` CLI is the canonical client.
//
// Authorization lives in the shared starter authz policy (see
// internal/auth/starter_policy.json or the operator-supplied policy
// file) consumed by both the gRPC delivery interceptor and the
// Connect HTTP middleware. The starter policy restricts
// /reflow.admin.v1.Admin/* to principals matching "operator/*".
//
// Mutating RPCs (AddNode, RemoveNode) translate to shard-0 Raft
// proposals; the apply arms in the metadata FSM and the metadata-
// leader rebalancer drive the rest. Read RPCs (ListNodes,
// ListPartitions, ListSnapshots) issue a SyncRead against shard 0 or
// the local SnapshotRepository.
//
// CreateSnapshot triggers an immediate dragonboat Exported snapshot of
// the requested partition shard; the resulting export dir is archived
// into the configured SnapshotRepository.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: adminv1/admin.proto

package adminv1

import (
	enginev1 "github.com/twinfer/reflow/proto/enginev1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	GossipAddr    string                 `protobuf:"bytes,3,opt,name=gossip_addr,json=gossipAddr,proto3" json:"gossip_addr,omitempty"`
	GrpcEndpoint  string                 `protobuf:"bytes,4,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	NodeHostId    string                 `protobuf:"bytes,5,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AddNodeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AddNodeRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *AddNodeRequest) GetGossipAddr() string {
	if x != nil {
		return x.GossipAddr
	}
	return ""
}

func (x *AddNodeRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *AddNodeRequest) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

type AddNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assignment_epoch after the new node was registered. The caller can
	// poll ListPartitions until shards converge.
	AssignmentEpoch uint64 `protobuf:"varint,1,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AddNodeResponse) GetAssignmentEpoch() uint64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveNodeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type RemoveNodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssignmentEpoch uint64                 `protobuf:"varint,1,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveNodeResponse) GetAssignmentEpoch() uint64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Nodes         []*enginev1.NodeMembership `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*enginev1.NodeMembership {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{6}
}

type ListPartitionsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Table         *enginev1.PartitionTable `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListPartitionsResponse) GetTable() *enginev1.PartitionTable {
	if x != nil {
		return x.Table
	}
	return nil
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSnapshotRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSnapshotResponse) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *CreateSnapshotResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CreateSnapshotResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListSnapshotsRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type SnapshotRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShardId         uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Index           uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,4,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRef) Reset() {
	*x = SnapshotRef{}
	mi := &file_adminv1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRef) ProtoMessage() {}

func (x *SnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRef.ProtoReflect.Descriptor instead.
func (*SnapshotRef) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotRef) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SnapshotRef) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotRef) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotRef         `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotRef {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSnapshotRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *DeleteSnapshotRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{14}
}

// RegisterDeploymentRequest names a handler endpoint reachable over
// HTTP/2. URL scheme must be http:// or https://; the engine dials
// the handler via Connect RPC.
type RegisterDeploymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional per-invocation cap on journal entries for this
	// deployment. 0 = engine default (10_000). The engine clamps to a
	// hard ceiling (100_000).
	MaxJournalEntries uint32 `protobuf:"varint,2,opt,name=max_journal_entries,json=maxJournalEntries,proto3" json:"max_journal_entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterDeploymentRequest) Reset() {
	*x = RegisterDeploymentRequest{}
	mi := &file_adminv1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeploymentRequest) ProtoMessage() {}

func (x *RegisterDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeploymentRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterDeploymentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterDeploymentRequest) GetMaxJournalEntries() uint32 {
	if x != nil {
		return x.MaxJournalEntries
	}
	return 0
}

type RegisterDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeploymentResponse) Reset() {
	*x = RegisterDeploymentResponse{}
	mi := &file_adminv1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeploymentResponse) ProtoMessage() {}

func (x *RegisterDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeploymentResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterDeploymentResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

// LeaderHint is attached as a connect.Error detail on
// connect.CodeUnavailable returned by mutating Admin RPCs when the
// receiving node is not the metadata leader. Clients (joiner's SelfJoin
// caller and the `reflowd cluster ...` CLI) extract it, dial
// admin_endpoint, retry.
type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AdminEndpoint string                 `protobuf:"bytes,2,opt,name=admin_endpoint,json=adminEndpoint,proto3" json:"admin_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_adminv1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_adminv1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_adminv1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *LeaderHint) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LeaderHint) GetAdminEndpoint() string {
	if x != nil {
		return x.AdminEndpoint
	}
	return ""
}

var File_adminv1_admin_proto protoreflect.FileDescriptor

const file_adminv1_admin_proto_rawDesc = "" +
	"\n" +
	"\x13adminv1/admin.proto\x12\x0freflow.admin.v1\x1a\x15enginev1/engine.proto\"\xae\x01\n" +
	"\x0eAddNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1f\n" +
	"\vgossip_addr\x18\x03 \x01(\tR\n" +
	"gossipAddr\x12#\n" +
	"\rgrpc_endpoint\x18\x04 \x01(\tR\fgrpcEndpoint\x12 \n" +
	"\fnode_host_id\x18\x05 \x01(\tR\n" +
	"nodeHostId\"<\n" +
	"\x0fAddNodeResponse\x12)\n" +
	"\x10assignment_epoch\x18\x01 \x01(\x04R\x0fassignmentEpoch\",\n" +
	"\x11RemoveNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\"?\n" +
	"\x12RemoveNodeResponse\x12)\n" +
	"\x10assignment_epoch\x18\x01 \x01(\x04R\x0fassignmentEpoch\"\x12\n" +
	"\x10ListNodesRequest\"K\n" +
	"\x11ListNodesResponse\x126\n" +
	"\x05nodes\x18\x01 \x03(\v2 .reflow.engine.v1.NodeMembershipR\x05nodes\"\x17\n" +
	"\x15ListPartitionsRequest\"P\n" +
	"\x16ListPartitionsResponse\x126\n" +
	"\x05table\x18\x01 \x01(\v2 .reflow.engine.v1.PartitionTableR\x05table\"2\n" +
	"\x15CreateSnapshotRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\"h\n" +
	"\x16CreateSnapshotResponse\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"1\n" +
	"\x14ListSnapshotsRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\"\x8a\x01\n" +
	"\vSnapshotRef\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12+\n" +
	"\x12created_at_unix_ms\x18\x04 \x01(\x03R\x0fcreatedAtUnixMs\"S\n" +
	"\x15ListSnapshotsResponse\x12:\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1c.reflow.admin.v1.SnapshotRefR\tsnapshots\"H\n" +
	"\x15DeleteSnapshotRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"\x18\n" +
	"\x16DeleteSnapshotResponse\"]\n" +
	"\x19RegisterDeploymentRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12.\n" +
	"\x13max_journal_entries\x18\x02 \x01(\rR\x11maxJournalEntries\"A\n" +
	"\x1aRegisterDeploymentResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"L\n" +
	"\n" +
	"LeaderHint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12%\n" +
	"\x0eadmin_endpoint\x18\x02 \x01(\tR\radminEndpoint2\xc7\x06\n" +
	"\x05Admin\x12L\n" +
	"\aAddNode\x12\x1f.reflow.admin.v1.AddNodeRequest\x1a .reflow.admin.v1.AddNodeResponse\x12M\n" +
	"\bSelfJoin\x12\x1f.reflow.admin.v1.AddNodeRequest\x1a .reflow.admin.v1.AddNodeResponse\x12U\n" +
	"\n" +
	"RemoveNode\x12\".reflow.admin.v1.RemoveNodeRequest\x1a#.reflow.admin.v1.RemoveNodeResponse\x12R\n" +
	"\tListNodes\x12!.reflow.admin.v1.ListNodesRequest\x1a\".reflow.admin.v1.ListNodesResponse\x12a\n" +
	"\x0eListPartitions\x12&.reflow.admin.v1.ListPartitionsRequest\x1a'.reflow.admin.v1.ListPartitionsResponse\x12a\n" +
	"\x0eCreateSnapshot\x12&.reflow.admin.v1.CreateSnapshotRequest\x1a'.reflow.admin.v1.CreateSnapshotResponse\x12^\n" +
	"\rListSnapshots\x12%.reflow.admin.v1.ListSnapshotsRequest\x1a&.reflow.admin.v1.ListSnapshotsResponse\x12a\n" +
	"\x0eDeleteSnapshot\x12&.reflow.admin.v1.DeleteSnapshotRequest\x1a'.reflow.admin.v1.DeleteSnapshotResponse\x12m\n" +
	"\x12RegisterDeployment\x12*.reflow.admin.v1.RegisterDeploymentRequest\x1a+.reflow.admin.v1.RegisterDeploymentResponseB1Z/github.com/twinfer/reflow/proto/adminv1;adminv1b\x06proto3"

var (
	file_adminv1_admin_proto_rawDescOnce sync.Once
	file_adminv1_admin_proto_rawDescData []byte
)

func file_adminv1_admin_proto_rawDescGZIP() []byte {
	file_adminv1_admin_proto_rawDescOnce.Do(func() {
		file_adminv1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adminv1_admin_proto_rawDesc), len(file_adminv1_admin_proto_rawDesc)))
	})
	return file_adminv1_admin_proto_rawDescData
}

var file_adminv1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_adminv1_admin_proto_goTypes = []any{
	(*AddNodeRequest)(nil),             // 0: reflow.admin.v1.AddNodeRequest
	(*AddNodeResponse)(nil),            // 1: reflow.admin.v1.AddNodeResponse
	(*RemoveNodeRequest)(nil),          // 2: reflow.admin.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),         // 3: reflow.admin.v1.RemoveNodeResponse
	(*ListNodesRequest)(nil),           // 4: reflow.admin.v1.ListNodesRequest
	(*ListNodesResponse)(nil),          // 5: reflow.admin.v1.ListNodesResponse
	(*ListPartitionsRequest)(nil),      // 6: reflow.admin.v1.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),     // 7: reflow.admin.v1.ListPartitionsResponse
	(*CreateSnapshotRequest)(nil),      // 8: reflow.admin.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),     // 9: reflow.admin.v1.CreateSnapshotResponse
	(*ListSnapshotsRequest)(nil),       // 10: reflow.admin.v1.ListSnapshotsRequest
	(*SnapshotRef)(nil),                // 11: reflow.admin.v1.SnapshotRef
	(*ListSnapshotsResponse)(nil),      // 12: reflow.admin.v1.ListSnapshotsResponse
	(*DeleteSnapshotRequest)(nil),      // 13: reflow.admin.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),     // 14: reflow.admin.v1.DeleteSnapshotResponse
	(*RegisterDeploymentRequest)(nil),  // 15: reflow.admin.v1.RegisterDeploymentRequest
	(*RegisterDeploymentResponse)(nil), // 16: reflow.admin.v1.RegisterDeploymentResponse
	(*LeaderHint)(nil),                 // 17: reflow.admin.v1.LeaderHint
	(*enginev1.NodeMembership)(nil),    // 18: reflow.engine.v1.NodeMembership
	(*enginev1.PartitionTable)(nil),    // 19: reflow.engine.v1.PartitionTable
}
var file_adminv1_admin_proto_depIdxs = []int32{
	18, // 0: reflow.admin.v1.ListNodesResponse.nodes:type_name -> reflow.engine.v1.NodeMembership
	19, // 1: reflow.admin.v1.ListPartitionsResponse.table:type_name -> reflow.engine.v1.PartitionTable
	11, // 2: reflow.admin.v1.ListSnapshotsResponse.snapshots:type_name -> reflow.admin.v1.SnapshotRef
	0,  // 3: reflow.admin.v1.Admin.AddNode:input_type -> reflow.admin.v1.AddNodeRequest
	0,  // 4: reflow.admin.v1.Admin.SelfJoin:input_type -> reflow.admin.v1.AddNodeRequest
	2,  // 5: reflow.admin.v1.Admin.RemoveNode:input_type -> reflow.admin.v1.RemoveNodeRequest
	4,  // 6: reflow.admin.v1.Admin.ListNodes:input_type -> reflow.admin.v1.ListNodesRequest
	6,  // 7: reflow.admin.v1.Admin.ListPartitions:input_type -> reflow.admin.v1.ListPartitionsRequest
	8,  // 8: reflow.admin.v1.Admin.CreateSnapshot:input_type -> reflow.admin.v1.CreateSnapshotRequest
	10, // 9: reflow.admin.v1.Admin.ListSnapshots:input_type -> reflow.admin.v1.ListSnapshotsRequest
	13, // 10: reflow.admin.v1.Admin.DeleteSnapshot:input_type -> reflow.admin.v1.DeleteSnapshotRequest
	15, // 11: reflow.admin.v1.Admin.RegisterDeployment:input_type -> reflow.admin.v1.RegisterDeploymentRequest
	1,  // 12: reflow.admin.v1.Admin.AddNode:output_type -> reflow.admin.v1.AddNodeResponse
	1,  // 13: reflow.admin.v1.Admin.SelfJoin:output_type -> reflow.admin.v1.AddNodeResponse
	3,  // 14: reflow.admin.v1.Admin.RemoveNode:output_type -> reflow.admin.v1.RemoveNodeResponse
	5,  // 15: reflow.admin.v1.Admin.ListNodes:output_type -> reflow.admin.v1.ListNodesResponse
	7,  // 16: reflow.admin.v1.Admin.ListPartitions:output_type -> reflow.admin.v1.ListPartitionsResponse
	9,  // 17: reflow.admin.v1.Admin.CreateSnapshot:output_type -> reflow.admin.v1.CreateSnapshotResponse
	12, // 18: reflow.admin.v1.Admin.ListSnapshots:output_type -> reflow.admin.v1.ListSnapshotsResponse
	14, // 19: reflow.admin.v1.Admin.DeleteSnapshot:output_type -> reflow.admin.v1.DeleteSnapshotResponse
	16, // 20: reflow.admin.v1.Admin.RegisterDeployment:output_type -> reflow.admin.v1.RegisterDeploymentResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_adminv1_admin_proto_init() }
func file_adminv1_admin_proto_init() {
	if File_adminv1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adminv1_admin_proto_rawDesc), len(file_adminv1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminv1_admin_proto_goTypes,
		DependencyIndexes: file_adminv1_admin_proto_depIdxs,
		MessageInfos:      file_adminv1_admin_proto_msgTypes,
	}.Build()
	File_adminv1_admin_proto = out.File
	file_adminv1_admin_proto_goTypes = nil
	file_adminv1_admin_proto_depIdxs = nil
}
